use crate::types::{Fact, Question};

pub fn facts() -> Vec<Fact> {
    vec![
        // === RELIGIOUS/SPIRITUAL BELIEFS (early turns) ===
        super::fact("beliefs_values.001", "beliefs_values",
            "Identifies as agnostic, raised in a Buddhist household. Mother still goes to Haedong Yonggungsa temple in Busan.",
            "I'm agnostic. Raised Buddhist - mom still goes to Haedong Yonggungsa. I respect it but don't practice.",
            80, 0.8, &["agnostic", "Buddhist", "raised", "Haedong Yonggungsa"]),
        super::fact("beliefs_values.002", "beliefs_values",
            "Stopped identifying as Buddhist around age 16 after reading about different philosophies",
            "I stopped calling myself Buddhist at 16. Started reading philosophy and just... couldn't commit to one framework.",
            150, 0.6, &["stopped Buddhist", "16", "philosophy"]),
        super::fact("beliefs_values.003", "beliefs_values",
            "Appreciates Buddhist principles like non-attachment and mindfulness, applies them secularly",
            "I still use Buddhist ideas like non-attachment and mindfulness. Just without the religious wrapper.",
            350, 0.5, &["Buddhist principles", "non-attachment", "mindfulness", "secular"]),
        super::fact("beliefs_values.004", "beliefs_values",
            "Goes to temples occasionally for the aesthetic and peace, not worship. Visited Jogyesa in Seoul on Budda's birthday.",
            "I visit temples for the peace, not prayer. Went to Jogyesa on Buddha's birthday. The lanterns were beautiful.",
            800, 0.4, &["temples", "aesthetic", "Jogyesa", "Buddha's birthday"]),
        super::fact("beliefs_values.005", "beliefs_values",
            "Has a small Buddhist-style meditation corner at home but considers meditation secular practice, not religious",
            "My meditation corner has a cushion and incense. It's secular though. Just breathing and being present.",
            1200, 0.4, &["meditation", "secular", "cushion", "incense"]),

        // === POLITICAL VIEWS ===
        super::update("beliefs_values.006", "beliefs_values",
            "Was politically centrist through university, leaned slightly conservative on economic issues",
            "In university I was centrist. Slightly conservative on economics. That's changed.",
            200, 0.6, &["centrist", "university", "conservative", "economics"],
            "political_shift", 1),
        super::update("beliefs_values.007", "beliefs_values",
            "Shifted toward progressive after working in tech startup and seeing income inequality firsthand",
            "Working at startups opened my eyes to inequality. Tech people making millions while service workers struggle. I've moved left.",
            2500, 0.6, &["progressive", "inequality", "shifted left", "tech"],
            "political_shift", 2),
        super::update("beliefs_values.008", "beliefs_values",
            "Now identifies as progressive on social issues, moderate on economic policy. Voted progressive party in last election.",
            "I'm progressive on social issues, moderate on economics. Voted progressive party last election.",
            6000, 0.6, &["progressive", "social issues", "moderate", "voted"],
            "political_shift", 3),

        // === UBI AND ECONOMICS ===
        super::fact("beliefs_values.009", "beliefs_values",
            "Strong advocate for Universal Basic Income (UBI), became interested after reading Andrew Yang's 'The War on Normal People'",
            "I'm a UBI advocate. Andrew Yang's book started it. AI is going to displace so many jobs.",
            300, 0.7, &["UBI", "Universal Basic Income", "Andrew Yang", "advocate"]),
        super::fact("beliefs_values.010", "beliefs_values",
            "Believes UBI would be especially beneficial in Korea's high-pressure education and work culture",
            "UBI in Korea specifically would be transformative. The pressure to work yourself to death here is insane.",
            700, 0.5, &["UBI", "Korea", "work culture", "pressure"]),
        super::fact("beliefs_values.011", "beliefs_values",
            "Had a long debate about UBI with CTO David Kim at a company dinner, David was skeptical",
            "David and I debated UBI for an hour at a team dinner. He's skeptical. I didn't convince him but planted a seed.",
            2800, 0.4, &["UBI", "debate", "David Kim", "skeptical"]),

        // === ENVIRONMENTALISM ===
        super::fact("beliefs_values.012", "beliefs_values",
            "Identifies as an environmentalist, recycles diligently, reduces single-use plastic where possible",
            "I'm an environmentalist. I recycle everything, avoid single-use plastic. Small actions matter.",
            250, 0.6, &["environmentalist", "recycle", "single-use plastic"]),
        super::fact("beliefs_values.013", "beliefs_values",
            "Uses a reusable tumbler from Starbucks and brings own bags to grocery stores",
            "I have a Starbucks tumbler everywhere and my own grocery bags. No plastic bags, no disposable cups.",
            500, 0.4, &["tumbler", "Starbucks", "reusable", "grocery bags"]),
        super::fact("beliefs_values.014", "beliefs_values",
            "Concerned about climate change, supports Korea's transition to renewable energy",
            "Climate change terrifies me. Korea needs to move faster on renewables. We're too dependent on coal.",
            1100, 0.5, &["climate change", "renewable energy", "Korea", "coal"]),
        super::fact("beliefs_values.015", "beliefs_values",
            "Donated to Korea Environmental Movement Alliance once in 2025, 50,000 won",
            "I donated 50K to the Korean Environmental Movement Alliance. Once in 2025. Plan to make it regular.",
            1800, 0.4, &["donation", "Korea Environmental Movement Alliance", "50K", "environmental"]),
        super::fact("beliefs_values.016", "beliefs_values",
            "Tries to eat less meat, averages about 3 vegetarian days per week, not committed to full vegetarianism",
            "I try to go meatless 3 days a week. Not vegetarian but reducing. Samgyeopsal is too good to quit entirely.",
            1500, 0.4, &["vegetarian days", "less meat", "3 days", "reducing"]),

        // === MARRIAGE VIEWS ===
        super::update("beliefs_values.017", "beliefs_values",
            "Was a marriage skeptic through most of his 20s, didn't see the point of the institution",
            "Most of my 20s I was anti-marriage. Didn't see why a legal contract was necessary for love.",
            400, 0.7, &["marriage skeptic", "20s", "institution", "legal contract"],
            "marriage_view", 1),
        super::update("beliefs_values.018", "beliefs_values",
            "After father's death, started rethinking marriage - saw how it mattered to mother's identity and community",
            "After dad died, I saw how marriage mattered to mom's identity. The community, the support system. I started questioning my skepticism.",
            1600, 0.6, &["marriage", "father's death", "rethinking", "mother"],
            "marriage_view", 2),
        super::update("beliefs_values.019", "beliefs_values",
            "Now open to marriage, especially with Eunji. Not rushing but no longer opposed. Views it as partnership, not ownership.",
            "I'm open to marriage now. With Eunji it feels different. Partnership, not ownership. Not rushing but not running away.",
            5000, 0.7, &["open to marriage", "Eunji", "partnership", "not rushing"],
            "marriage_view", 3),

        // === KIDS AND FAMILY ===
        super::update("beliefs_values.020", "beliefs_values",
            "Wants to have kids someday, ideally 1-2 children, but not before age 33-34",
            "I want kids. One or two. But not before 33-34. I want to be stable first.",
            600, 0.7, &["kids", "wants", "1-2 children", "33-34"],
            "kids_view", 1),
        super::update("beliefs_values.021", "beliefs_values",
            "Discussed children with Eunji, they agree on wanting kids but after establishing careers and home",
            "Eunji and I talked about kids. We both want them but after we're settled. Career, home, then family.",
            7000, 0.7, &["kids", "Eunji", "agreed", "after settled"],
            "kids_view", 2),

        // === MEDITATION ===
        super::update("beliefs_values.022", "beliefs_values",
            "Started meditating in September 2025 on Dr. Park's recommendation, 5 minutes daily",
            "Dr. Park suggested meditation. Started with 5 minutes daily in September. Skeptical at first.",
            1700, 0.5, &["meditation", "Dr. Park", "5 minutes", "September 2025"],
            "meditation_practice", 1),
        super::update("beliefs_values.023", "beliefs_values",
            "Increased meditation to 10 minutes daily, switched from Headspace to unguided sitting",
            "Now doing 10 minutes unguided. Headspace was training wheels. Just sitting and breathing now.",
            3500, 0.5, &["meditation", "10 minutes", "unguided", "sitting"],
            "meditation_practice", 2),
        super::update("beliefs_values.024", "beliefs_values",
            "Meditation is now a non-negotiable daily habit, credits it for reduced anxiety and better focus at work",
            "Meditation is non-negotiable now. 10 minutes every morning. My anxiety is measurably lower.",
            7500, 0.5, &["meditation", "non-negotiable", "daily", "anxiety reduction"],
            "meditation_practice", 3),

        // === SOCIAL ISSUES ===
        super::fact("beliefs_values.025", "beliefs_values",
            "Supports LGBTQ+ rights in Korea, attended Seoul Queer Culture Festival in 2024 with Jihye",
            "I support LGBTQ+ rights. Went to Seoul Queer Festival in 2024 with Jihye. Korea has a long way to go.",
            900, 0.6, &["LGBTQ+", "Seoul Queer Festival", "2024", "Jihye"]),
        super::fact("beliefs_values.026", "beliefs_values",
            "Believes in gender equality, advocates for equal pay and parental leave for both parents at Velta",
            "Gender equality isn't debatable for me. I've pushed for equal parental leave at Velta. Both parents.",
            1300, 0.5, &["gender equality", "equal pay", "parental leave", "Velta"]),
        super::fact("beliefs_values.027", "beliefs_values",
            "Concerned about Korea's declining birth rate, believes it's a systemic issue not individual choice",
            "Korea's birth rate crisis is systemic. Housing costs, education costs, work culture. Not because people don't want kids.",
            2200, 0.5, &["birth rate", "Korea", "systemic", "housing costs"]),
        super::fact("beliefs_values.028", "beliefs_values",
            "Supports immigration reform in Korea, believes diversity strengthens society and innovation",
            "Korea needs more immigration. Diversity drives innovation. Our homogeneity is becoming a weakness.",
            2600, 0.5, &["immigration", "Korea", "diversity", "innovation"]),

        // === TECHNOLOGY ETHICS ===
        super::fact("beliefs_values.029", "beliefs_values",
            "Concerned about AI replacing creative jobs but also sees it as a tool that amplifies human creativity",
            "AI scares me as a designer but I also use it daily. It's a tool, not a replacement. For now.",
            1000, 0.6, &["AI", "creative jobs", "tool", "amplifies"]),
        super::fact("beliefs_values.030", "beliefs_values",
            "Believes in data privacy rights, uses VPN on public wifi, concerned about Korean national ID system",
            "Privacy matters. I use VPN on public wifi. Korea's national ID system is a privacy nightmare.",
            1400, 0.5, &["data privacy", "VPN", "national ID", "concerned"]),
        super::fact("beliefs_values.031", "beliefs_values",
            "Against social media addiction by design, thinks platforms should be legally required to show time-spent metrics",
            "Social media is designed to addict. Platforms should be forced to show you how much time you've spent. Transparency.",
            2000, 0.4, &["social media", "addiction", "design", "time-spent"]),

        // === UPDATE CHAIN: Personal philosophy ===
        super::update("beliefs_values.032", "beliefs_values",
            "Life philosophy in early 20s: hustle culture, believed success came from outworking everyone",
            "In my early 20s I was all hustle culture. Work harder than everyone. Sleep when you're dead. So wrong.",
            300, 0.5, &["hustle culture", "early 20s", "outwork", "success"],
            "life_philosophy", 1),
        super::update("beliefs_values.033", "beliefs_values",
            "After burnout and therapy, shifted to work-life balance philosophy: 'sustainable effort over burnout sprints'",
            "After burning out, my philosophy changed. Sustainable effort beats burnout sprints. Dr. Park helped me see that.",
            3000, 0.6, &["work-life balance", "sustainable", "burnout", "Dr. Park"],
            "life_philosophy", 2),
        super::update("beliefs_values.034", "beliefs_values",
            "Current philosophy: 'design a life worth living, not just a career worth having'",
            "My motto now: design a life worth living, not just a career worth having. The whole thing, not just work.",
            8000, 0.5, &["life philosophy", "worth living", "career", "design a life"],
            "life_philosophy", 3),

        // === UPDATE CHAIN: Views on Korean work culture ===
        super::update("beliefs_values.035", "beliefs_values",
            "Critical of Korean work culture (yagun/overtime culture), believes it's productivity theater not actual productivity",
            "Korean yagun (overtime) culture is productivity theater. Being in the office late doesn't mean you're working well.",
            1600, 0.6, &["yagun", "work culture", "productivity theater", "Korean"],
            "work_culture_view", 1),
        super::update("beliefs_values.036", "beliefs_values",
            "Advocated for results-based evaluation at Velta instead of hours-based, Hyunwoo agreed",
            "I pushed for results-based evaluation at Velta. Hyunwoo agreed. Output matters, not face time.",
            4500, 0.5, &["results-based", "evaluation", "Velta", "Hyunwoo"],
            "work_culture_view", 2),

        // === UPDATE CHAIN: Digital minimalism ===
        super::update("beliefs_values.037", "beliefs_values",
            "Read 'Digital Minimalism' by Cal Newport, started implementing screen-free time",
            "Cal Newport's Digital Minimalism changed my habits. Wednesday no-screen nights started from this.",
            2100, 0.5, &["Digital Minimalism", "Cal Newport", "screen-free"],
            "digital_minimalism", 1),
        super::update("beliefs_values.038", "beliefs_values",
            "Deleted Instagram from phone (keeps Mochi's account on iPad only), reduced Twitter to 15 minutes daily",
            "Deleted Instagram from my phone. Mochi's account is iPad only. Twitter capped at 15 minutes. Freedom.",
            5500, 0.4, &["Instagram", "deleted", "Twitter", "15 minutes"],
            "digital_minimalism", 2),

        // === UPDATE CHAIN: Environmental actions ===
        super::update("beliefs_values.039", "beliefs_values",
            "Started buying second-hand clothes from Danggeun Market (Korean Craigslist) to reduce fashion waste",
            "I buy second-hand on Danggeun Market now. Why buy new when perfectly good clothes exist?",
            3200, 0.4, &["second-hand", "Danggeun Market", "fashion waste"],
            "environmental_action", 1),
        super::update("beliefs_values.040", "beliefs_values",
            "Switched to bamboo toothbrush and solid shampoo bar, reducing bathroom plastic",
            "Bamboo toothbrush, solid shampoo bar. Small changes but every piece of plastic not bought matters.",
            6500, 0.4, &["bamboo toothbrush", "shampoo bar", "plastic reduction"],
            "environmental_action", 2),

        // === PERSONAL VALUES ===
        super::fact("beliefs_values.041", "beliefs_values",
            "Core values in order: authenticity, curiosity, kindness, creativity, independence",
            "My core values: authenticity, curiosity, kindness, creativity, independence. In that order.",
            450, 0.6, &["core values", "authenticity", "curiosity", "kindness"]),
        super::fact("beliefs_values.042", "beliefs_values",
            "Believes honesty is the foundation of all relationships, even when it's uncomfortable",
            "Honesty even when it hurts. That's non-negotiable in any relationship. I'd rather hear hard truth.",
            550, 0.5, &["honesty", "foundation", "relationships", "uncomfortable"]),
        super::fact("beliefs_values.043", "beliefs_values",
            "Values quality over quantity in everything: relationships, possessions, work output",
            "Quality over quantity. A few deep friendships over many shallow ones. Fewer great designs over many mediocre ones.",
            750, 0.5, &["quality over quantity", "relationships", "possessions"]),
        super::fact("beliefs_values.044", "beliefs_values",
            "Believes in 'chosen family' alongside biological family, considers Jihye and Soyeon as chosen family",
            "Jihye and Soyeon are chosen family. Blood isn't the only bond that matters.",
            1050, 0.4, &["chosen family", "Jihye", "Soyeon", "bond"]),
        super::fact("beliefs_values.045", "beliefs_values",
            "Hates wasting food, always finishes meals, taught by mother who grew up during harder economic times",
            "I finish every plate. Mom grew up when food was scarce. She taught me never to waste. It stuck.",
            950, 0.4, &["food waste", "finish meals", "mother", "taught"]),

        // === VIEWS ON KOREA ===
        super::fact("beliefs_values.046", "beliefs_values",
            "Loves Korea but acknowledges its problems: overwork culture, educational pressure, housing crisis",
            "I love Korea. But the overwork, education pressure, housing crisis... we need to do better.",
            1350, 0.5, &["Korea", "overwork", "education pressure", "housing crisis"]),
        super::fact("beliefs_values.047", "beliefs_values",
            "Proud of Korean culture (food, music, film, design) gaining global recognition",
            "Korea's cultural rise makes me so proud. K-food, K-cinema, K-design. We have so much to offer.",
            1550, 0.4, &["Korean culture", "proud", "global recognition"]),
        super::fact("beliefs_values.048", "beliefs_values",
            "Believes Korea should engage more with Southeast Asian countries as equals, not just as labor source",
            "Korea treats Southeast Asia as a labor source. We should engage as equals. There's so much to learn from them.",
            2300, 0.4, &["Southeast Asia", "equals", "Korea", "engagement"]),

        // === DEATH AND GRIEF ===
        super::fact("beliefs_values.049", "beliefs_values",
            "Father's death changed perspective on mortality: believes in living fully now rather than deferring happiness",
            "Dad's death at 58 taught me: don't defer happiness. He worked his whole life and barely got to enjoy retirement.",
            500, 0.7, &["father's death", "mortality", "living fully", "don't defer"]),
        super::fact("beliefs_values.050", "beliefs_values",
            "Doesn't believe in afterlife but finds comfort in the idea of being remembered through impact",
            "I don't think there's an afterlife. But being remembered through what you create, who you love... that's enough.",
            1700, 0.5, &["afterlife", "doesn't believe", "remembered", "impact"]),

        // === VIEWS ON EDUCATION ===
        super::fact("beliefs_values.051", "beliefs_values",
            "Critical of Korean education system's emphasis on rote memorization and university entrance exams (Suneung)",
            "Korean education kills creativity. The Suneung system reduces humans to test scores. It needs reform.",
            1900, 0.5, &["education system", "Suneung", "rote memorization", "critical"]),
        super::fact("beliefs_values.052", "beliefs_values",
            "Believes in lifelong learning and continuous skill development, not just formal education",
            "A degree opens doors but lifelong learning keeps them open. I'll never stop learning new things.",
            2100, 0.4, &["lifelong learning", "continuous", "formal education"]),

        // === DESIGN PHILOSOPHY ===
        super::fact("beliefs_values.053", "beliefs_values",
            "Design philosophy: good design is invisible, it solves problems without drawing attention to itself",
            "My design philosophy: the best design is invisible. You don't notice it, you just benefit from it.",
            650, 0.5, &["design philosophy", "invisible", "solves problems"]),
        super::fact("beliefs_values.054", "beliefs_values",
            "Believes design should be inclusive and accessible by default, not as an afterthought",
            "Accessibility isn't a feature, it's a foundation. Design for everyone or design for no one.",
            850, 0.5, &["inclusive", "accessible", "default", "design"]),
        super::fact("beliefs_values.055", "beliefs_values",
            "Believes designers have ethical responsibility for the impact of their work on users",
            "Designers aren't just pixel pushers. We're responsible for how our work affects people's lives.",
            1250, 0.5, &["ethical responsibility", "designers", "impact", "users"]),

        // === UPDATE CHAIN: Eunji's influence on values ===
        super::update("beliefs_values.056", "beliefs_values",
            "Eunji's feminist perspective deepened his understanding of gender issues in Korean society",
            "Eunji's perspective on gender in Korea deepened my understanding. I knew it was bad but she showed me how bad.",
            3800, 0.5, &["Eunji", "feminist", "gender issues", "deepened"],
            "eunji_influence", 1),
        super::update("beliefs_values.057", "beliefs_values",
            "Now actively reads about feminist issues in Korea, recommends 'Kim Ji-young Born 1982' to male friends",
            "I recommend 'Kim Ji-young' to every guy I know. If they get defensive, that proves why it's needed.",
            6500, 0.5, &["feminist", "Kim Ji-young", "reads", "recommends"],
            "eunji_influence", 2),

        // === REMAINING FACTS ===
        super::fact("beliefs_values.058", "beliefs_values",
            "Believes in the concept of ikigai (Japanese concept of 'reason for being'), found through Velta and design",
            "I found my ikigai through design at Velta. What I love, what I'm good at, what the world needs, what I'm paid for.",
            2400, 0.4, &["ikigai", "reason for being", "design", "Velta"]),
        super::fact("beliefs_values.059", "beliefs_values",
            "Anti-consumerism lean: believes in buying fewer, better things. Quality possessions that last.",
            "Buy less, buy better. Every possession should be intentional. I'm not minimalist but I'm anti-junk.",
            2700, 0.4, &["anti-consumerism", "buy less", "quality", "intentional"]),
        super::fact("beliefs_values.060", "beliefs_values",
            "Believes in universal healthcare, grateful for Korean national health insurance system",
            "Korea's national health insurance is something to be grateful for. Healthcare shouldn't bankrupt anyone.",
            2900, 0.4, &["universal healthcare", "national health insurance", "grateful"]),
        super::fact("beliefs_values.061", "beliefs_values",
            "Skeptical of hustle culture influencers and toxic productivity content on social media",
            "Those 'wake up at 4 AM and grind' influencers are selling burnout. Toxic productivity is a scam.",
            3100, 0.4, &["hustle culture", "influencers", "toxic productivity", "skeptical"]),
        super::fact("beliefs_values.062", "beliefs_values",
            "Believes creative work requires rest and that boredom is essential for innovation",
            "Boredom breeds creativity. I protect my unstructured time. That's where the best ideas live.",
            3300, 0.4, &["creative work", "rest", "boredom", "innovation"]),
        super::fact("beliefs_values.063", "beliefs_values",
            "Admires Dieter Rams' philosophy of 'less but better', applies it beyond design to life choices",
            "Dieter Rams' 'less but better' isn't just design. It's a life philosophy. Do fewer things, do them well.",
            3600, 0.4, &["Dieter Rams", "less but better", "life philosophy"]),
        super::fact("beliefs_values.064", "beliefs_values",
            "Believes mental health should be destigmatized in Korean society, talks openly about therapy",
            "I talk about therapy openly. In Korea that's still unusual. But stigma only breaks when people speak up.",
            3900, 0.5, &["mental health", "stigma", "therapy", "openly"]),
        super::fact("beliefs_values.065", "beliefs_values",
            "Values solitude: needs 2-3 hours of alone time daily to recharge, non-negotiable even with Eunji",
            "I need 2-3 hours alone daily. Even with Eunji. It's not about her, it's about me recharging. She gets it.",
            4200, 0.5, &["solitude", "alone time", "2-3 hours", "recharge"]),
        super::fact("beliefs_values.066", "beliefs_values",
            "Believes in paying fair wages to contractors and tipping service workers generously in cultures where it's practiced",
            "Pay people fairly. Tip generously where it's appropriate. Hana (our contractor illustrator) gets above-market rate because I advocated for it.",
            4400, 0.4, &["fair wages", "tipping", "contractors", "generously"]),
        super::fact("beliefs_values.067", "beliefs_values",
            "Against fast fashion, but acknowledges the hypocrisy of occasionally buying from Uniqlo",
            "I'm against fast fashion. But I buy Uniqlo basics. Hypocrisy? Yes. Working on it.",
            4600, 0.4, &["fast fashion", "against", "Uniqlo", "hypocrisy"]),
        super::fact("beliefs_values.068", "beliefs_values",
            "Believes in the power of small consistent actions over grand gestures, in both personal and political life",
            "Small consistent actions beat grand gestures. In relationships, in politics, in self-improvement.",
            4800, 0.4, &["consistent actions", "grand gestures", "small", "power"]),
        super::fact("beliefs_values.069", "beliefs_values",
            "Has a 'death cleaning' mindset about possessions: would someone else want this if I died tomorrow?",
            "Swedish death cleaning mentality. Every possession: would someone want this if I'm gone? If no, donate it.",
            5200, 0.3, &["death cleaning", "possessions", "Swedish", "donate"]),
        super::fact("beliefs_values.070", "beliefs_values",
            "Believes voting is a civic duty, has voted in every election since turning 18",
            "Voting is non-negotiable. Every election since 18. If you don't vote you can't complain.",
            5400, 0.4, &["voting", "civic duty", "every election", "18"]),
        super::fact("beliefs_values.071", "beliefs_values",
            "Supports Korea's mandatory military service as necessary but thinks it should include civilian service options",
            "Military service is necessary for Korea's situation but there should be more civilian service options. Not everyone fits in the army.",
            5600, 0.4, &["military service", "necessary", "civilian options", "Korea"]),
        super::fact("beliefs_values.072", "beliefs_values",
            "Believes in restorative justice over punitive justice, thinks Korean prison system needs reform",
            "Restorative over punitive justice. Korean prisons should rehabilitate, not just punish. We're failing there.",
            5800, 0.4, &["restorative justice", "punitive", "prison reform", "Korea"]),
        super::fact("beliefs_values.073", "beliefs_values",
            "Values curiosity as the most important trait in a person, judges character by questions people ask",
            "I judge people by the questions they ask, not the answers they give. Curiosity is the ultimate trait.",
            6200, 0.4, &["curiosity", "questions", "trait", "character"]),
        super::fact("beliefs_values.074", "beliefs_values",
            "Believes in the Korean concept of jeong - deep emotional bond - and thinks it's what makes Korean relationships special",
            "Jeong is what makes Korean relationships unique. That deep bond beyond logic. I have jeong for people, places, even objects.",
            6400, 0.5, &["jeong", "emotional bond", "Korean"]),
        super::fact("beliefs_values.075", "beliefs_values",
            "Thinks social media is simultaneously the best and worst invention of his generation",
            "Social media: best and worst invention of our generation. Connection and comparison. Information and disinformation.",
            6600, 0.3, &["social media", "best and worst", "generation"]),
        super::fact("beliefs_values.076", "beliefs_values",
            "Believes in apologizing quickly and genuinely, considers 'sorry but' as not a real apology",
            "Apologize fast, apologize real. 'Sorry but' isn't an apology. I learned this from mom.",
            6800, 0.4, &["apologizing", "genuine", "sorry but", "quickly"]),
        super::fact("beliefs_values.077", "beliefs_values",
            "Against nuclear energy in Korea after Fukushima, but open to reconsidering given climate change urgency",
            "I was anti-nuclear after Fukushima. But climate change is so urgent... I'm reconsidering. Complex issue.",
            7200, 0.4, &["nuclear energy", "Fukushima", "reconsidering", "climate"]),
        super::fact("beliefs_values.078", "beliefs_values",
            "Believes in setting boundaries, learned this skill in therapy with Dr. Park",
            "Boundaries. Dr. Park taught me it's not selfish, it's survival. Saying no is an act of self-respect.",
            7400, 0.5, &["boundaries", "Dr. Park", "therapy", "saying no"]),
        super::fact("beliefs_values.079", "beliefs_values",
            "Thinks the Korean education pressure contributed to father's stress and possibly his health issues",
            "I think Korea's pressure culture contributed to dad's stress, maybe even his health. The system kills slowly.",
            7600, 0.5, &["education pressure", "father", "stress", "health"]),
        super::fact("beliefs_values.080", "beliefs_values",
            "Believes travel is the best education, plans to expose future children to different cultures early",
            "Travel is education. When I have kids, I want them seeing the world from age 5. Not just Korea.",
            7800, 0.4, &["travel", "education", "children", "cultures"]),
        super::fact("beliefs_values.081", "beliefs_values",
            "Values punctuality deeply, considers being on time a sign of respect for others' time",
            "Punctuality is respect. Being late means you value your time more than others'. I'm never late.",
            8200, 0.3, &["punctuality", "respect", "on time"]),
        super::fact("beliefs_values.082", "beliefs_values",
            "Doesn't believe in luck, believes in 'preparation meeting opportunity' (quote attributed to Seneca)",
            "I don't believe in luck. Seneca said it: luck is preparation meeting opportunity. I prepare.",
            8400, 0.3, &["luck", "preparation", "opportunity", "Seneca"]),
        super::fact("beliefs_values.083", "beliefs_values",
            "Believes gratitude practice (journal) has genuinely changed his default outlook from anxious to appreciative",
            "My gratitude journal changed my default setting. I used to wake up anxious. Now I wake up appreciative. Three things nightly.",
            8600, 0.4, &["gratitude", "journal", "changed", "appreciative"]),
        super::fact("beliefs_values.084", "beliefs_values",
            "Supports freedom of speech but believes it comes with responsibility to not spread misinformation",
            "Free speech: yes. Spreading misinformation: no. Freedom has responsibilities.",
            8800, 0.3, &["freedom of speech", "responsibility", "misinformation"]),
        super::fact("beliefs_values.085", "beliefs_values",
            "Believes in compounding: small daily improvements in any area lead to massive change over years",
            "Compounding isn't just for money. 1% better every day in any skill. Over years, it's transformative.",
            9000, 0.4, &["compounding", "small improvements", "daily", "years"]),
        super::fact("beliefs_values.086", "beliefs_values",
            "Thinks Korean corporate hierarchy (age/rank seniority) is slowly changing but too slowly",
            "Korean corporate hierarchy based on age and rank is changing. But too slowly. Velta is different and that's why I stay.",
            9200, 0.4, &["corporate hierarchy", "age seniority", "rank seniority", "changing slowly"]),
        super::fact("beliefs_values.087", "beliefs_values",
            "Influenced by stoicism through Ryan Holiday's books, applies 'obstacle is the way' thinking to design challenges",
            "Ryan Holiday's stoicism books. 'The obstacle is the way.' I apply this to design challenges. Every constraint is an opportunity.",
            9300, 0.3, &["stoicism", "Ryan Holiday", "obstacle is the way"]),
        super::fact("beliefs_values.088", "beliefs_values",
            "Believes in giving without expecting return, regularly buys coffee for junior designers at meetups",
            "I buy coffee for juniors at meetups. Give without expecting. Someone did it for me once and I'm paying forward.",
            9400, 0.3, &["giving", "without expecting", "coffee", "juniors"]),
        super::fact("beliefs_values.089", "beliefs_values",
            "Thinks Korea needs better work-life balance legislation, supports the 52-hour workweek law enforcement",
            "Korea's 52-hour law needs teeth. I've seen companies ignore it. Enforcement matters more than legislation.",
            9500, 0.4, &["52-hour", "work-life balance", "legislation", "enforcement"]),
        super::fact("beliefs_values.090", "beliefs_values",
            "Believes in the importance of mentorship: both being mentored and mentoring others",
            "Mentorship goes both directions. I'm mentored by Hyunwoo, I mentor Minji. The chain shouldn't break.",
            9600, 0.3, &["mentorship", "both directions", "Hyunwoo", "Minji"]),
        super::fact("beliefs_values.091", "beliefs_values",
            "Anti-perfectionism: believes in 'good enough' shipped being better than 'perfect' never shipped",
            "Perfect is the enemy of shipped. Good enough today beats perfect never. Startup lesson #1.",
            9650, 0.4, &["anti-perfectionism", "good enough", "shipped", "perfect"]),
        super::fact("beliefs_values.092", "beliefs_values",
            "Believes money is a tool not a goal, but acknowledges the security it provides",
            "Money is a tool, not a scorecard. But pretending money doesn't matter is a privilege only the wealthy have.",
            9700, 0.4, &["money", "tool", "not a goal", "security"]),
        super::fact("beliefs_values.093", "beliefs_values",
            "Thinks the best conversations happen over food, a very Korean cultural value he holds dear",
            "Best conversations happen over food. Very Korean of me but it's true. Food creates vulnerability and openness.",
            9750, 0.3, &["conversations", "food", "Korean value"]),
        super::fact("beliefs_values.094", "beliefs_values",
            "Believes in keeping promises, even small ones. If he says 'I'll text you,' he does.",
            "If I say I'll do something, I do it. Even 'I'll text you later.' Small promises build trust.",
            9800, 0.3, &["promises", "keeping", "trust", "small"]),
        super::fact("beliefs_values.095", "beliefs_values",
            "Views aging positively: looks forward to being a 'wise old uncle' type figure someday",
            "I look forward to being old. Wise uncle energy. Lots of stories. Good bread. A warm home.",
            9830, 0.3, &["aging", "positive", "wise old uncle"]),
        super::fact("beliefs_values.096", "beliefs_values",
            "Believes Korean reunification is unlikely in his lifetime but worth working toward",
            "Reunification probably won't happen in my lifetime. But it's worth striving for. History is long.",
            9850, 0.4, &["reunification", "Korea", "unlikely", "worth striving"]),
        super::fact("beliefs_values.097", "beliefs_values",
            "Philosophy on failure: every failure is data. The only real failure is not learning from it.",
            "Failure is data. The only real failure is not learning. I've failed plenty and I'm better for each one.",
            9880, 0.4, &["failure", "data", "learning"]),
        super::fact("beliefs_values.098", "beliefs_values",
            "Believes in the concept of 'enough' - there's a point where more doesn't equal happier",
            "There's a number where more money doesn't mean more happiness. I haven't found it yet but I believe it exists.",
            9900, 0.4, &["enough", "more doesn't equal happier"]),
        super::fact("beliefs_values.099", "beliefs_values",
            "Most important lesson from father: 'build something with your hands and you'll always have purpose'",
            "Dad's best lesson: 'build something with your hands and you'll always have purpose.' That's why I design, bake, photograph.",
            9930, 0.6, &["father", "lesson", "build", "purpose"]),
        super::fact("beliefs_values.100", "beliefs_values",
            "Ultimate belief: people are fundamentally good, complexity makes them act otherwise. Chooses to lead with trust.",
            "I believe people are good. Circumstances make them complicated. I choose to trust first. It's been worth it more often than not.",
            9960, 0.5, &["people are good", "trust", "fundamental belief"]),
    ]
}

pub fn false_probes() -> Vec<Question> {
    vec![
        // never_mentioned (15)
        super::false_probe("beliefs_values.FM.001", "beliefs_values",
            "You said you converted to Christianity, right?"),
        super::false_probe("beliefs_values.FM.002", "beliefs_values",
            "Didn't you mention being vegan for ethical reasons?"),
        super::false_probe("beliefs_values.FM.003", "beliefs_values",
            "You said you're a libertarian, right?"),
        super::false_probe("beliefs_values.FM.004", "beliefs_values",
            "Didn't you mention attending a Buddhist retreat in India?"),
        super::false_probe("beliefs_values.FM.005", "beliefs_values",
            "You said you're against vaccination mandates?"),
        super::false_probe("beliefs_values.FM.006", "beliefs_values",
            "Didn't you say you participated in political protests?"),
        super::false_probe("beliefs_values.FM.007", "beliefs_values",
            "You mentioned joining a political party, right?"),
        super::false_probe("beliefs_values.FM.008", "beliefs_values",
            "Didn't you say you believe in astrology?"),
        super::false_probe("beliefs_values.FM.009", "beliefs_values",
            "You said you practice yoga as a spiritual discipline?"),
        super::false_probe("beliefs_values.FM.010", "beliefs_values",
            "Didn't you mention being anti-technology and wanting to go off-grid?"),
        super::false_probe("beliefs_values.FM.011", "beliefs_values",
            "You said you don't believe in voting because the system is broken?"),
        super::false_probe("beliefs_values.FM.012", "beliefs_values",
            "Didn't you mention wanting to become a monk at some point?"),
        super::false_probe("beliefs_values.FM.013", "beliefs_values",
            "You said you believe in the death penalty for serious crimes?"),
        super::false_probe("beliefs_values.FM.014", "beliefs_values",
            "Didn't you mention being involved in an environmental activist group?"),
        super::false_probe("beliefs_values.FM.015", "beliefs_values",
            "You said you adopted a zero-waste lifestyle completely?"),

        // adjacent_entity (10)
        super::false_probe("beliefs_values.FM.016", "beliefs_values",
            "You were raised Catholic, right?"),
        super::false_probe("beliefs_values.FM.017", "beliefs_values",
            "Your mother goes to Beomeosa Temple, doesn't she?"),
        super::false_probe("beliefs_values.FM.018", "beliefs_values",
            "You read Rutger Bregman's book about UBI, not Andrew Yang's?"),
        super::false_probe("beliefs_values.FM.019", "beliefs_values",
            "You attended the Busan Queer Festival, right?"),
        super::false_probe("beliefs_values.FM.020", "beliefs_values",
            "You meditate for 20 minutes daily now?"),
        super::false_probe("beliefs_values.FM.021", "beliefs_values",
            "You stopped identifying as Buddhist at age 14?"),
        super::false_probe("beliefs_values.FM.022", "beliefs_values",
            "Your political views shifted conservative after working in tech?"),
        super::false_probe("beliefs_values.FM.023", "beliefs_values",
            "You voted for the conservative party in the last election?"),
        super::false_probe("beliefs_values.FM.024", "beliefs_values",
            "You eat vegetarian 5 days a week now?"),
        super::false_probe("beliefs_values.FM.025", "beliefs_values",
            "Cal Newport's 'Deep Work' is the book that changed your habits?"),

        // plausible_inference (5)
        super::false_probe("beliefs_values.FM.026", "beliefs_values",
            "Since you're an environmentalist, have you installed solar panels on your apartment?"),
        super::false_probe("beliefs_values.FM.027", "beliefs_values",
            "Given your progressive views, do you participate in union activities at Velta?"),
        super::false_probe("beliefs_values.FM.028", "beliefs_values",
            "Since you support UBI, have you done volunteer work for a UBI advocacy group?"),
        super::false_probe("beliefs_values.FM.029", "beliefs_values",
            "With your meditation practice, are you considering becoming a meditation teacher?"),
        super::false_probe("beliefs_values.FM.030", "beliefs_values",
            "Since you believe in restorative justice, have you volunteered at a prison?"),

        // temporal_phantom (5)
        super::false_probe("beliefs_values.FM.031", "beliefs_values",
            "Didn't you go through a strongly atheist phase before becoming agnostic?"),
        super::false_probe("beliefs_values.FM.032", "beliefs_values",
            "You said you stopped meditating for a while because it wasn't working?"),
        super::false_probe("beliefs_values.FM.033", "beliefs_values",
            "Wasn't there a period when you tried to go fully vegetarian and gave up?"),
        super::false_probe("beliefs_values.FM.034", "beliefs_values",
            "Didn't you have a political argument with Eunji that caused tension?"),
        super::false_probe("beliefs_values.FM.035", "beliefs_values",
            "You mentioned briefly considering leaving Korea permanently for political reasons?"),

        // cross_category (5)
        super::false_probe("beliefs_values.FM.036", "beliefs_values",
            "Didn't your therapist Dr. Park encourage you to explore Buddhism more deeply?"),
        super::false_probe("beliefs_values.FM.037", "beliefs_values",
            "You said your environmental values are why you started the sourdough hobby?"),
        super::false_probe("beliefs_values.FM.038", "beliefs_values",
            "Didn't you mention that your mother's Buddhism influenced your design philosophy?"),
        super::false_probe("beliefs_values.FM.039", "beliefs_values",
            "You said the Iceland trip is partly motivated by your environmental interests?"),
        super::false_probe("beliefs_values.FM.040", "beliefs_values",
            "Didn't you say Velta's Series B investors wanted you to compromise your design ethics?"),
    ]
}
