use crate::types::{Fact, Question};

pub fn facts() -> Vec<Fact> {
    vec![
        // === BASIC ROUTINES (T1-T2500, early mentions) ===
        super::fact("daily_life.001", "daily_life",
            "Wakes up at 7:15 AM on weekdays, uses a Philips sunrise alarm clock bought in 2024",
            "Ugh, my alarm went off at 7:15 again... at least that Philips sunrise clock makes it bearable. Got it last year.",
            120, 0.8, &["wake", "alarm", "7:15", "Philips", "sunrise"]),
        super::fact("daily_life.002", "daily_life",
            "Morning routine: shower first, then coffee. Never eats breakfast before showering.",
            "I literally cannot function until I've showered. Coffee comes right after, but food? Not until I'm clean.",
            180, 0.5, &["shower", "morning", "coffee", "routine"]),
        super::fact("daily_life.003", "daily_life",
            "Drinks pour-over coffee using a Hario V60, medium roast beans from Fritz Coffee in Mapo-gu",
            "My morning V60 pour-over is sacred. I only buy beans from Fritz in Mapo, their medium roast is perfect.",
            250, 0.7, &["coffee", "Hario", "V60", "Fritz", "pour-over"]),
        super::fact("daily_life.004", "daily_life",
            "Lives in a 23-pyeong apartment in Yeonnam-dong, moved there in March 2025",
            "I moved to this place in Yeonnam-dong last March. 23 pyeong, which is honestly perfect for one person.",
            90, 0.9, &["apartment", "Yeonnam-dong", "23 pyeong", "March 2025"]),
        super::fact("daily_life.005", "daily_life",
            "Commute is 35 minutes by subway Line 2 from Hongik University station to Gangnam station",
            "The commute is about 35 minutes, Line 2 straight from Hongik University to Gangnam. Not bad honestly.",
            310, 0.7, &["commute", "subway", "Line 2", "Hongik", "Gangnam"]),
        super::fact("daily_life.006", "daily_life",
            "Packs lunch 3 days a week, usually rice with some banchan. Eats out on Tuesdays and Thursdays.",
            "I try to bring lunch Monday, Wednesday, Friday. Tuesdays and Thursdays I eat out with the team.",
            420, 0.5, &["lunch", "banchan", "pack lunch", "eat out"]),
        super::fact("daily_life.007", "daily_life",
            "Uses a Dyson V15 cordless vacuum, cleans apartment every Saturday morning",
            "Saturday morning is always cleaning time. My Dyson V15 is the best purchase I've made this year honestly.",
            500, 0.4, &["vacuum", "Dyson", "V15", "Saturday", "cleaning"]),
        super::fact("daily_life.008", "daily_life",
            "Goes to bed between 11:30 PM and midnight, reads on Kindle Paperwhite for 20 minutes before sleep",
            "I'm usually in bed by 11:30, read my Kindle for about 20 minutes and lights out by midnight.",
            620, 0.6, &["sleep", "bed", "Kindle", "Paperwhite", "midnight"]),
        super::fact("daily_life.009", "daily_life",
            "Grocery shops at Emart Every Day in Yeonnam-dong every Sunday, spends about 60,000 won per week",
            "I always hit up the Emart Every Day near my place on Sundays. Usually about 60K won for the week.",
            780, 0.5, &["grocery", "Emart", "Sunday", "60000 won"]),
        super::fact("daily_life.010", "daily_life",
            "Has a monstera plant named Gerald on the living room windowsill, bought at Kukje Flower Market",
            "Gerald the monstera is thriving! Got him at Kukje Flower Market a few months ago.",
            850, 0.4, &["monstera", "Gerald", "plant", "Kukje Flower Market"]),

        // === APARTMENT DETAILS ===
        super::fact("daily_life.011", "daily_life",
            "Rent is 900,000 won/month with 30 million won jeonse deposit",
            "My rent is 900K a month with a 30 million deposit. For Yeonnam-dong that's actually decent.",
            150, 0.8, &["rent", "900K", "jeonse", "30 million", "deposit"]),
        super::fact("daily_life.012", "daily_life",
            "Apartment has ondol floor heating, keeps it at 22 degrees in winter",
            "I love ondol heating. Keep it at 22 degrees, my electricity bill is actually reasonable.",
            1100, 0.4, &["ondol", "heating", "22 degrees", "floor"]),
        super::fact("daily_life.013", "daily_life",
            "Kitchen has an LG InstaView refrigerator, a hand-me-down from parents when they upgraded",
            "My parents gave me their old LG InstaView fridge when they upgraded. It's honestly way too fancy for me.",
            1250, 0.3, &["refrigerator", "LG", "InstaView", "parents"]),
        super::fact("daily_life.014", "daily_life",
            "Has a small balcony converted into a laundry/drying area with an LG ThinQ washer",
            "My balcony is basically just the washer and drying rack. LG ThinQ, works great with the app.",
            1400, 0.3, &["balcony", "laundry", "LG", "ThinQ", "washer"]),
        super::fact("daily_life.015", "daily_life",
            "Living room has a 55-inch Samsung Frame TV mounted on the wall, bought during Chuseok sale 2025",
            "Best Chuseok sale purchase: my 55-inch Samsung Frame TV. It looks like art when it's off.",
            1600, 0.5, &["TV", "Samsung", "Frame", "55-inch", "Chuseok"]),

        // === MEALS AND COOKING ===
        super::fact("daily_life.016", "daily_life",
            "Signature dish is kimchi jjigae, uses mother's recipe with extra gochugaru",
            "My kimchi jjigae is honestly amazing. Mom's recipe but I add extra gochugaru.",
            400, 0.5, &["kimchi jjigae", "cooking", "mother recipe", "gochugaru"]),
        super::fact("daily_life.017", "daily_life",
            "Orders delivery on Friday nights, alternates between Baedal Minjok and Coupang Eats",
            "Friday is delivery night! I switch between Baedal Minjok and Coupang Eats depending on deals.",
            550, 0.4, &["delivery", "Friday", "Baedal Minjok", "Coupang Eats"]),
        super::fact("daily_life.018", "daily_life",
            "Favorite lunch spot near office is a Vietnamese pho restaurant called Pho Saigon on Gangnam-daero",
            "There's this amazing pho place near the office, Pho Saigon on Gangnam-daero. I go every Thursday.",
            700, 0.5, &["pho", "Pho Saigon", "Gangnam-daero", "Vietnamese", "lunch"]),
        super::fact("daily_life.019", "daily_life",
            "Allergic to shellfish, carries an EpiPen. Had a scare at a company dinner in January 2026.",
            "I'm allergic to shellfish, it's serious enough that I carry an EpiPen. Had a close call at a work dinner in January.",
            340, 0.9, &["shellfish", "allergy", "EpiPen", "company dinner"]),
        super::fact("daily_life.020", "daily_life",
            "Drinks 2 liters of water daily, uses a mint green Hydroflask 32oz bottle",
            "I try to drink 2 liters a day. My mint green Hydroflask goes everywhere with me.",
            900, 0.3, &["water", "Hydroflask", "2 liters", "mint green"]),

        // === COMMUTE AND TRANSPORT ===
        super::fact("daily_life.021", "daily_life",
            "Does not own a car, uses T-money card for subway and bus. Monthly transport cost about 65,000 won.",
            "No car for me. T-money card, subway and bus. Costs me about 65K a month in transport.",
            480, 0.5, &["T-money", "no car", "transport", "65000 won"]),
        super::fact("daily_life.022", "daily_life",
            "Takes the 7:45 AM subway to avoid rush hour, arrives at office by 8:20 AM",
            "If I catch the 7:45 train I beat the worst of rush hour. Usually at my desk by 8:20.",
            560, 0.4, &["7:45", "subway", "rush hour", "8:20"]),
        super::fact("daily_life.023", "daily_life",
            "Sometimes bikes to work on nice days using Seoul Bike (Ttareungyi), takes about 50 minutes",
            "When the weather is nice I take Ttareungyi to work. About 50 minutes but it's a great ride along the stream.",
            1800, 0.4, &["Ttareungyi", "Seoul Bike", "cycling", "50 minutes"]),

        // === EVENING ROUTINE ===
        super::fact("daily_life.024", "daily_life",
            "Gets home around 7 PM on most days, 9 PM during crunch periods at work",
            "Usually home by 7, but during crunch it's more like 9. Those weeks are brutal.",
            650, 0.5, &["home", "7 PM", "9 PM", "crunch"]),
        super::fact("daily_life.025", "daily_life",
            "Cooks dinner 4 nights a week, meal preps on Sundays for Monday and Tuesday",
            "I meal prep on Sundays, covers Monday and Tuesday. Cook fresh the other nights.",
            800, 0.4, &["dinner", "meal prep", "Sunday", "cook"]),
        super::fact("daily_life.026", "daily_life",
            "Takes a 15-minute evening walk around Yeonnam-dong park after dinner when weather permits",
            "I've started doing a little evening walk around Yeonnam-dong park after dinner. Helps me decompress.",
            2100, 0.4, &["evening walk", "Yeonnam-dong park", "after dinner"]),
        super::fact("daily_life.027", "daily_life",
            "Showers twice a day in summer (morning and after evening walk), once in winter",
            "In summer I shower twice, morning and evening. Winter just the morning one is fine.",
            2400, 0.3, &["shower", "summer", "twice", "winter"]),

        // === WEEKEND ROUTINES ===
        super::fact("daily_life.028", "daily_life",
            "Sleeps in until 9:30 AM on Saturdays, 10 AM on Sundays",
            "Weekends I let myself sleep in. 9:30 Saturday, 10 on Sunday. My body just knows.",
            1000, 0.4, &["weekend", "sleep in", "9:30", "Saturday", "Sunday"]),
        super::fact("daily_life.029", "daily_life",
            "Saturday afternoon routine: cafe hopping in Yeonnam-dong or Hapjeong, usually Anthracite or Cafe Onion",
            "Saturday afternoons I'm always at a cafe. Anthracite or Cafe Onion are my go-tos around here.",
            1300, 0.5, &["cafe", "Saturday", "Anthracite", "Cafe Onion", "Hapjeong"]),
        super::fact("daily_life.030", "daily_life",
            "Does laundry every Wednesday evening and Sunday morning",
            "Laundry days are Wednesday evenings and Sunday mornings. Like clockwork.",
            1500, 0.3, &["laundry", "Wednesday", "Sunday", "routine"]),

        // === TECH AND GADGETS ===
        super::fact("daily_life.031", "daily_life",
            "Uses iPhone 16 Pro in Desert Titanium, switched from Samsung Galaxy S24 in November 2025",
            "I finally switched to iPhone last November. iPhone 16 Pro, Desert Titanium. The camera alone was worth it.",
            380, 0.6, &["iPhone", "16 Pro", "Desert Titanium", "Samsung", "switched"]),
        super::fact("daily_life.032", "daily_life",
            "MacBook Air M3 15-inch for personal use, company provides MacBook Pro M3 for work",
            "I have two MacBooks somehow. Personal M3 Air 15-inch, work gives me an M3 Pro.",
            950, 0.5, &["MacBook", "Air", "M3", "15-inch", "Pro"]),
        super::fact("daily_life.033", "daily_life",
            "AirPods Pro 2 for commute, Sony WH-1000XM5 headphones for home/office",
            "AirPods Pro for the subway, Sony XM5s for when I need to focus at home or the office.",
            1050, 0.4, &["AirPods", "Pro", "Sony", "XM5", "headphones"]),
        super::fact("daily_life.034", "daily_life",
            "Smart home setup: Philips Hue lights, Naver Clova speaker, SmartThings hub",
            "My smart home is mostly Philips Hue lights controlled through SmartThings. Naver Clova for voice stuff.",
            1700, 0.4, &["Philips Hue", "smart home", "Naver Clova", "SmartThings"]),
        super::fact("daily_life.035", "daily_life",
            "Nintendo Switch OLED in the living room, plays mostly on weekends",
            "My Switch OLED is really just a weekend thing. It lives in the living room dock.",
            2000, 0.3, &["Nintendo Switch", "OLED", "weekend", "gaming"]),

        // === UPDATE CHAIN 1: Wake time changes ===
        super::update("daily_life.036", "daily_life",
            "Started waking up at 6:30 AM to fit in a morning run before work",
            "I've been pushing my alarm to 6:30 to get a morning run in. It's been two weeks and I'm surviving.",
            3200, 0.7, &["wake", "6:30", "morning run", "alarm"],
            "wake_time", 1),
        super::update("daily_life.037", "daily_life",
            "Gave up 6:30 AM wake-up after 3 weeks, back to 7:15 AM. Morning runs moved to evening.",
            "Yeah the 6:30 thing lasted exactly three weeks. Back to 7:15, I'll run in the evenings instead.",
            4100, 0.6, &["wake", "7:15", "gave up", "morning run"],
            "wake_time", 2),

        // === UPDATE CHAIN 2: Coffee preference changes ===
        super::update("daily_life.038", "daily_life",
            "Switched from Fritz Coffee beans to Namusairo roastery in Yeonnam-dong, darker roast",
            "I've been trying Namusairo's dark roast lately. It's right in Yeonnam-dong and their beans are incredible.",
            3800, 0.5, &["coffee", "Namusairo", "dark roast", "beans"],
            "coffee_beans", 1),
        super::update("daily_life.039", "daily_life",
            "Started buying beans from both Fritz and Namusairo, alternating weekly",
            "I can't choose between Fritz and Namusairo so I just alternate weeks now. Best of both worlds.",
            5500, 0.4, &["coffee", "Fritz", "Namusairo", "alternate"],
            "coffee_beans", 2),

        // === UPDATE CHAIN 3: Lunch spot changes ===
        super::update("daily_life.040", "daily_life",
            "Pho Saigon in Gangnam closed down in February 2026, now goes to a kalguksu place called Myeongdong Kalguksu",
            "Pho Saigon closed! I'm devastated. Been going to Myeongdong Kalguksu instead, it's good but not the same.",
            4500, 0.6, &["Pho Saigon", "closed", "Myeongdong Kalguksu", "lunch"],
            "lunch_spot", 1),
        super::update("daily_life.041", "daily_life",
            "New Vietnamese place opened near office called Hanoi Corner, replaced Pho Saigon as Thursday spot",
            "A new Vietnamese place opened! Hanoi Corner. Their bun cha is amazing. Thursday spot is back.",
            6200, 0.5, &["Hanoi Corner", "Vietnamese", "bun cha", "Thursday"],
            "lunch_spot", 2),

        // === UPDATE CHAIN 4: Apartment changes ===
        super::update("daily_life.042", "daily_life",
            "Landlord raised rent from 900K to 950K won starting April 2026",
            "My landlord just told me rent's going up to 950K starting April. Annoying but still okay for the area.",
            5000, 0.7, &["rent", "950K", "increase", "landlord", "April"],
            "rent_amount", 1),

        // === UPDATE CHAIN 5: Phone ===
        super::update("daily_life.043", "daily_life",
            "iPhone 16 Pro screen cracked after dropping it at Gangnam station, using a temporary screen protector",
            "I dropped my phone at Gangnam station and cracked the screen. Got a temp protector but I need to get it fixed.",
            4800, 0.5, &["iPhone", "cracked", "screen", "Gangnam station"],
            "phone_status", 1),
        super::update("daily_life.044", "daily_life",
            "Got iPhone screen repaired at Apple Garosugil for 280,000 won",
            "Finally got the screen fixed at Apple Garosugil. 280K won, ouch. At least it's perfect again.",
            5200, 0.5, &["iPhone", "repair", "Apple Garosugil", "280K"],
            "phone_status", 2),

        // === MISCELLANEOUS HABITS ===
        super::fact("daily_life.045", "daily_life",
            "Uses Notion for personal task management, has templates for weekly reviews every Sunday evening",
            "Sunday evenings I do my weekly review in Notion. I have a whole template system set up.",
            1150, 0.4, &["Notion", "weekly review", "Sunday", "task management"]),
        super::fact("daily_life.046", "daily_life",
            "Morning skincare routine: Cosrx cleanser, Klairs toner, Innisfree moisturizer, Biore sunscreen",
            "My skincare is pretty simple. Cosrx cleanser, Klairs toner, Innisfree moisturizer, Biore sunscreen. Done.",
            1350, 0.3, &["skincare", "Cosrx", "Klairs", "Innisfree", "Biore"]),
        super::fact("daily_life.047", "daily_life",
            "Takes vitamin D and omega-3 supplements every morning with coffee",
            "I take vitamin D and omega-3 with my morning coffee. Doctor's orders after my checkup last year.",
            1550, 0.4, &["vitamins", "vitamin D", "omega-3", "supplements"]),
        super::fact("daily_life.048", "daily_life",
            "Has a shoe rack with 12 pairs, favorite daily shoes are New Balance 990v6 in grey",
            "My daily beaters are New Balance 990v6 in grey. I have like 12 pairs total but those are the ones.",
            1700, 0.3, &["shoes", "New Balance", "990v6", "grey"]),
        super::fact("daily_life.049", "daily_life",
            "Charges all devices on a Belkin 3-in-1 MagSafe charger on the nightstand",
            "Everything charges on my Belkin 3-in-1 MagSafe at night. Phone, AirPods, Apple Watch.",
            1900, 0.3, &["charger", "Belkin", "MagSafe", "nightstand"]),
        super::fact("daily_life.050", "daily_life",
            "Has an Apple Watch Ultra 2 for fitness tracking, bought with first big bonus from Velta",
            "Bought the Apple Watch Ultra 2 with my first real bonus from Velta. Use it mainly for workouts.",
            600, 0.5, &["Apple Watch", "Ultra 2", "fitness", "Velta bonus"]),

        // === MID-RANGE TURNS (T2500-T5000) ===
        super::fact("daily_life.051", "daily_life",
            "Started using a standing desk converter (FlexiSpot) at home in February 2026",
            "Got a FlexiSpot standing desk converter for my home desk. My back thanks me.",
            2700, 0.4, &["standing desk", "FlexiSpot", "home office", "back"]),
        super::fact("daily_life.052", "daily_life",
            "Keeps apartment at exactly 24 degrees in summer using a Samsung wind-free AC unit",
            "My Samsung wind-free AC is set to exactly 24 in summer. Any lower and I freeze.",
            2900, 0.3, &["AC", "Samsung", "wind-free", "24 degrees", "summer"]),
        super::fact("daily_life.053", "daily_life",
            "Has a morning playlist on Spotify called 'Wake Up Chill', mostly lo-fi and acoustic",
            "I have this Spotify playlist called 'Wake Up Chill' that I play every morning. Lo-fi and acoustic stuff.",
            3100, 0.3, &["Spotify", "playlist", "Wake Up Chill", "lo-fi", "morning"]),
        super::fact("daily_life.054", "daily_life",
            "Neighbor in 302 is a retired teacher named Mrs. Kim who sometimes brings homemade tteok",
            "Mrs. Kim in 302 brought over tteok again. She's a retired teacher, sweetest person ever.",
            3300, 0.4, &["neighbor", "Mrs. Kim", "302", "tteok", "retired teacher"]),
        super::fact("daily_life.055", "daily_life",
            "Building has a rooftop access, goes up there to stargaze on clear nights with a cheap telescope",
            "Our building has rooftop access and I bought this cheap telescope. On clear nights it's actually magical.",
            3500, 0.4, &["rooftop", "telescope", "stargaze", "building"]),
        super::fact("daily_life.056", "daily_life",
            "Uses a Brita water filter pitcher, replaces filter every 2 months",
            "I use a Brita for all my drinking water. Replace the filter every two months religiously.",
            3600, 0.3, &["Brita", "water filter", "pitcher"]),
        super::fact("daily_life.057", "daily_life",
            "Has a junk drawer in the kitchen with dead batteries, old cables, takeout menus, and a Swiss army knife",
            "Everyone has a junk drawer right? Mine has dead batteries, old cables, and a Swiss army knife I never use.",
            3800, 0.3, &["junk drawer", "kitchen", "Swiss army knife"]),
        super::fact("daily_life.058", "daily_life",
            "Parking space in building basement is rented out since no car, earns 80,000 won/month from it",
            "I rent out my parking spot in the basement since I don't have a car. Easy 80K a month.",
            2800, 0.5, &["parking", "rent out", "80K", "basement"]),
        super::fact("daily_life.059", "daily_life",
            "Wednesday nights are 'no screen' nights, reads physical books or plays vinyl records",
            "Wednesdays I try to do no screens after 8 PM. Just books and vinyl. It's my reset night.",
            3000, 0.5, &["no screen", "Wednesday", "books", "vinyl", "digital detox"]),
        super::fact("daily_life.060", "daily_life",
            "Building elevator was broken for 3 days in January 2026, had to walk up to 5th floor",
            "The elevator broke for three days in January. Five flights of stairs with groceries is NOT fun.",
            4200, 0.3, &["elevator", "broken", "5th floor", "January", "stairs"]),

        // === LATER TURNS (T5000-T7500) ===
        super::fact("daily_life.061", "daily_life",
            "Started a small herb garden on the balcony: basil, perilla, and chives",
            "I started growing herbs on my balcony! Basil, perilla, and chives. The perilla is going crazy.",
            5300, 0.4, &["herb garden", "balcony", "basil", "perilla", "chives"]),
        super::fact("daily_life.062", "daily_life",
            "Installed a bidet toilet seat (Coway) after trying one at Eunji's parents' house",
            "Got a Coway bidet after using the one at Eunji's parents' place. Life changing, not even kidding.",
            5500, 0.3, &["bidet", "Coway", "toilet", "Eunji parents"]),
        super::fact("daily_life.063", "daily_life",
            "Electricity bill averages 45,000 won in summer, 35,000 won in winter",
            "My electricity is about 45K in summer with the AC, drops to 35K in winter. Ondol is gas-heated.",
            5700, 0.3, &["electricity", "bill", "45K", "35K", "summer", "winter"]),
        super::fact("daily_life.064", "daily_life",
            "Internet is KT GiGA 1Gbps, pays 33,000 won/month on a 3-year contract",
            "KT GiGA internet, 1 gig speed, 33K a month. Locked into a 3-year contract but the speed is worth it.",
            5800, 0.4, &["internet", "KT", "GiGA", "1Gbps", "33K"]),
        super::fact("daily_life.065", "daily_life",
            "Has a designated 'charging corner' with USB hub, cable organizer, and surge protector",
            "I set up a proper charging corner with a USB hub and cable organizer. No more cable chaos.",
            5900, 0.3, &["charging", "USB hub", "cable organizer", "surge protector"]),
        super::fact("daily_life.066", "daily_life",
            "Bathroom has a small waterproof Bluetooth speaker (JBL Go 3) for shower music",
            "I have a little JBL Go 3 in the shower. Waterproof, perfect for my morning playlist.",
            6100, 0.3, &["JBL", "Go 3", "shower", "speaker", "Bluetooth"]),
        super::fact("daily_life.067", "daily_life",
            "Bedside table has: Kindle, lip balm, eye mask, earplugs, phone charger, glass of water",
            "My bedside table is very predictable: Kindle, lip balm, eye mask, earplugs, charger, water glass.",
            6300, 0.3, &["bedside", "Kindle", "eye mask", "earplugs"]),
        super::fact("daily_life.068", "daily_life",
            "Has exactly 3 sets of bedsheets, rotates them every Sunday when doing laundry",
            "I own three sets of sheets and rotate every Sunday. Color-coded: grey, white, and navy.",
            6500, 0.3, &["bedsheets", "three sets", "Sunday", "grey", "white", "navy"]),
        super::fact("daily_life.069", "daily_life",
            "Front door uses a Samsung digital lock with fingerprint, PIN is birthday backwards",
            "My Samsung digital lock has fingerprint but I still use the PIN sometimes. It's my birthday backwards.",
            6700, 0.4, &["door lock", "Samsung", "digital", "fingerprint", "PIN"]),
        super::fact("daily_life.070", "daily_life",
            "Mail slot gets stuffed with chicken delivery flyers, recycles them every few days",
            "My mail slot is 90% chicken delivery flyers. I recycle them every few days, it's endless.",
            6800, 0.3, &["mail", "flyers", "chicken delivery", "recycle"]),

        // === UPDATE CHAIN 6: Evening routine changes ===
        super::update("daily_life.071", "daily_life",
            "Started doing 10 minutes of meditation before bed using Headspace app",
            "I downloaded Headspace and started meditating 10 minutes before bed. It actually helps me fall asleep faster.",
            5100, 0.5, &["meditation", "Headspace", "bedtime", "10 minutes"],
            "evening_routine", 1),
        super::update("daily_life.072", "daily_life",
            "Switched from Headspace to Calm app because preferred the sleep stories narrated by Korean voice actors",
            "I moved from Headspace to Calm. Their Korean sleep stories are so much better.",
            7200, 0.4, &["Calm", "Headspace", "sleep stories", "Korean"],
            "evening_routine", 2),

        // === UPDATE CHAIN 7: Cleaning routine ===
        super::update("daily_life.073", "daily_life",
            "Hired a cleaning service (Miso) biweekly after work got too busy during Series B prep",
            "I started using Miso cleaning service every two weeks. With the Series B crunch I just can't keep up.",
            6000, 0.5, &["Miso", "cleaning service", "biweekly", "Series B"],
            "cleaning_routine", 1),
        super::update("daily_life.074", "daily_life",
            "Cancelled Miso and went back to cleaning myself after Series B calmed down, saves 120K/month",
            "Cancelled the cleaning service now that things calmed down. Saving 120K a month feels good.",
            8500, 0.4, &["Miso", "cancelled", "cleaning", "120K", "saving"],
            "cleaning_routine", 2),

        // === LATE TURNS (T7500-T10000) ===
        super::fact("daily_life.075", "daily_life",
            "Discovered a great jjimjilbang called Dragon Hill Spa in Yongsan, goes monthly with Jihye",
            "Jihye and I found Dragon Hill Spa in Yongsan. We go once a month now, it's our thing.",
            7500, 0.4, &["jjimjilbang", "Dragon Hill Spa", "Yongsan", "Jihye", "monthly"]),
        super::fact("daily_life.076", "daily_life",
            "Wears glasses at home (Oliver Peoples frames, -2.5 prescription) but contacts outside",
            "I wear contacts outside but glasses at home. Oliver Peoples frames, my prescription is -2.5.",
            7700, 0.3, &["glasses", "Oliver Peoples", "contacts", "-2.5", "prescription"]),
        super::fact("daily_life.077", "daily_life",
            "Has a small home office setup in the second bedroom: IKEA Bekant desk, Herman Miller Aeron chair",
            "My home office is the second bedroom. IKEA Bekant desk and I splurged on a Herman Miller Aeron.",
            7800, 0.4, &["home office", "IKEA", "Bekant", "Herman Miller", "Aeron"]),
        super::fact("daily_life.078", "daily_life",
            "Keeps a gratitude journal, writes 3 things every night before bed in a Moleskine notebook",
            "I write 3 things I'm grateful for every night in my Moleskine. Sounds cheesy but it works.",
            7900, 0.4, &["gratitude journal", "Moleskine", "3 things", "nightly"]),
        super::fact("daily_life.079", "daily_life",
            "Morning commute podcast rotation: Tech & the City (Tue), Bookworm Seoul (Thu), rest is music",
            "Tuesdays I listen to Tech & the City on the subway, Thursdays it's Bookworm Seoul. Other days just music.",
            8000, 0.4, &["podcast", "commute", "Tech & the City", "Bookworm Seoul"]),
        super::fact("daily_life.080", "daily_life",
            "Has a 'no shoes indoors' rule, keeps indoor slippers from MUJI at the entrance",
            "Absolutely no shoes inside. I have MUJI slippers right at the entrance, it's non-negotiable.",
            8200, 0.3, &["no shoes", "indoors", "slippers", "MUJI"]),
        super::fact("daily_life.081", "daily_life",
            "Apartment hallway light is motion-activated, installed it personally with landlord's permission",
            "I installed a motion-activated light in my entrance hallway. Landlord was cool with it.",
            8400, 0.3, &["motion light", "hallway", "installed", "landlord"]),
        super::fact("daily_life.082", "daily_life",
            "Uses Coupang Rocket Delivery for most household items, has Rocket WOW membership at 4,990 won/month",
            "Coupang Rocket WOW is the best 4,990 won I spend monthly. Everything arrives next day.",
            8600, 0.4, &["Coupang", "Rocket", "WOW", "4990 won", "delivery"]),
        super::fact("daily_life.083", "daily_life",
            "Keeps emergency kit under bed: flashlight, first aid kit, water bottles, instant noodles",
            "I have an emergency kit under my bed. Flashlight, first aid, water, and instant noodles. Just in case.",
            8700, 0.3, &["emergency kit", "under bed", "flashlight", "first aid"]),
        super::fact("daily_life.084", "daily_life",
            "Building management fee (gwanlibi) is 150,000 won/month, includes water and common area electricity",
            "Gwanlibi is 150K, covers water and common area electricity. Not bad for Yeonnam-dong.",
            8800, 0.4, &["gwanlibi", "150K", "management fee", "water"]),
        super::fact("daily_life.085", "daily_life",
            "Has a key hook by the door shaped like a cat, Eunji gave it as a housewarming gift",
            "Eunji gave me this cat-shaped key hook for my housewarming. It's actually really useful.",
            8900, 0.3, &["key hook", "cat shaped", "Eunji", "housewarming"]),

        // === UPDATE CHAIN 8: Grocery shopping ===
        super::update("daily_life.086", "daily_life",
            "Started ordering groceries online through Market Kurly instead of going to Emart",
            "I've been using Market Kurly for groceries lately. Arrives by morning, no more Sunday Emart trips.",
            7000, 0.5, &["Market Kurly", "groceries", "online", "delivery"],
            "grocery_shopping", 1),
        super::update("daily_life.087", "daily_life",
            "Went back to Emart Every Day for groceries because Market Kurly produce quality was inconsistent",
            "Market Kurly's produce was hit or miss so I'm back at Emart. At least I can pick my own avocados.",
            9000, 0.4, &["Emart", "groceries", "Market Kurly", "produce quality"],
            "grocery_shopping", 2),

        // === UPDATE CHAIN 9: Sleep schedule ===
        super::update("daily_life.088", "daily_life",
            "Started going to bed at 11 PM instead of 11:30 PM after reading about sleep hygiene",
            "I've been trying to get to bed by 11 instead of 11:30. Read an article about sleep hygiene that scared me.",
            7400, 0.5, &["sleep", "11 PM", "sleep hygiene", "earlier"],
            "sleep_schedule", 1),
        super::update("daily_life.089", "daily_life",
            "Sleep schedule slipped back to midnight during a stressful project, averaging 6 hours a night",
            "My sleep schedule is wrecked again. Not getting to bed until midnight, maybe 6 hours total.",
            9200, 0.5, &["sleep", "midnight", "6 hours", "stressed"],
            "sleep_schedule", 2),
        super::update("daily_life.090", "daily_life",
            "Recovered sleep schedule to 11:15 PM bedtime after project ended, feels much better",
            "Project's done and I'm back to sleeping by 11:15. The difference in how I feel is night and day.",
            9800, 0.5, &["sleep", "11:15 PM", "recovered", "better"],
            "sleep_schedule", 3),

        // === UPDATE CHAIN 10: TV/Streaming ===
        super::update("daily_life.091", "daily_life",
            "Subscribed to Netflix, Watcha, and Disney+ but mostly watches Netflix",
            "I have Netflix, Watcha, and Disney+ but honestly I only really use Netflix.",
            2500, 0.4, &["Netflix", "Watcha", "Disney+", "streaming"],
            "streaming_sub", 1),
        super::update("daily_life.092", "daily_life",
            "Cancelled Watcha subscription, wasn't using it. Down to Netflix and Disney+ only.",
            "Finally cancelled Watcha. Wasn't worth the 7,900 won, I never opened it. Netflix and Disney+ stay.",
            6600, 0.4, &["Watcha", "cancelled", "Netflix", "Disney+"],
            "streaming_sub", 2),

        // === FINAL FACTS ===
        super::fact("daily_life.093", "daily_life",
            "Has a small fire extinguisher in the kitchen, checked expiration date in January 2026",
            "I checked my fire extinguisher in January, still good until 2028. Safety first.",
            9100, 0.3, &["fire extinguisher", "kitchen", "safety", "2028"]),
        super::fact("daily_life.094", "daily_life",
            "Favorite convenience store is CU right below the apartment, knows the night clerk Dongwoo by name",
            "The CU downstairs is dangerous for late-night snacking. Dongwoo the night clerk knows my order by now.",
            9300, 0.4, &["CU", "convenience store", "Dongwoo", "night clerk"]),
        super::fact("daily_life.095", "daily_life",
            "Recycling day is Tuesday and Friday, has separate bins for plastic, paper, glass, and food waste",
            "Recycling is Tuesday and Friday. I have four bins: plastic, paper, glass, and food waste.",
            9400, 0.3, &["recycling", "Tuesday", "Friday", "bins"]),
        super::fact("daily_life.096", "daily_life",
            "Uses a Philips Sonicare toothbrush, replaces head every 3 months",
            "Philips Sonicare gang. New head every three months, I set a reminder.",
            9500, 0.3, &["toothbrush", "Philips", "Sonicare"]),
        super::fact("daily_life.097", "daily_life",
            "Has a small bookshelf in the living room with about 80 books, organized by color because of Instagram",
            "My bookshelf has about 80 books organized by color. Yes, I did it for Instagram. No regrets.",
            9600, 0.3, &["bookshelf", "80 books", "color organized", "Instagram"]),
        super::fact("daily_life.098", "daily_life",
            "Morning bus alternative on rainy days: Bus 7017 from Yeonnam intersection to Gangnam, takes 55 minutes",
            "When it rains I take Bus 7017 instead of the subway. Takes 55 minutes but I get a seat.",
            9700, 0.4, &["bus", "7017", "rainy", "55 minutes", "Yeonnam"]),
        super::fact("daily_life.099", "daily_life",
            "Apartment faces south with good natural light, doesn't need to turn on lights until 5 PM in summer",
            "My apartment faces south so the natural light is amazing. Don't need lights until like 5 PM in summer.",
            9800, 0.3, &["south facing", "natural light", "apartment"]),
        super::fact("daily_life.100", "daily_life",
            "Has a 'Sunday reset' ritual: clean, meal prep, plan week, call mom, evening walk",
            "Sundays are my reset day: clean, meal prep, plan the week, call mom, then an evening walk. Perfect formula.",
            9900, 0.6, &["Sunday reset", "ritual", "clean", "meal prep", "call mom"]),
    ]
}

pub fn false_probes() -> Vec<Question> {
    vec![
        // never_mentioned (15)
        super::false_probe("daily_life.FM.001", "daily_life",
            "What brand of rice cooker do you use at home?"),
        super::false_probe("daily_life.FM.002", "daily_life",
            "You mentioned your apartment has a dishwasher - what brand is it?"),
        super::false_probe("daily_life.FM.003", "daily_life",
            "What floor is your apartment on? You said it was the 3rd floor, right?"),
        super::false_probe("daily_life.FM.004", "daily_life",
            "Didn't you say you take Line 6 to work?"),
        super::false_probe("daily_life.FM.005", "daily_life",
            "What was the name of that Thai restaurant near your office you liked?"),
        super::false_probe("daily_life.FM.006", "daily_life",
            "You mentioned getting a Roomba robot vacuum - how's that working out?"),
        super::false_probe("daily_life.FM.007", "daily_life",
            "What time do you usually wake up on holidays? You said 11 AM right?"),
        super::false_probe("daily_life.FM.008", "daily_life",
            "Didn't you say you bought your Kindle at Kyobo bookstore?"),
        super::false_probe("daily_life.FM.009", "daily_life",
            "How's your succulent garden on the windowsill doing?"),
        super::false_probe("daily_life.FM.010", "daily_life",
            "You mentioned your apartment building has a gym - do you use it often?"),
        super::false_probe("daily_life.FM.011", "daily_life",
            "What was the name of that food delivery app you said you preferred over the others? Yogiyo?"),
        super::false_probe("daily_life.FM.012", "daily_life",
            "Didn't you say you use a French press for your morning coffee?"),
        super::false_probe("daily_life.FM.013", "daily_life",
            "What's the name of the dry cleaner you use near your apartment?"),
        super::false_probe("daily_life.FM.014", "daily_life",
            "You said you have a treadmill at home, right?"),
        super::false_probe("daily_life.FM.015", "daily_life",
            "What was that meal kit subscription service you signed up for?"),

        // adjacent_entity (10)
        super::false_probe("daily_life.FM.016", "daily_life",
            "You mentioned your neighbor in 301 who plays piano late at night - is that still happening?"),
        super::false_probe("daily_life.FM.017", "daily_life",
            "How's that aloe vera plant you got at Kukje Flower Market?"),
        super::false_probe("daily_life.FM.018", "daily_life",
            "You said you shop at Homeplus on Sundays, right?"),
        super::false_probe("daily_life.FM.019", "daily_life",
            "Didn't you mention your Sony WF-1000XM5 earbuds for the commute?"),
        super::false_probe("daily_life.FM.020", "daily_life",
            "You said you switched from iPhone to the Galaxy S25 recently?"),
        super::false_probe("daily_life.FM.021", "daily_life",
            "How's the Aeropress working out for your morning coffee?"),
        super::false_probe("daily_life.FM.022", "daily_life",
            "You use Tving for streaming too, right?"),
        super::false_probe("daily_life.FM.023", "daily_life",
            "Your Samsung 65-inch TV - are you happy with it?"),
        super::false_probe("daily_life.FM.024", "daily_life",
            "Didn't you say the CU clerk's name was Junwoo?"),
        super::false_probe("daily_life.FM.025", "daily_life",
            "You mentioned coffee beans from Coffee Libre in Mapo, right?"),

        // plausible_inference (5)
        super::false_probe("daily_life.FM.026", "daily_life",
            "Since you live alone, do you find the 23 pyeong apartment too big sometimes?"),
        super::false_probe("daily_life.FM.027", "daily_life",
            "You must spend a lot on Coupang with free delivery - what's your monthly average there?"),
        super::false_probe("daily_life.FM.028", "daily_life",
            "With your shellfish allergy, I assume you avoid Japanese restaurants entirely?"),
        super::false_probe("daily_life.FM.029", "daily_life",
            "Since you bike to work sometimes, you must own your own bicycle too right?"),
        super::false_probe("daily_life.FM.030", "daily_life",
            "Given your smart home setup, do you use a robot vacuum to complement the Dyson?"),

        // temporal_phantom (5)
        super::false_probe("daily_life.FM.031", "daily_life",
            "Remember when you briefly switched to waking up at 5:30 AM for that 30-day challenge?"),
        super::false_probe("daily_life.FM.032", "daily_life",
            "Didn't your rent go up to 1 million won at some point?"),
        super::false_probe("daily_life.FM.033", "daily_life",
            "You mentioned your Dyson broke down and you had to get it repaired last December?"),
        super::false_probe("daily_life.FM.034", "daily_life",
            "Wasn't there a period when you were doing intermittent fasting and skipping dinner?"),
        super::false_probe("daily_life.FM.035", "daily_life",
            "You said you tried switching to decaf for a month, right?"),

        // cross_category (5)
        super::false_probe("daily_life.FM.036", "daily_life",
            "Did your morning routine change when you started that online course?"),
        super::false_probe("daily_life.FM.037", "daily_life",
            "You mentioned adjusting your commute time because of your running schedule?"),
        super::false_probe("daily_life.FM.038", "daily_life",
            "Didn't Mochi the cat knock over your monstera Gerald at some point?"),
        super::false_probe("daily_life.FM.039", "daily_life",
            "You said your therapist Dr. Park recommended the no-screen Wednesday habit, right?"),
        super::false_probe("daily_life.FM.040", "daily_life",
            "Didn't your sister Soojin help you set up the smart home system?"),
    ]
}
