use crate::types::{Fact, Question};

pub fn facts() -> Vec<Fact> {
    vec![
        // === FORMAL EDUCATION (early turns) ===
        super::fact("education_skills.001", "education_skills",
            "Graduated from Yonsei University in 2022, Bachelor's in Visual Communication Design",
            "Yonsei, Visual Communication Design, class of 2022. Four years of learning to make things beautiful.",
            60, 0.9, &["Yonsei", "Visual Communication Design", "2022", "Bachelor's"]),
        super::fact("education_skills.002", "education_skills",
            "GPA was 3.7/4.3, graduated magna cum laude, dean's list 5 out of 8 semesters",
            "3.7 GPA out of 4.3. Magna cum laude. Dean's list 5 semesters. Proud of that.",
            130, 0.6, &["GPA", "3.7", "magna cum laude", "dean's list"]),
        super::fact("education_skills.003", "education_skills",
            "Senior thesis was on 'Emotional Design in Korean Digital Products', received department award",
            "Senior thesis: 'Emotional Design in Korean Digital Products.' Won the department award. My proudest academic moment.",
            200, 0.6, &["thesis", "Emotional Design", "department award"]),
        super::fact("education_skills.004", "education_skills",
            "High school was Haeundae High School in Busan, graduated 2018, was in the art elective track",
            "Haeundae High School, class of 2018. Art track. That's where I decided design was my path.",
            170, 0.5, &["Haeundae High School", "2018", "art track", "Busan"]),
        super::fact("education_skills.005", "education_skills",
            "Attended elementary and middle school in Haeundae, normal public schools, no private education (hagwon) for academics",
            "Normal public schools in Haeundae. No hagwon for academics, just an art academy on weekends.",
            250, 0.4, &["public school", "Haeundae", "no hagwon", "art academy"]),

        // === LANGUAGE SKILLS ===
        super::fact("education_skills.006", "education_skills",
            "Native Korean speaker, fluent English speaker. Learned English from age 10 with native-speaking tutors",
            "Korean is my native language. English I've been learning since I was 10. Fluent now, think in both.",
            80, 0.8, &["Korean", "English", "bilingual", "fluent"]),
        super::fact("education_skills.007", "education_skills",
            "TOEIC score: 935/990, taken in 2021 for job applications",
            "TOEIC 935. Took it in 2021 for job hunting. Not perfect but close enough.",
            300, 0.5, &["TOEIC", "935", "2021", "English test"]),
        super::fact("education_skills.008", "education_skills",
            "Studying Japanese, passed JLPT N4 in December 2025, preparing for N3 in July 2026",
            "I passed JLPT N4 in December! Studying for N3 in July. Japanese is hard but I love it.",
            350, 0.7, &["JLPT", "N4", "December 2025", "N3", "Japanese"]),
        super::fact("education_skills.009", "education_skills",
            "Studies Japanese using Genki textbook series, Anki flashcards, and NHK World podcasts",
            "My Japanese study stack: Genki textbook, Anki flashcards, NHK World podcasts. Every day 30 minutes.",
            450, 0.4, &["Genki", "Anki", "NHK World", "Japanese study"]),
        super::fact("education_skills.010", "education_skills",
            "Can read basic Japanese manga in original, currently reading 'Yotsuba&!' for practice",
            "I can read simple manga in Japanese now. 'Yotsuba&!' is perfect for my level.",
            1000, 0.4, &["manga", "Japanese reading", "Yotsuba", "practice"]),

        // === DESIGN SKILLS ===
        super::fact("education_skills.011", "education_skills",
            "Expert-level Figma user, Figma Community Advocate certified since March 2025",
            "Figma is my primary tool. Got the Community Advocate certification in March 2025.",
            120, 0.8, &["Figma", "expert", "Community Advocate", "certified"]),
        super::fact("education_skills.012", "education_skills",
            "Proficient in Adobe Creative Suite: Illustrator (advanced), Photoshop (intermediate), After Effects (basic)",
            "Adobe: Illustrator advanced, Photoshop intermediate, After Effects basic. Figma replaced most Adobe work.",
            400, 0.5, &["Adobe", "Illustrator", "Photoshop", "After Effects"]),
        super::fact("education_skills.013", "education_skills",
            "Learned Framer for interactive prototyping, used it for 3 Velta client presentations",
            "Framer for interactive prototypes. Used it for 3 client presentations. Clients were blown away.",
            750, 0.5, &["Framer", "prototyping", "interactive", "client presentations"]),
        super::fact("education_skills.014", "education_skills",
            "Typography skills: can identify over 50 typefaces on sight, favorite is Pretendard for Korean and Inter for English",
            "I can ID about 50 typefaces by sight. Pretendard for Korean, Inter for English. My go-to pairing.",
            900, 0.4, &["typography", "Pretendard", "Inter", "typefaces"]),
        super::fact("education_skills.015", "education_skills",
            "Color theory knowledge from university is applied daily, uses HSB model exclusively for color decisions",
            "I use HSB for all color decisions. RGB and HEX are outputs, HSB is how you think about color.",
            1100, 0.4, &["color theory", "HSB", "university", "color decisions"]),

        // === CODING SKILLS ===
        super::fact("education_skills.016", "education_skills",
            "Learned Python basics through Codecademy in 2023, can write simple scripts for data processing",
            "I know basic Python from Codecademy. Simple scripts, data processing. Enough to be dangerous.",
            500, 0.6, &["Python", "Codecademy", "2023", "basics"]),
        super::fact("education_skills.017", "education_skills",
            "Knows HTML/CSS well enough to inspect and modify frontend code, helps bridge design-dev gap at Velta",
            "I know HTML/CSS well enough to inspect code and suggest tweaks. Bridge between design and dev.",
            650, 0.5, &["HTML", "CSS", "frontend", "inspect"]),
        super::fact("education_skills.018", "education_skills",
            "Started learning Go basics because Velta backend uses it, completed 'A Tour of Go' tutorial",
            "Learning Go since Velta uses it. Did 'A Tour of Go.' Can read the code now, can't write production code.",
            1300, 0.4, &["Go", "Tour of Go", "Velta", "backend"]),
        super::fact("education_skills.019", "education_skills",
            "Can write basic JavaScript for Figma plugins, created a small plugin for batch-renaming layers",
            "I made a Figma plugin for batch-renaming layers. Basic JavaScript but the team uses it daily.",
            1500, 0.5, &["JavaScript", "Figma plugin", "batch-renaming", "layers"]),

        // === COURSERA UX COURSE ===
        super::update("education_skills.020", "education_skills",
            "Enrolled in Google UX Design Professional Certificate on Coursera in October 2025",
            "I enrolled in the Google UX Design cert on Coursera. October 2025. Even as a working designer, there's more to learn.",
            1800, 0.6, &["Google UX Design", "Coursera", "October 2025", "certificate"],
            "coursera_ux", 1),
        super::update("education_skills.021", "education_skills",
            "Completed 4 out of 7 courses in the Google UX certificate by January 2026",
            "Four out of seven courses done. The research methods module was the most valuable so far.",
            4000, 0.5, &["4 out of 7", "Google UX", "research methods"],
            "coursera_ux", 2),
        super::update("education_skills.022", "education_skills",
            "Completed Google UX Design Certificate in February 2026, added to LinkedIn profile",
            "Google UX Design Certificate: DONE. February 2026. Added to LinkedIn immediately.",
            5500, 0.6, &["completed", "Google UX", "February 2026", "LinkedIn"],
            "coursera_ux", 3),

        // === HCI MASTERS CONSIDERATION ===
        super::update("education_skills.023", "education_skills",
            "Started researching HCI (Human-Computer Interaction) master's programs in Korea: KAIST, SNU, Yonsei",
            "I've been looking into HCI master's programs. KAIST, SNU, Yonsei all have good ones.",
            2000, 0.7, &["HCI", "master's", "KAIST", "SNU", "Yonsei"],
            "hci_masters", 1),
        super::update("education_skills.024", "education_skills",
            "Attended KAIST HCI Lab open house in November 2025, met Professor Lee Hyunjoo who runs the lab",
            "Went to KAIST HCI Lab open house. Met Professor Lee Hyunjoo. Her research on emotional AI design blew my mind.",
            2800, 0.6, &["KAIST", "HCI Lab", "Professor Lee Hyunjoo", "open house"],
            "hci_masters", 2),
        super::update("education_skills.025", "education_skills",
            "Decided to postpone HCI master's for at least 2 years due to Velta's growth trajectory and potential IPO",
            "Postponing the master's. Velta is too exciting right now. Maybe 2028. KAIST will still be there.",
            6000, 0.7, &["postpone", "master's", "2028", "Velta growth"],
            "hci_masters", 3),

        // === PROFESSIONAL DEVELOPMENT ===
        super::fact("education_skills.026", "education_skills",
            "Attended UX Seoul Conference 2025 as both attendee and speaker, networking yielded 15 new contacts",
            "UX Seoul Conference was great for networking. 15 new contacts. And I spoke there too.",
            2200, 0.5, &["UX Seoul Conference", "speaker", "networking", "15 contacts"]),
        super::fact("education_skills.027", "education_skills",
            "Completed a design leadership workshop by IDEO in Seoul, 2-day intensive in June 2025",
            "IDEO design leadership workshop in Seoul. Two-day intensive in June 2025. Changed how I think about leading.",
            1700, 0.5, &["IDEO", "workshop", "design leadership", "June 2025"]),
        super::fact("education_skills.028", "education_skills",
            "Has a LinkedIn Learning subscription through Velta, completed 12 courses in 2025",
            "LinkedIn Learning through work. Did 12 courses in 2025. Mostly design thinking and UX research.",
            2400, 0.3, &["LinkedIn Learning", "12 courses", "2025"]),
        super::fact("education_skills.029", "education_skills",
            "Reads design blogs daily: Smashing Magazine, UX Collective on Medium, Nielsen Norman Group",
            "Daily reading: Smashing Magazine, UX Collective, NNG. Staying current is part of the job.",
            800, 0.4, &["Smashing Magazine", "UX Collective", "Nielsen Norman Group"]),
        super::fact("education_skills.030", "education_skills",
            "Subscribed to 'Design Systems Weekly' newsletter by Brad Frost, reads it every Monday morning",
            "Brad Frost's Design Systems Weekly every Monday. Essential reading for my work.",
            1200, 0.3, &["Design Systems Weekly", "Brad Frost", "newsletter"]),

        // === UPDATE CHAIN: Japanese study progress ===
        super::update("education_skills.031", "education_skills",
            "Japanese study routine: 30 minutes daily before bed, uses Anki for kanji (learned 350 kanji so far)",
            "Japanese: 30 minutes nightly. 350 kanji in Anki. I can read menus and basic signs now.",
            550, 0.5, &["Japanese", "30 minutes", "350 kanji", "Anki"],
            "japanese_progress", 1),
        super::update("education_skills.032", "education_skills",
            "Kanji count reached 500 by March 2026, started watching Japanese dramas without subtitles for listening practice",
            "500 kanji! Watching Japanese dramas without subs for listening. I catch about 40% of dialogue.",
            7000, 0.5, &["500 kanji", "Japanese dramas", "no subtitles", "listening"],
            "japanese_progress", 2),

        // === UPDATE CHAIN: Python skills growth ===
        super::update("education_skills.033", "education_skills",
            "Started using Python for design workflow automation: batch image processing and file organization",
            "Using Python to automate design tasks. Batch image processing, file org. Saves me hours each week.",
            3000, 0.5, &["Python", "automation", "batch image", "workflow"],
            "python_skills", 1),
        super::update("education_skills.034", "education_skills",
            "Built a Python script that generates weekly design metric reports from Amplitude API data",
            "Built a Python script that pulls Amplitude data and generates design metric reports. The team loves it.",
            5000, 0.5, &["Python", "Amplitude API", "metric reports", "script"],
            "python_skills", 2),

        // === UPDATE CHAIN: Teaching and mentoring ===
        super::update("education_skills.035", "education_skills",
            "Started writing tutorial articles on Medium about Figma techniques, 3 articles published",
            "I've published 3 Figma tutorial articles on Medium. Giving back to the design community.",
            3500, 0.4, &["Medium", "tutorials", "Figma", "3 articles"],
            "teaching", 1),
        super::update("education_skills.036", "education_skills",
            "Invited to be a guest lecturer at Yonsei University's Visual Design department in April 2026",
            "Yonsei invited me to guest lecture! April 2026, Visual Design department. Full circle moment.",
            8000, 0.6, &["guest lecturer", "Yonsei", "April 2026", "Visual Design"],
            "teaching", 2),

        // === UPDATE CHAIN: Design skills evolution ===
        super::update("education_skills.037", "education_skills",
            "Learning motion design using After Effects and Lottie for Velta micro-interactions",
            "I'm diving into motion design. After Effects and Lottie. Our micro-interactions need more life.",
            2600, 0.5, &["motion design", "After Effects", "Lottie", "micro-interactions"],
            "design_evolution", 1),
        super::update("education_skills.038", "education_skills",
            "Created first Lottie animation for Velta onboarding flow, received positive user feedback",
            "First Lottie animation went into the onboarding flow. Users noticed and commented positively. Validation.",
            4500, 0.5, &["Lottie animation", "onboarding", "user feedback"],
            "design_evolution", 2),

        // === UPDATE CHAIN: AI tools in design ===
        super::update("education_skills.039", "education_skills",
            "Started experimenting with AI design tools: Midjourney for mood boards, Claude for UX copy",
            "AI tools are changing my workflow. Midjourney for mood boards, Claude for UX copy drafts.",
            3800, 0.5, &["AI tools", "Midjourney", "Claude", "mood boards", "UX copy"],
            "ai_tools", 1),
        super::update("education_skills.040", "education_skills",
            "Developed a workflow combining Figma + Claude + Midjourney for rapid prototyping, shared it at team meeting",
            "My Figma + Claude + Midjourney workflow for rapid prototyping. Shared it at the team meeting. Everyone wanted to learn.",
            6500, 0.5, &["workflow", "rapid prototyping", "Figma", "Claude", "Midjourney"],
            "ai_tools", 2),

        // === SELF-TAUGHT SKILLS ===
        super::fact("education_skills.041", "education_skills",
            "Self-taught film photography: learned developing from YouTube, processes basic B&W at home",
            "I taught myself film photography from YouTube. Can process basic B&W at home in the bathroom.",
            600, 0.5, &["film photography", "self-taught", "B&W developing", "YouTube"]),
        super::fact("education_skills.042", "education_skills",
            "Learned sourdough baking from 'Flour Water Salt Yeast' book by Ken Forkish",
            "Sourdough journey started with Ken Forkish's book. 'Flour Water Salt Yeast.' Bible for bread.",
            700, 0.4, &["sourdough", "Ken Forkish", "Flour Water Salt Yeast", "baking"]),
        super::fact("education_skills.043", "education_skills",
            "Basic music theory knowledge from a free online course (Musictheory.net), can read simple sheet music",
            "I know basic music theory from Musictheory.net. Can read simple sheet music. Enough to appreciate what I hear.",
            1400, 0.3, &["music theory", "Musictheory.net", "sheet music", "basic"]),
        super::fact("education_skills.044", "education_skills",
            "Learned basic video editing in DaVinci Resolve for personal travel vlogs, never published any",
            "I edit personal travel videos in DaVinci Resolve. Never published though. They're just for me.",
            1600, 0.3, &["DaVinci Resolve", "video editing", "travel vlogs", "personal"]),

        // === CERTIFICATES AND AWARDS ===
        super::fact("education_skills.045", "education_skills",
            "Figma Community Advocate certification, earned March 2025, valid for 2 years",
            "Figma Community Advocate cert since March 2025. Valid for 2 years. Plan to renew.",
            400, 0.5, &["Figma", "Community Advocate", "certification", "2025"]),
        super::fact("education_skills.046", "education_skills",
            "Won 2nd place in Korea Design Award 2024 (student division) for a mental health app concept",
            "Korea Design Award 2024, 2nd place student division. Mental health app concept. Still proud of that.",
            350, 0.5, &["Korea Design Award", "2024", "2nd place", "mental health app"]),
        super::fact("education_skills.047", "education_skills",
            "TOEFL score: 108/120, taken in 2020 as backup for potential overseas study",
            "TOEFL 108 in 2020. Was considering studying abroad but decided Yonsei was right.",
            500, 0.4, &["TOEFL", "108", "2020", "overseas study"]),

        // === LEARNING STYLE AND PHILOSOPHY ===
        super::fact("education_skills.048", "education_skills",
            "Learning philosophy: 'T-shaped designer' - deep in interaction design, broad in research, dev, and business",
            "I aim to be T-shaped: deep in interaction design, broad across research, dev, and business.",
            1900, 0.5, &["T-shaped", "interaction design", "broad", "learning"]),
        super::fact("education_skills.049", "education_skills",
            "Preferred learning method: project-based. Learns new skills by applying them to real work problems.",
            "I learn by doing, not by reading. Give me a real problem and I'll figure out the skill I need.",
            2100, 0.4, &["project-based", "learning method", "real problems"]),
        super::fact("education_skills.050", "education_skills",
            "Keeps a 'skills wishlist' in Notion: currently includes 3D design (Blender), data visualization, and copywriting",
            "My Notion skills wishlist: Blender for 3D, data viz, copywriting. Always something to learn.",
            2300, 0.4, &["skills wishlist", "Blender", "3D", "data visualization", "Notion"]),

        // === MID-RANGE FACTS ===
        super::fact("education_skills.051", "education_skills",
            "Yonsei professor who influenced him most: Professor Shin Donghyuk, taught Interaction Design course",
            "Professor Shin Donghyuk at Yonsei changed my trajectory. His Interaction Design course was transformative.",
            2500, 0.4, &["Professor Shin", "Yonsei", "Interaction Design"]),
        super::fact("education_skills.052", "education_skills",
            "University exchange program: spent one semester at Tokyo Zokei University in 2021, sparked Japan interest",
            "I did an exchange semester at Tokyo Zokei University in 2021. That's when I fell for Japan.",
            400, 0.5, &["Tokyo Zokei", "exchange", "2021", "semester"]),
        super::fact("education_skills.053", "education_skills",
            "Presentation skills improved after joining Toastmasters club at Yonsei for 6 months",
            "Toastmasters at Yonsei for 6 months. Terrifying but it fixed my public speaking anxiety. Mostly.",
            2700, 0.4, &["Toastmasters", "Yonsei", "public speaking", "6 months"]),
        super::fact("education_skills.054", "education_skills",
            "Can touch-type at 90 WPM in English, about 60 WPM in Korean on a Samsung keyboard layout",
            "I type 90 WPM in English, 60 in Korean. Samsung keyboard layout. Mechanical keyboard helps.",
            2900, 0.3, &["typing", "90 WPM", "60 WPM", "Samsung keyboard"]),
        super::fact("education_skills.055", "education_skills",
            "Knows basic SQL from a weekend course at Fastcampus in 2024, useful for pulling data from Velta's DB",
            "Basic SQL from Fastcampus. Weekend course in 2024. I can query our DB for design data now.",
            3100, 0.4, &["SQL", "Fastcampus", "2024", "database"]),
        super::fact("education_skills.056", "education_skills",
            "UX writing skills developed through daily practice: writes all in-app copy for Velta features",
            "I write all the in-app copy at Velta. UX writing is design. Every word is a design decision.",
            3300, 0.4, &["UX writing", "in-app copy", "Velta", "daily"]),
        super::fact("education_skills.057", "education_skills",
            "Military service: completed 18 months in the army (KATUSA) from 2019-2020, stationed at Camp Humphreys",
            "KATUSA service at Camp Humphreys, 2019-2020. 18 months. My English got really good there.",
            270, 0.6, &["KATUSA", "military", "Camp Humphreys", "2019-2020", "18 months"]),
        super::fact("education_skills.058", "education_skills",
            "Design thinking certifications: completed IDEO U 'Foundations in Design Thinking' online course",
            "IDEO U Foundations in Design Thinking. Online course. Structured thinking framework I still use daily.",
            3500, 0.4, &["IDEO U", "Design Thinking", "foundations", "online"]),
        super::fact("education_skills.059", "education_skills",
            "Can do basic woodworking, learned from father's workshop as a teenager",
            "Dad taught me basic woodworking in his workshop. I can make simple shelves and picture frames.",
            3700, 0.3, &["woodworking", "father", "workshop", "shelves"]),
        super::fact("education_skills.060", "education_skills",
            "Reading speed: about 50 pages per hour in Korean, 35 pages per hour in English",
            "I read about 50 pages/hour in Korean, 35 in English. Audiobooks don't work for me.",
            3900, 0.3, &["reading speed", "50 pages", "35 pages", "Korean", "English"]),
        super::fact("education_skills.061", "education_skills",
            "Knows basic statistics from a university elective: mean, median, regression, p-values",
            "I took statistics as an elective. Mean, median, regression, p-values. Useful for user research.",
            4100, 0.3, &["statistics", "university", "regression", "p-values"]),
        super::fact("education_skills.062", "education_skills",
            "Photography skills: understands exposure triangle (ISO, aperture, shutter speed), shoots manual on Canon AE-1",
            "I shoot full manual on my Canon AE-1. Exposure triangle is second nature now. ISO, aperture, shutter.",
            4300, 0.4, &["photography", "exposure triangle", "ISO", "Canon AE-1", "manual"]),
        super::fact("education_skills.063", "education_skills",
            "Accessibility knowledge: WCAG 2.1 guidelines, screen reader testing, color contrast ratios",
            "I know WCAG 2.1 well. Screen reader testing, contrast ratios. The accessibility audit failure taught me.",
            4500, 0.5, &["WCAG", "accessibility", "screen reader", "contrast"]),
        super::fact("education_skills.064", "education_skills",
            "User research skills: conducts interviews, surveys, usability tests, card sorting, tree testing",
            "I do user interviews, surveys, usability tests, card sorting, tree testing. Full research toolkit.",
            4700, 0.4, &["user research", "interviews", "usability tests", "card sorting"]),
        super::fact("education_skills.065", "education_skills",
            "Wireframing speed: can produce low-fidelity wireframes for a feature in about 2 hours",
            "I can wireframe a full feature in about 2 hours. Low-fi. Speed comes from having a component library.",
            4900, 0.3, &["wireframing", "2 hours", "low-fidelity", "speed"]),

        // === LATER TURNS ===
        super::fact("education_skills.066", "education_skills",
            "Learning Blender 3D in spare time, following Donut Tutorial by Blender Guru on YouTube",
            "I started the Blender Donut Tutorial. Blender Guru. Everyone starts with the donut.",
            5200, 0.4, &["Blender", "3D", "Donut Tutorial", "Blender Guru"]),
        super::fact("education_skills.067", "education_skills",
            "Completed basic Blender donut, now learning character modeling for potential Velta mascot redesign",
            "Donut done! Now trying character modeling. Thinking about redesigning Veltie in 3D.",
            6500, 0.3, &["Blender", "character modeling", "Veltie", "3D"]),
        super::fact("education_skills.068", "education_skills",
            "Attended a Figma Config recap event at WeWork Gangnam, organized by Korean Figma community",
            "Figma Config recap event at WeWork. Korean Figma community organized it. Great networking.",
            5400, 0.3, &["Config", "Figma community", "WeWork", "recap"]),
        super::fact("education_skills.069", "education_skills",
            "Skill gap self-assessment: weakest areas are business strategy and data analysis",
            "My weakest areas: business strategy and data analysis. Working on both.",
            5600, 0.4, &["skill gap", "business strategy", "data analysis", "weak"]),
        super::fact("education_skills.070", "education_skills",
            "Considered a Chartered Financial Planner certification for personal finance but decided it's overkill",
            "I thought about getting a finance cert for personal investing. Overkill. YouTube is fine.",
            5800, 0.3, &["financial planner", "certification", "considered", "overkill"]),
        super::fact("education_skills.071", "education_skills",
            "Can cook 15 Korean dishes confidently, 8 Japanese dishes, and 5 Western dishes",
            "Cooking repertoire: 15 Korean dishes, 8 Japanese, 5 Western. All self-taught from YouTube and mom.",
            6200, 0.3, &["cooking", "15 Korean", "8 Japanese", "5 Western"]),
        super::fact("education_skills.072", "education_skills",
            "Knows Hangul (Korean alphabet) creation history in detail, fascinated by King Sejong's design process",
            "King Sejong creating Hangul was basically design thinking in 1443. I've studied the process in detail.",
            6400, 0.3, &["Hangul", "King Sejong", "design thinking", "history"]),
        super::fact("education_skills.073", "education_skills",
            "Can use a sewing machine (mother taught basic skills), repairs own clothes occasionally",
            "Mom taught me basic sewing. I can fix a button, hem pants. Saves money and trips to the tailor.",
            6600, 0.3, &["sewing", "mother taught", "repairs", "basic"]),
        super::fact("education_skills.074", "education_skills",
            "University elective in Art History covered Renaissance to Contemporary, favorite period: Bauhaus",
            "Art History elective at Yonsei. Renaissance to Contemporary. Bauhaus is my era. Function meets form.",
            6800, 0.4, &["Art History", "Bauhaus", "university", "elective"]),
        super::fact("education_skills.075", "education_skills",
            "CPR certified from military service, renews every 2 years at the local fire station",
            "CPR certified from KATUSA days. I renew every 2 years at the fire station. Hope I never need it.",
            7000, 0.3, &["CPR", "certified", "military", "fire station"]),
        super::fact("education_skills.076", "education_skills",
            "Knows how to develop color film at home: C-41 process in a Paterson tank, temperature-critical",
            "I develop color film at home. C-41 process in a Paterson tank. Temperature has to be exact at 38°C.",
            7200, 0.4, &["C-41", "film developing", "Paterson tank", "color film"]),
        super::fact("education_skills.077", "education_skills",
            "Touch-type on both QWERTY and Korean Dubeolsik keyboard layout without looking",
            "I can type both QWERTY and Dubeolsik without looking. Decades of practice.",
            7400, 0.3, &["typing", "QWERTY", "Dubeolsik", "touch type"]),
        super::fact("education_skills.078", "education_skills",
            "Knows basic first aid from military training: wound care, splinting, tourniquet application",
            "Military taught me first aid: wound care, splinting, tourniquet. Practical skills I hope to never use.",
            7600, 0.3, &["first aid", "military", "wound care", "splinting"]),
        super::fact("education_skills.079", "education_skills",
            "Design portfolio website built with Framer, updated quarterly, URL is kimdesign.studio",
            "My portfolio is at kimdesign.studio. Built with Framer. Update it quarterly.",
            7800, 0.4, &["portfolio", "kimdesign.studio", "Framer", "quarterly"]),
        super::fact("education_skills.080", "education_skills",
            "Can navigate Seoul's entire subway system from memory, knows transfer stations and efficient routes",
            "I know the Seoul subway map by heart. Every transfer station. Most efficient routes. Years of commuting.",
            8000, 0.3, &["Seoul subway", "memory", "transfer stations", "navigation"]),
        super::fact("education_skills.081", "education_skills",
            "Handwriting: has neat Korean handwriting, won penmanship award in elementary school",
            "My Korean handwriting is neat. Won a penmanship award in elementary. Mom still has the certificate.",
            8200, 0.3, &["handwriting", "penmanship", "award", "elementary"]),
        super::fact("education_skills.082", "education_skills",
            "Knows basics of information architecture: card sorting, site maps, navigation structures",
            "Information architecture: card sorting, site maps, nav structures. Foundation of every project.",
            8400, 0.3, &["information architecture", "card sorting", "site maps"]),
        super::fact("education_skills.083", "education_skills",
            "Can give design critique using the SBI (Situation-Behavior-Impact) feedback framework",
            "I use SBI framework for design critiques. Situation, Behavior, Impact. Keeps feedback constructive.",
            8600, 0.3, &["SBI", "feedback", "design critique", "framework"]),
        super::fact("education_skills.084", "education_skills",
            "Familiar with design sprints (Google Ventures style), has facilitated 4 at Velta",
            "I've facilitated 4 design sprints at Velta. GV style. Five days of focused chaos.",
            8800, 0.4, &["design sprints", "Google Ventures", "facilitated", "4 sprints"]),
        super::fact("education_skills.085", "education_skills",
            "Knows enough about Korean copyright law to advise on image licensing for Velta marketing",
            "I know Korean copyright law basics. Image licensing for marketing, font licensing. The boring but important stuff.",
            9000, 0.3, &["copyright law", "image licensing", "Korean law"]),
        super::fact("education_skills.086", "education_skills",
            "Learned to ride a motorcycle during military service but doesn't ride anymore, no license",
            "I learned to ride a motorcycle in the army. Don't ride anymore, no civilian license.",
            9100, 0.3, &["motorcycle", "military", "learned", "no license"]),
        super::fact("education_skills.087", "education_skills",
            "Took a weekend calligraphy course in Insadong in 2024, practices occasionally",
            "Calligraphy weekend course in Insadong, 2024. I practice when I need to zen out.",
            9200, 0.3, &["calligraphy", "Insadong", "2024", "weekend"]),
        super::fact("education_skills.088", "education_skills",
            "Excel/Google Sheets: advanced level, uses pivot tables and vlookups for design metric tracking",
            "Advanced spreadsheet skills. Pivot tables, vlookups for design metrics. Data-informed design.",
            9300, 0.3, &["Excel", "Google Sheets", "pivot tables", "vlookup"]),
        super::fact("education_skills.089", "education_skills",
            "Knows basic darkroom printing techniques (silver gelatin) from a university elective course",
            "University darkroom course taught me silver gelatin printing. Magical watching an image appear in the developer.",
            9400, 0.3, &["darkroom", "silver gelatin", "printing", "university"]),
        super::fact("education_skills.090", "education_skills",
            "Time management system: modified Pomodoro (35 minutes work, 10 minutes break) since standard 25/5 felt too short",
            "I do modified Pomodoro: 35 min work, 10 min break. Standard 25/5 was too short for design flow.",
            9500, 0.3, &["Pomodoro", "time management", "35 minutes", "modified"]),
        super::fact("education_skills.091", "education_skills",
            "Guest lecturer prep for Yonsei: preparing talk on 'From Student to Senior Designer in 4 Years'",
            "My Yonsei guest lecture topic: 'From Student to Senior Designer in 4 Years.' Writing the slides now.",
            9600, 0.4, &["Yonsei", "guest lecture", "Student to Senior", "preparation"]),
        super::fact("education_skills.092", "education_skills",
            "Knows sign language finger alphabet from a volunteer project in university",
            "I know the Korean sign language alphabet from a uni volunteer project. Basics only but it's something.",
            9650, 0.3, &["sign language", "sign language finger alphabet", "volunteer", "university"]),
        super::fact("education_skills.093", "education_skills",
            "Mental math: fairly quick, can calculate tips, discounts, and split bills without a calculator",
            "I'm pretty fast at mental math. Tips, splits, discounts. Friends hate eating with me because I calculate everything.",
            9700, 0.3, &["mental math", "quick", "calculate", "tips"]),
        super::fact("education_skills.094", "education_skills",
            "Knows basic car maintenance from father: checking oil, changing tires, jump-starting a battery",
            "Dad taught me car basics even though I don't own one. Oil, tires, jump-start. Knowledge bank.",
            9750, 0.3, &["car maintenance", "father", "oil", "tires"]),
        super::fact("education_skills.095", "education_skills",
            "Writing skills: can write professional emails in Korean, English, and very basic Japanese",
            "I write professional emails in Korean and English, basic Japanese. Three languages of varying competence.",
            9800, 0.3, &["writing", "emails", "Korean", "English", "Japanese"]),
        super::fact("education_skills.096", "education_skills",
            "Fastest Figma shortcut user in the office, knows 40+ keyboard shortcuts by muscle memory",
            "40+ Figma shortcuts memorized. My mouse barely moves. Soyeon times me sometimes for fun.",
            9830, 0.3, &["Figma", "shortcuts", "40+", "keyboard"]),
        super::fact("education_skills.097", "education_skills",
            "Can navigate by stars (basic): knows Big Dipper, Polaris, Orion. Learned from father's astronomy hobby.",
            "Dad taught me star navigation. Big Dipper, Polaris, Orion. Useful exactly never but I love it.",
            9860, 0.3, &["stars", "navigation", "Big Dipper", "Polaris", "father"]),
        super::fact("education_skills.098", "education_skills",
            "Design book completed most recently: 'Articulating Design Decisions' by Tom Greever",
            "Just finished 'Articulating Design Decisions' by Tom Greever. Should be mandatory for every designer.",
            9890, 0.3, &["Articulating Design Decisions", "Tom Greever", "book"]),
        super::fact("education_skills.099", "education_skills",
            "Learning backlog in Notion has 47 items, organized by priority: high (5), medium (20), low (22)",
            "My learning backlog has 47 items. 5 high priority, 20 medium, 22 low. There's always more to learn.",
            9920, 0.3, &["learning backlog", "47 items", "Notion", "priority"]),
        super::fact("education_skills.100", "education_skills",
            "Lifelong learning philosophy: 'Every year I should be embarrassed by what I didn't know the year before'",
            "My learning motto: every year I should be embarrassed by what I didn't know last year. Growth mindset.",
            9950, 0.4, &["lifelong learning", "philosophy", "growth mindset"]),
    ]
}

pub fn false_probes() -> Vec<Question> {
    vec![
        // never_mentioned (15)
        super::false_probe("education_skills.FM.001", "education_skills",
            "You said you studied at Korea University, right?"),
        super::false_probe("education_skills.FM.002", "education_skills",
            "Didn't you mention getting a master's degree in design?"),
        super::false_probe("education_skills.FM.003", "education_skills",
            "You said you speak Chinese too, right?"),
        super::false_probe("education_skills.FM.004", "education_skills",
            "What was that coding bootcamp you attended in 2024?"),
        super::false_probe("education_skills.FM.005", "education_skills",
            "You mentioned getting AWS certification for cloud computing?"),
        super::false_probe("education_skills.FM.006", "education_skills",
            "Didn't you study abroad in London?"),
        super::false_probe("education_skills.FM.007", "education_skills",
            "You said you can play the piano, right?"),
        super::false_probe("education_skills.FM.008", "education_skills",
            "What was that UX bootcamp at General Assembly you attended?"),
        super::false_probe("education_skills.FM.009", "education_skills",
            "You mentioned having a teaching certificate?"),
        super::false_probe("education_skills.FM.010", "education_skills",
            "Didn't you say you know React and can build frontend apps?"),
        super::false_probe("education_skills.FM.011", "education_skills",
            "You said you dropped out of university and went back later?"),
        super::false_probe("education_skills.FM.012", "education_skills",
            "What was that data science course you took on DataCamp?"),
        super::false_probe("education_skills.FM.013", "education_skills",
            "Didn't you mention getting a TOPIK Level 6 certificate?"),
        super::false_probe("education_skills.FM.014", "education_skills",
            "You said you can do 3D printing at a local maker space?"),
        super::false_probe("education_skills.FM.015", "education_skills",
            "What was that product management certification you completed?"),

        // adjacent_entity (10)
        super::false_probe("education_skills.FM.016", "education_skills",
            "Your JLPT level is N3 now, right?"),
        super::false_probe("education_skills.FM.017", "education_skills",
            "You graduated from Yonsei in 2021, didn't you?"),
        super::false_probe("education_skills.FM.018", "education_skills",
            "Your TOEIC score was 960, right?"),
        super::false_probe("education_skills.FM.019", "education_skills",
            "You did your exchange semester at Kyoto University?"),
        super::false_probe("education_skills.FM.020", "education_skills",
            "Your GPA was 3.9, right?"),
        super::false_probe("education_skills.FM.021", "education_skills",
            "You served in the Navy for military service?"),
        super::false_probe("education_skills.FM.022", "education_skills",
            "The Coursera course was from Stanford, wasn't it?"),
        super::false_probe("education_skills.FM.023", "education_skills",
            "You know 700 kanji now, right?"),
        super::false_probe("education_skills.FM.024", "education_skills",
            "Your portfolio site is built with Webflow?"),
        super::false_probe("education_skills.FM.025", "education_skills",
            "Professor Kim was your most influential Yonsei professor?"),

        // plausible_inference (5)
        super::false_probe("education_skills.FM.026", "education_skills",
            "Since you did KATUSA, you must have considered staying in the military longer?"),
        super::false_probe("education_skills.FM.027", "education_skills",
            "With your Japanese studies, are you planning to work at the Velta Tokyo office?"),
        super::false_probe("education_skills.FM.028", "education_skills",
            "Since you know Python and SQL, are you considering a data science career pivot?"),
        super::false_probe("education_skills.FM.029", "education_skills",
            "Given your teaching at Yonsei, are you becoming an adjunct professor?"),
        super::false_probe("education_skills.FM.030", "education_skills",
            "With your exchange at Tokyo Zokei, you must have taken Japanese classes there?"),

        // temporal_phantom (5)
        super::false_probe("education_skills.FM.031", "education_skills",
            "Didn't you fail the JLPT N3 the first time you took it?"),
        super::false_probe("education_skills.FM.032", "education_skills",
            "You said you dropped the Google UX course halfway and then restarted?"),
        super::false_probe("education_skills.FM.033", "education_skills",
            "Wasn't there a period when you stopped studying Japanese for 6 months?"),
        super::false_probe("education_skills.FM.034", "education_skills",
            "Didn't you apply to KAIST HCI and get rejected?"),
        super::false_probe("education_skills.FM.035", "education_skills",
            "You mentioned losing all your Figma files in a cloud sync issue?"),

        // cross_category (5)
        super::false_probe("education_skills.FM.036", "education_skills",
            "Didn't Eunji help you study for the JLPT N4?"),
        super::false_probe("education_skills.FM.037", "education_skills",
            "You said your bouldering skill V5 achievement was partly thanks to studying climbing technique books?"),
        super::false_probe("education_skills.FM.038", "education_skills",
            "Didn't your sister Soojin tutor you in biology during university?"),
        super::false_probe("education_skills.FM.039", "education_skills",
            "You mentioned using your Python skills to analyze your running data from Strava?"),
        super::false_probe("education_skills.FM.040", "education_skills",
            "Didn't you take a cooking class at that place in Itaewon?"),
    ]
}
