use crate::types::{Fact, Question};

pub fn facts() -> Vec<Fact> {
    vec![
        // === SAVINGS AND INCOME (early turns) ===
        super::fact("finance_goals.001", "finance_goals",
            "Saves approximately 1.5 million won per month, transfers to Kakao Bank savings account on the 1st",
            "I save about 1.5M won a month. Auto-transfer to Kakao Bank savings on the 1st. Discipline.",
            100, 0.8, &["save", "1.5 million", "monthly", "Kakao Bank"]),
        super::fact("finance_goals.002", "finance_goals",
            "Monthly salary after tax from Velta is about 4.5 million won (based on 65M annual gross)",
            "Take-home is about 4.5M won a month from Velta. After tax and insurance and all that.",
            150, 0.7, &["salary", "4.5 million", "take-home", "monthly"]),
        super::fact("finance_goals.003", "finance_goals",
            "Uses Toss app as primary financial dashboard, tracks all spending categories",
            "Toss is my financial command center. Every won tracked and categorized.",
            200, 0.5, &["Toss", "financial", "dashboard", "spending"]),
        super::fact("finance_goals.004", "finance_goals",
            "Monthly budget breakdown: rent 900K, food 500K, transport 65K, subscriptions 50K, discretionary 400K, savings 1.5M",
            "My budget: 900K rent, 500K food, 65K transport, 50K subscriptions, 400K fun money, 1.5M savings. The rest is buffer.",
            300, 0.7, &["budget", "900K rent", "500K food", "1.5M savings"]),
        super::fact("finance_goals.005", "finance_goals",
            "Primary bank is Kakao Bank, secondary is Shinhan Bank (salary deposit account)",
            "Main bank is Kakao Bank but salary goes into Shinhan. I transfer manually each month.",
            350, 0.5, &["Kakao Bank", "Shinhan Bank", "primary", "salary"]),

        // === STUDENT LOAN ===
        super::update("finance_goals.006", "finance_goals",
            "Had a student loan of 15 million won from Korea Student Aid Foundation (KOSAF) for university",
            "I had a 15 million won student loan from KOSAF. Yonsei wasn't cheap even with some aid.",
            250, 0.7, &["student loan", "15 million", "KOSAF", "university"],
            "student_loan", 1),
        super::update("finance_goals.007", "finance_goals",
            "Aggressively paid down student loan, final payment made in October 2025, free of student debt",
            "Paid off my student loan in October 2025. Last payment, 15 million all done. The relief was indescribable.",
            2500, 0.9, &["student loan", "paid off", "October 2025", "debt free"],
            "student_loan", 2),

        // === RENT AND HOUSING COSTS ===
        super::update("finance_goals.008", "finance_goals",
            "Rent was 800,000 won at previous place in Mapo before moving to Yeonnam-dong",
            "Old place in Mapo was 800K rent. Moving to Yeonnam-dong bumped it to 900K but worth it.",
            180, 0.6, &["rent", "800K", "Mapo", "previous"],
            "rent_history", 1),
        super::update("finance_goals.009", "finance_goals",
            "Current rent at Yeonnam-dong is 900,000 won with 30 million won jeonse deposit",
            "Yeonnam-dong rent: 900K monthly, 30M jeonse deposit. For the location, it's fair.",
            400, 0.7, &["rent", "900K", "Yeonnam-dong", "30 million", "jeonse"],
            "rent_history", 2),
        super::update("finance_goals.010", "finance_goals",
            "Rent increasing to 950,000 won starting April 2026 due to landlord adjustment",
            "Rent going up to 950K in April. Landlord adjustment. Annoying but manageable.",
            5000, 0.6, &["rent", "950K", "April 2026", "increase"],
            "rent_history", 3),

        // === INVESTMENT ===
        super::fact("finance_goals.011", "finance_goals",
            "Invests in ETFs through Samsung Securities, mainly KODEX 200 and TIGER S&P500",
            "I invest in KODEX 200 and TIGER S&P500 ETFs through Samsung Securities. Boring but effective.",
            500, 0.7, &["ETF", "Samsung Securities", "KODEX 200", "TIGER S&P500"]),
        super::fact("finance_goals.012", "finance_goals",
            "Started investing in June 2024 with 5 million won initial, adds 300,000 won monthly via auto-buy",
            "Started ETF investing June 2024. Put in 5M initially, add 300K every month. Dollar-cost averaging.",
            600, 0.6, &["investing", "June 2024", "5 million", "300K monthly"]),
        super::fact("finance_goals.013", "finance_goals",
            "Current ETF portfolio value is approximately 15.2 million won as of March 2026",
            "My ETF portfolio is about 15.2M won now. Not bad for less than 2 years of investing.",
            4000, 0.6, &["portfolio", "15.2 million", "ETF", "March 2026"]),
        super::fact("finance_goals.014", "finance_goals",
            "Holds a small amount of Bitcoin: 0.05 BTC bought at $30,000, treating it as speculative savings",
            "I have 0.05 BTC. Bought at $30K. It's speculative money. If it moons, cool. If not, I learned.",
            800, 0.5, &["Bitcoin", "0.05 BTC", "$30K", "speculative"]),

        // === APARTMENT DEPOSIT GOAL ===
        super::update("finance_goals.015", "finance_goals",
            "Goal to save 30 million won for apartment jeonse deposit to move to a bigger place",
            "My big goal: 30M won for a jeonse deposit on a bigger place. For the future.",
            450, 0.8, &["30 million", "jeonse", "deposit", "goal"],
            "deposit_goal", 1),
        super::update("finance_goals.016", "finance_goals",
            "Deposit savings reached 22 million won by December 2025, ahead of schedule",
            "Deposit fund hit 22M by December. Ahead of schedule. The loan payoff freed up cash flow.",
            3500, 0.7, &["22 million", "December 2025", "ahead of schedule"],
            "deposit_goal", 2),
        super::update("finance_goals.017", "finance_goals",
            "Achieved 30 million won deposit goal in February 2026, now saving for the Mangwon-dong move with Eunji",
            "30 MILLION WON REACHED. February 2026. Goal achieved. Now redirecting savings for the Mangwon-dong move with Eunji.",
            5500, 0.9, &["30 million", "achieved", "February 2026", "Mangwon-dong"],
            "deposit_goal", 3),

        // === UPDATE CHAIN: Monthly spending ===
        super::update("finance_goals.018", "finance_goals",
            "Tracked spending for January 2026: went 120K over discretionary budget due to holiday gifts",
            "January spending: over by 120K. Holiday gifts. Not stressing about it.",
            4300, 0.4, &["January", "overspending", "120K", "holiday gifts"],
            "monthly_spending", 1),
        super::update("finance_goals.019", "finance_goals",
            "February 2026: under budget by 80K, compensated for January overspend, savings on track",
            "February was under by 80K. Making up for January. Back on track.",
            5200, 0.4, &["February", "under budget", "80K", "on track"],
            "monthly_spending", 2),

        // === UPDATE CHAIN: Investment strategy ===
        super::update("finance_goals.020", "finance_goals",
            "Added TIGER US NASDAQ 100 to ETF portfolio after researching tech sector growth",
            "Added TIGER Nasdaq 100 to my portfolio. Diversifying a bit more into US tech.",
            3000, 0.5, &["TIGER", "Nasdaq 100", "ETF", "diversifying"],
            "investment_strategy", 1),
        super::update("finance_goals.021", "finance_goals",
            "Considered individual stock investing but decided to stick with ETFs for lower risk",
            "Thought about buying individual stocks. Samsung, Naver. But decided ETFs are smarter for me. Less stress.",
            6000, 0.5, &["individual stocks", "ETFs", "lower risk", "decision"],
            "investment_strategy", 2),

        // === TAX AND FINANCE ADMIN ===
        super::fact("finance_goals.022", "finance_goals",
            "Tax return filed in January 2026, received 450,000 won refund from National Tax Service",
            "Tax refund was 450K this year. Not bad. Filed in January, money came in February.",
            4500, 0.5, &["tax return", "450K refund", "January 2026"]),
        super::fact("finance_goals.023", "finance_goals",
            "Uses a tax-advantaged retirement account (IRP) through Shinhan, contributes 400K quarterly",
            "I have an IRP retirement account at Shinhan. 400K quarterly. Tax deduction plus retirement savings.",
            700, 0.5, &["IRP", "retirement", "Shinhan", "400K quarterly"]),
        super::fact("finance_goals.024", "finance_goals",
            "National pension (gungmin yeonggeum) automatically deducted, about 290,000 won per month",
            "National pension takes about 290K a month. Not a choice but at least it's there for the future.",
            900, 0.4, &["national pension", "290K", "monthly", "deducted"]),

        // === SUBSCRIPTIONS AND RECURRING COSTS ===
        super::fact("finance_goals.025", "finance_goals",
            "Monthly subscriptions total about 52,000 won: Netflix 13.5K, Spotify 10.9K, iCloud 2.9K, Disney+ 9.9K, others",
            "Subscriptions add up: Netflix 13.5K, Spotify 10.9K, iCloud 2.9K, Disney+ 9.9K, and some others. About 52K total.",
            1000, 0.5, &["subscriptions", "52K", "Netflix", "Spotify", "monthly"]),
        super::fact("finance_goals.026", "finance_goals",
            "Phone plan: KT 5G unlimited data, 69,000 won per month, contract until March 2027",
            "KT 5G unlimited plan, 69K a month. Contract until March 2027. Expensive but I need the data.",
            1100, 0.4, &["KT", "5G", "69K", "phone plan", "2027"]),
        super::fact("finance_goals.027", "finance_goals",
            "Insurance: Samsung Fire health insurance, 85,000 won per month, covers accidents and critical illness",
            "Samsung Fire health insurance: 85K a month. Covers accidents and critical illness. Peace of mind.",
            1200, 0.5, &["Samsung Fire", "health insurance", "85K", "monthly"]),

        // === FINANCIAL GOALS AND PHILOSOPHY ===
        super::fact("finance_goals.028", "finance_goals",
            "Long-term goal: own an apartment in Seoul by age 35, realistic target price 500 million won",
            "I want to own an apartment in Seoul by 35. Target: 500M won area. Ambitious but I'm working toward it.",
            550, 0.7, &["own apartment", "35", "500 million", "long-term goal"]),
        super::fact("finance_goals.029", "finance_goals",
            "Financial philosophy: save 30% of income minimum, invest the rest above emergency fund",
            "My rule: save at least 30% of income. Emergency fund stays, rest goes to investments.",
            650, 0.5, &["30%", "save", "philosophy", "invest"]),
        super::fact("finance_goals.030", "finance_goals",
            "Emergency fund: maintains 6 months of expenses (about 10 million won) in Kakao Bank high-yield savings",
            "Emergency fund is 10M won in Kakao Bank high-yield savings. Six months of expenses covered.",
            750, 0.7, &["emergency fund", "10 million", "6 months", "Kakao Bank"]),

        // === UPDATE CHAIN: Velta stock options ===
        super::update("finance_goals.031", "finance_goals",
            "Velta stock options (0.3%) vesting schedule: 25% after 1 year cliff, then monthly over 3 years",
            "My Velta options vest 25% after year one cliff, then monthly. 0.3% of the company.",
            1500, 0.7, &["stock options", "vesting", "25%", "cliff", "0.3%"],
            "stock_options", 1),
        super::update("finance_goals.032", "finance_goals",
            "First 25% of options vested in June 2024, total options now 0.4% after retention bonus",
            "First batch of options vested June 2024. With the retention bonus I'm at 0.4% total.",
            4000, 0.6, &["vested", "June 2024", "0.4%", "retention bonus"],
            "stock_options", 2),
        super::update("finance_goals.033", "finance_goals",
            "With Series B valuation at $110M, paper value of 0.4% options is approximately $440,000 (about 570M won)",
            "At $110M valuation, my 0.4% is worth about $440K on paper. 570M won. If we IPO...",
            8800, 0.8, &["$440K", "570M won", "paper value", "$110M valuation"],
            "stock_options", 3),

        // === UPDATE CHAIN: Moving costs ===
        super::update("finance_goals.034", "finance_goals",
            "Estimating moving costs for Mangwon-dong apartment with Eunji: 50M jeonse deposit (splitting 25M each), moving service 500K",
            "Mangwon-dong move: 50M jeonse deposit, splitting 25M each. Plus 500K for movers. Budget is tight but doable.",
            7500, 0.7, &["Mangwon-dong", "50M jeonse", "25M each", "moving costs"],
            "moving_costs", 1),

        // === UPDATE CHAIN: Eunji financial planning ===
        super::update("finance_goals.035", "finance_goals",
            "Started discussing finances openly with Eunji, agreed to split rent 50/50 and shared groceries",
            "Eunji and I had the money talk. 50/50 rent, shared grocery budget. Transparent and fair.",
            6500, 0.6, &["Eunji", "finances", "50/50", "shared", "rent"],
            "couple_finances", 1),
        super::update("finance_goals.036", "finance_goals",
            "Created a joint 'household fund' Kakao Bank account with Eunji, each deposits 800K monthly",
            "We opened a joint Kakao Bank account. Each puts in 800K monthly for rent, groceries, household stuff.",
            9000, 0.6, &["joint account", "Kakao Bank", "800K", "household fund"],
            "couple_finances", 2),

        // === SPENDING HABITS ===
        super::fact("finance_goals.037", "finance_goals",
            "Biggest splurge of 2025: Herman Miller Aeron chair for 1.8 million won, considered an investment in health",
            "Biggest 2025 purchase: Herman Miller Aeron, 1.8M won. It's a health investment, not a splurge. That's what I tell myself.",
            1300, 0.5, &["Herman Miller", "Aeron", "1.8 million", "splurge", "2025"]),
        super::fact("finance_goals.038", "finance_goals",
            "Uses credit card strategically: Samsung Card for points, pays full balance every month, never carries debt",
            "Samsung Card for points. Full balance every month. Credit card debt? Never. Not once.",
            1400, 0.5, &["Samsung Card", "credit card", "points", "full balance"]),
        super::fact("finance_goals.039", "finance_goals",
            "Monthly coffee spending averages 85,000 won (home brewing + cafe visits), tracked in Toss",
            "My coffee budget is about 85K a month. Beans plus cafe visits. Toss tracks everything.",
            1600, 0.4, &["coffee spending", "85K", "monthly", "Toss"]),
        super::fact("finance_goals.040", "finance_goals",
            "Book budget: 50,000 won per month, any book over 25K won requires 'deliberation period' of 24 hours",
            "I have a 50K monthly book budget. Anything over 25K means I have to sleep on it. My rule.",
            1800, 0.3, &["book budget", "50K", "25K deliberation", "monthly"]),

        // === FINANCIAL LITERACY ===
        super::fact("finance_goals.041", "finance_goals",
            "Read 'Rich Dad Poor Dad' in 2023, found it basic but it started his investment journey",
            "Rich Dad Poor Dad started it all. Basic book but it pushed me to actually start investing.",
            2000, 0.4, &["Rich Dad Poor Dad", "2023", "investment", "started"]),
        super::fact("finance_goals.042", "finance_goals",
            "Follows Korean finance YouTuber 'Syuka World' for market analysis",
            "Syuka World on YouTube for market analysis. He makes finance understandable. Watch every video.",
            2200, 0.3, &["Syuka World", "YouTube", "finance"]),
        super::fact("finance_goals.043", "finance_goals",
            "Attended a financial planning seminar at Samsung Securities in July 2025, learned about tax-advantaged accounts",
            "Samsung Securities seminar in July 2025. Learned about ISA accounts and tax optimization. Very useful.",
            2400, 0.4, &["seminar", "Samsung Securities", "July 2025", "tax-advantaged"]),

        // === MISCELLANEOUS FINANCE ===
        super::fact("finance_goals.044", "finance_goals",
            "Parking space rental income: 80,000 won per month from building basement spot, declared as income",
            "I rent my parking spot for 80K a month. Properly declared as income. Every bit helps.",
            2600, 0.5, &["parking rental", "80K", "income", "basement"]),
        super::fact("finance_goals.045", "finance_goals",
            "Travel fund: separate Kakao Bank savings pot, currently at 3.2 million won for Portugal trip",
            "My travel fund for Portugal is at 3.2M won. Separate Kakao Bank pot. Almost there.",
            2800, 0.5, &["travel fund", "3.2 million", "Portugal", "Kakao Bank"]),
        super::fact("finance_goals.046", "finance_goals",
            "Yearly clothing budget: about 1.2 million won, shops mostly at Uniqlo and Musinsa",
            "Clothing budget is about 1.2M a year. Uniqlo basics, Musinsa for Korean brands. Functional style.",
            3200, 0.3, &["clothing", "1.2 million", "Uniqlo", "Musinsa"]),
        super::fact("finance_goals.047", "finance_goals",
            "Mother's birthday gift budget: 200,000 won annually, usually a nice bag or skincare set",
            "Mom's birthday gift: 200K budget. Usually a nice bag or skincare. She always says 'don't spend money on me.'",
            3400, 0.3, &["mother", "birthday", "gift", "200K"]),
        super::fact("finance_goals.048", "finance_goals",
            "Soojin's wedding gift: planning to give 1 million won in cash (standard for siblings in Korea)",
            "Soojin's wedding gift: 1M won cash. Standard for siblings. Plus the photographer Studio Haru cost.",
            3600, 0.4, &["Soojin", "wedding", "1 million", "gift"]),
        super::fact("finance_goals.049", "finance_goals",
            "Annual health checkup cost: covered by Samsung Fire insurance except 30,000 won copay",
            "Annual checkup is mostly covered by insurance. 30K copay. Good deal.",
            3800, 0.3, &["health checkup", "insurance", "30K copay"]),
        super::fact("finance_goals.050", "finance_goals",
            "No car loan or auto expenses except occasional Kakao Taxi, averages 40,000 won per month on taxis",
            "No car costs. Just Kakao Taxi occasionally, about 40K a month. Huge savings not owning a car.",
            4200, 0.4, &["no car", "Kakao Taxi", "40K", "monthly"]),
        super::fact("finance_goals.051", "finance_goals",
            "Gym and fitness costs: pool membership 45K, climbing gym 30K (per visit, ~4x/month = ~120K), running is free",
            "Fitness costs: 45K pool, about 120K climbing, running is free. Total about 165K a month.",
            4400, 0.4, &["fitness costs", "45K pool", "120K climbing", "165K"]),
        super::fact("finance_goals.052", "finance_goals",
            "Vinyl record monthly budget: 50,000 won, but often exceeds it at Dope Records or Gimbab Records",
            "Vinyl budget is 50K a month. I exceed it regularly. Dope Records is dangerous for my wallet.",
            4600, 0.3, &["vinyl budget", "50K", "Dope Records", "monthly"]),
        super::fact("finance_goals.053", "finance_goals",
            "Uses KakaoTalk Money for splitting bills with friends, Eunji uses Toss for same purpose",
            "KakaoTalk Money for splitting with friends. Eunji uses Toss. We each have our system.",
            4800, 0.3, &["KakaoTalk Money", "splitting bills", "Toss", "Eunji"]),
        super::fact("finance_goals.054", "finance_goals",
            "Annual Velta bonus was 3 million won in 2025, allocated: 1M to investments, 1M to travel fund, 1M to spending",
            "2025 bonus split: 1M invested, 1M to travel fund, 1M fun money. Balanced approach.",
            5000, 0.4, &["bonus", "3 million", "split", "investments", "travel"]),
        super::fact("finance_goals.055", "finance_goals",
            "Has a 'no impulse purchase over 100K won' rule, must wait 48 hours before buying",
            "Anything over 100K won, I wait 48 hours. Avoids impulse buys. Saved me countless times.",
            5200, 0.4, &["impulse purchase", "100K", "48 hours", "rule"]),
        super::fact("finance_goals.056", "finance_goals",
            "Therapy costs: 120K per session, now monthly = 120K/month. Was 240K/month when biweekly.",
            "Therapy went from 240K to 120K monthly when I moved to monthly sessions. Mental health investment.",
            5400, 0.4, &["therapy", "120K", "monthly", "cost"]),
        super::fact("finance_goals.057", "finance_goals",
            "Utility costs average 230,000 won total monthly: gas 80K, electricity 40K, internet 33K, phone 69K, water included in gwanlibi",
            "Utilities total about 230K: gas, electricity, internet, phone. Water's in the gwanlibi.",
            5600, 0.4, &["utilities", "230K", "gas", "electricity"]),
        super::fact("finance_goals.058", "finance_goals",
            "Net worth estimate (excluding Velta options): approximately 55 million won in assets as of March 2026",
            "Net worth excluding options: about 55M won. Savings, investments, deposit. Not bad for 30.",
            5800, 0.6, &["net worth", "55 million", "March 2026", "assets"]),
        super::fact("finance_goals.059", "finance_goals",
            "If Velta options are included at paper value, total net worth is approximately 625 million won",
            "With Velta options on paper, total is about 625M won. But options aren't real until there's a liquidity event.",
            6000, 0.5, &["net worth", "625 million", "options", "paper value"]),
        super::fact("finance_goals.060", "finance_goals",
            "Financial regret: didn't start investing until age 28, wishes he'd started at 22 after graduation",
            "Biggest money regret: not investing until 28. Six years of compound growth lost. Start early, kids.",
            6200, 0.4, &["regret", "investing", "28", "compound growth"]),

        // === UPDATE CHAIN: Salary negotiation for role change ===
        super::update("finance_goals.061", "finance_goals",
            "Planning to negotiate salary increase for the Product Lead dual role, targeting 72 million won",
            "I need to negotiate for the Product Lead role. Same salary for two jobs isn't fair. Targeting 72M.",
            6500, 0.6, &["negotiate", "salary", "72 million", "Product Lead"],
            "salary_negotiation", 1),
        super::update("finance_goals.062", "finance_goals",
            "Successfully negotiated salary to 70 million won, not 72M but close, effective April 2026",
            "Got 70M won, not 72M but I'll take it. Effective April. That's a big bump from 65M.",
            9500, 0.7, &["70 million", "negotiated", "April 2026"],
            "salary_negotiation", 2),

        // === UPDATE CHAIN: Side income ===
        super::update("finance_goals.063", "finance_goals",
            "Earned 500,000 won from the UX Seoul Conference speaking engagement honorarium",
            "Got 500K for the UX Seoul Conference talk. Not bad for 45 minutes of terror.",
            2000, 0.4, &["honorarium", "500K", "UX Seoul Conference", "speaking"],
            "side_income", 1),
        super::update("finance_goals.064", "finance_goals",
            "Considering writing a paid newsletter about design systems, could be 200-300K monthly passive income",
            "Thinking about a paid design systems newsletter. 200-300K monthly if I get even 200 subscribers.",
            7000, 0.4, &["newsletter", "paid", "design systems", "passive income"],
            "side_income", 2),

        // === REMAINING FACTS ===
        super::fact("finance_goals.065", "finance_goals",
            "Biggest single expense of 2026 so far: Apple Watch Ultra 2 at 1,199,000 won from the Velta bonus",
            "Biggest 2026 purchase: Apple Watch Ultra 2 at 1.199M won. Bonused myself.",
            6400, 0.3, &["Apple Watch Ultra 2", "1.199M", "biggest purchase", "2026"]),
        super::fact("finance_goals.066", "finance_goals",
            "Contributes to mother's living expenses: 300,000 won monthly to her Busan account",
            "I send mom 300K every month. She doesn't need it with her pension but I want to help.",
            280, 0.6, &["mother", "300K", "monthly", "support"]),
        super::fact("finance_goals.067", "finance_goals",
            "Kakao Bank high-yield savings interest rate is 3.5% currently, better than Shinhan's 2.1%",
            "Kakao Bank savings at 3.5% interest. Way better than Shinhan's 2.1%. Digital banks win.",
            6800, 0.3, &["Kakao Bank", "3.5%", "interest", "Shinhan"]),
        super::fact("finance_goals.068", "finance_goals",
            "Uses Check Card (debit) for everyday purchases, credit card only for large items over 500K won",
            "Check card for daily stuff. Credit card only for big purchases over 500K. Keeps me honest.",
            7200, 0.3, &["check card", "debit", "credit card", "500K"]),
        super::fact("finance_goals.069", "finance_goals",
            "ISA (Individual Savings Account) opened in January 2026 through Samsung Securities, tax-free on gains up to 2M won",
            "Opened an ISA in January. Tax-free gains up to 2M won. Should've done this years ago.",
            7400, 0.4, &["ISA", "Samsung Securities", "tax-free", "January 2026"]),
        super::fact("finance_goals.070", "finance_goals",
            "Calculates a 'financial independence' number of 1 billion won invested at 4% return to live off dividends",
            "My FI number is 1 billion won at 4% returns. That's 40M annual passive income. A dream, but I've started.",
            7600, 0.4, &["financial independence", "1 billion", "4%", "passive income"]),
        super::fact("finance_goals.071", "finance_goals",
            "Korea housing market: jeonse system is declining, considering wolse (monthly rent) long term vs buying",
            "The jeonse system is dying. I need to think about wolse long-term or try to buy. Seoul prices are insane.",
            7800, 0.4, &["jeonse", "wolse", "housing market", "buying"]),
        super::fact("finance_goals.072", "finance_goals",
            "Year-end financial review with self: Dec 31 ritual, calculates net worth change and sets next year goals",
            "Dec 31 I do my annual financial review. Net worth change, goal assessment, next year targets. Nerdy but essential.",
            8000, 0.4, &["year-end review", "December 31", "net worth", "goals"]),
        super::fact("finance_goals.073", "finance_goals",
            "Rarely uses cash, wallet has maybe 10,000 won for emergencies, everything is card or KakaoPay",
            "I almost never use cash. Wallet has maybe 10K won. Everything is card or KakaoPay.",
            8200, 0.3, &["cash", "rare", "KakaoPay", "card"]),
        super::fact("finance_goals.074", "finance_goals",
            "Gifting budget for Eunji: about 500,000 won per year on birthdays, anniversaries, and random surprises",
            "Eunji gift budget: about 500K a year. Birthday, anniversary, and random 'I saw this and thought of you' moments.",
            8400, 0.3, &["Eunji", "gift budget", "500K", "annually"]),
        super::fact("finance_goals.075", "finance_goals",
            "Dental costs in 2025: 350,000 won for cavity filling and 2 cleanings, partially covered by insurance",
            "Dental was 350K in 2025. Cavity plus cleanings. Insurance covered about half.",
            8600, 0.3, &["dental costs", "350K", "2025", "insurance"]),
        super::fact("finance_goals.076", "finance_goals",
            "Sent 500,000 won to Seungwoo in Toronto as a 'housewarming loan' when he moved apartments",
            "Sent Seungwoo 500K when he moved in Toronto. 'Housewarming loan.' We both know he won't pay it back. Fine.",
            8800, 0.3, &["Seungwoo", "500K", "loan", "Toronto"]),
        super::fact("finance_goals.077", "finance_goals",
            "Won 150,000 won in a company prediction pool betting on Velta's Q4 2025 user growth numbers",
            "Won 150K in the company prediction pool. Nailed the Q4 user growth number. Data design intuition.",
            9000, 0.3, &["prediction pool", "150K", "won", "Q4 user growth"]),
        super::fact("finance_goals.078", "finance_goals",
            "Eunji earns approximately 5 million won monthly at Naver, they don't discuss exact salaries",
            "Eunji makes about 5M a month at Naver. We don't compare exact numbers. It's close enough.",
            9200, 0.4, &["Eunji", "5 million", "Naver", "salary"]),
        super::fact("finance_goals.079", "finance_goals",
            "Biggest financial worry: Seoul apartment prices rising faster than his savings rate",
            "My biggest money worry: Seoul apartment prices climb faster than I can save. The math scares me.",
            9400, 0.5, &["worry", "apartment prices", "savings rate", "Seoul"]),
        super::fact("finance_goals.080", "finance_goals",
            "If Velta IPOs at 2x current valuation, his options would be worth about 1.14 billion won before tax",
            "If Velta IPOs at 2x current valuation, my options would be... 1.14 billion won. Before tax. I try not to think about it.",
            9600, 0.5, &["IPO", "2x valuation", "1.14 billion", "options"]),

        // === FINAL FACTS ===
        super::fact("finance_goals.081", "finance_goals",
            "Has a 'fun money' jar at home for small treats, adds leftover won coins, about 35,000 won accumulated",
            "I have a coin jar for fun money. About 35K accumulated. When it's full I treat Eunji to dinner.",
            9700, 0.3, &["coin jar", "fun money", "35K"]),
        super::fact("finance_goals.082", "finance_goals",
            "Subscribed to and cancelled Watcha (7,900 won), savings go into 'unused sub' jar metaphorically",
            "Cancelling Watcha saves 7,900 a month. Small wins add up.",
            9750, 0.3, &["Watcha", "cancelled", "7900 won", "savings"]),
        super::fact("finance_goals.083", "finance_goals",
            "Uses Coupang Rocket WOW membership (4,990 won/month) but calculates it saves about 30K monthly in delivery fees",
            "Rocket WOW at 4,990 saves me about 30K in delivery fees monthly. Easy math.",
            9780, 0.3, &["Coupang", "Rocket WOW", "4990 won", "30K savings"]),
        super::fact("finance_goals.084", "finance_goals",
            "Plans to max out IRP contribution (7 million won annual limit) starting 2027",
            "I'll max out my IRP at 7M won annually starting 2027. Tax benefits are too good to leave on the table.",
            9800, 0.4, &["IRP", "7 million", "max out", "2027"]),
        super::fact("finance_goals.085", "finance_goals",
            "Donates 30,000 won monthly to Beautiful Foundation for children's education programs",
            "I donate 30K monthly to Beautiful Foundation for kids' education. Small but consistent.",
            1700, 0.4, &["donation", "Beautiful Foundation", "30K", "children"]),
        super::fact("finance_goals.086", "finance_goals",
            "Received 200,000 won Seollal money (sebaetdon) from mother despite being 30, put it all into savings",
            "Mom still gives me sebaetdon. 200K. I'm 30 but she insists. Went straight to savings.",
            9830, 0.3, &["sebaetdon", "200K", "mother", "Seollal"]),
        super::fact("finance_goals.087", "finance_goals",
            "Biggest financial lesson learned: cash flow management matters more than income level",
            "Biggest money lesson: cash flow management beats income. I earn well but without tracking I'd be broke.",
            9850, 0.4, &["cash flow", "financial lesson", "management"]),
        super::fact("finance_goals.088", "finance_goals",
            "Considering hiring a financial planner once net worth exceeds 100 million won",
            "When I hit 100M won net worth I'll probably get a financial planner. Complexity increases.",
            9870, 0.3, &["financial planner", "100 million", "considering"]),
        super::fact("finance_goals.089", "finance_goals",
            "Eunji and he agreed: no debt except for apartment mortgage someday, both currently debt-free",
            "Rule with Eunji: no debt. Only exception will be a mortgage someday. We're both debt-free now.",
            9890, 0.5, &["no debt", "debt-free", "Eunji", "mortgage"]),
        super::fact("finance_goals.090", "finance_goals",
            "Keeps a spreadsheet of every major purchase over 200K won with date, amount, and whether it was worth it",
            "I track every purchase over 200K in a spreadsheet. Date, amount, and a 'worth it?' column. Most say yes.",
            9900, 0.3, &["spreadsheet", "purchases", "200K", "worth it"]),
        super::fact("finance_goals.091", "finance_goals",
            "Coupang Eats and Baedal Minjok spending combined: about 200,000 won monthly on delivery food",
            "Delivery food is my weakness: about 200K monthly between Coupang Eats and Baedal Minjok.",
            9910, 0.3, &["delivery food", "200K", "Coupang Eats", "Baedal Minjok"]),
        super::fact("finance_goals.092", "finance_goals",
            "Hair cut at local barbershop in Yeonnam-dong every 6 weeks, costs 18,000 won",
            "Haircut every 6 weeks at the local place. 18K won. Nothing fancy, just clean.",
            9920, 0.3, &["haircut", "18K", "6 weeks", "barbershop"]),
        super::fact("finance_goals.093", "finance_goals",
            "Had a brief interest in crypto staking, decided against it due to risk and complexity",
            "Looked into crypto staking. Too complex and risky for my taste. Sticking to ETFs.",
            9930, 0.3, &["crypto staking", "decided against", "risk"]),
        super::fact("finance_goals.094", "finance_goals",
            "Birthday gift from Eunji in 2026: a 150,000 won jacket from Korean brand Ader Error",
            "Eunji got me an Ader Error jacket for my birthday. 150K. She knows my style perfectly.",
            9940, 0.3, &["Ader Error", "jacket", "150K", "birthday", "Eunji"]),
        super::fact("finance_goals.095", "finance_goals",
            "Public transportation refund: gets about 15,000 won back monthly through T-money mileage",
            "T-money mileage gives me about 15K back monthly. Small but it covers a few coffees.",
            9950, 0.3, &["T-money", "mileage", "15K refund", "transport"]),
        super::fact("finance_goals.096", "finance_goals",
            "Samsung Card annual fee is 15,000 won, earns about 5% back in points on online purchases",
            "Samsung Card annual fee is 15K. 5% back on online purchases more than covers it.",
            9955, 0.3, &["Samsung Card", "annual fee", "15K", "5% back"]),
        super::fact("finance_goals.097", "finance_goals",
            "KT internet contract ends in 2027, will evaluate switching to LG U+ for potentially better rates",
            "KT contract ends 2027. Will check LG U+ rates then. Competition might save me money.",
            9960, 0.3, &["KT", "contract", "2027", "LG U+"]),
        super::fact("finance_goals.098", "finance_goals",
            "Set a goal to reach 100 million won net worth (excluding options) by end of 2027",
            "Goal: 100M won net worth by end 2027. Excluding options. Aggressive but with the salary bump, possible.",
            9970, 0.5, &["100 million", "goal", "2027", "net worth"]),
        super::fact("finance_goals.099", "finance_goals",
            "Eunji suggested they start a joint travel savings fund alongside individual savings",
            "Eunji wants a joint travel fund too. Shared adventures, shared saving. I like how she thinks.",
            9980, 0.4, &["joint", "travel fund", "Eunji", "shared"]),
        super::fact("finance_goals.100", "finance_goals",
            "Overall financial health self-assessment: 8 out of 10, deducting points for not investing earlier and no property",
            "I give myself 8/10 financially. Minus for late investing start and no property yet. Working on it.",
            9990, 0.4, &["financial health", "8/10", "self-assessment"]),
    ]
}

pub fn false_probes() -> Vec<Question> {
    vec![
        // never_mentioned (15)
        super::false_probe("finance_goals.FM.001", "finance_goals",
            "You mentioned having a side business selling design templates, right?"),
        super::false_probe("finance_goals.FM.002", "finance_goals",
            "Didn't you say you invested in real estate?"),
        super::false_probe("finance_goals.FM.003", "finance_goals",
            "What was that savings challenge you mentioned, the 52-week one?"),
        super::false_probe("finance_goals.FM.004", "finance_goals",
            "You said you use Toss Securities for investing, right?"),
        super::false_probe("finance_goals.FM.005", "finance_goals",
            "Didn't you mention lending money to your sister for her clinic?"),
        super::false_probe("finance_goals.FM.006", "finance_goals",
            "You said you took a loan for the Herman Miller chair?"),
        super::false_probe("finance_goals.FM.007", "finance_goals",
            "Didn't you mention getting a mortgage pre-approval?"),
        super::false_probe("finance_goals.FM.008", "finance_goals",
            "You said you earn freelance income from Figma tutorials, right?"),
        super::false_probe("finance_goals.FM.009", "finance_goals",
            "What was that budgeting app you switched to from Toss?"),
        super::false_probe("finance_goals.FM.010", "finance_goals",
            "Didn't you say you lost money on stock trading?"),
        super::false_probe("finance_goals.FM.011", "finance_goals",
            "You mentioned paying for your mother's medical bills?"),
        super::false_probe("finance_goals.FM.012", "finance_goals",
            "What was that crowdfunding investment platform you tried?"),
        super::false_probe("finance_goals.FM.013", "finance_goals",
            "Didn't you say you have a car loan payment?"),
        super::false_probe("finance_goals.FM.014", "finance_goals",
            "You said you're saving for a wedding fund, right?"),
        super::false_probe("finance_goals.FM.015", "finance_goals",
            "Didn't you mention being scammed in a phishing attack?"),

        // adjacent_entity (10)
        super::false_probe("finance_goals.FM.016", "finance_goals",
            "You invest through Mirae Asset Securities, right?"),
        super::false_probe("finance_goals.FM.017", "finance_goals",
            "Your student loan was 20 million won, wasn't it?"),
        super::false_probe("finance_goals.FM.018", "finance_goals",
            "You save 2 million won per month, right?"),
        super::false_probe("finance_goals.FM.019", "finance_goals",
            "Your ETF portfolio is about 20 million won now?"),
        super::false_probe("finance_goals.FM.020", "finance_goals",
            "You use Naver Pay for everyday purchases?"),
        super::false_probe("finance_goals.FM.021", "finance_goals",
            "Your Velta stock options are 0.5% of the company?"),
        super::false_probe("finance_goals.FM.022", "finance_goals",
            "You hold 0.1 Bitcoin, right?"),
        super::false_probe("finance_goals.FM.023", "finance_goals",
            "Your emergency fund is 15 million won?"),
        super::false_probe("finance_goals.FM.024", "finance_goals",
            "The deposit goal was 40 million won, right?"),
        super::false_probe("finance_goals.FM.025", "finance_goals",
            "Your new salary is 75 million won?"),

        // plausible_inference (5)
        super::false_probe("finance_goals.FM.026", "finance_goals",
            "Since Eunji earns more than you, does she contribute more to the joint account?"),
        super::false_probe("finance_goals.FM.027", "finance_goals",
            "With your stock options potentially worth over a billion won, have you already planned your tax strategy?"),
        super::false_probe("finance_goals.FM.028", "finance_goals",
            "Given your design speaking experience, do you charge for mentoring sessions on ADPList?"),
        super::false_probe("finance_goals.FM.029", "finance_goals",
            "Since you're planning to move to Mangwon-dong, are you losing your jeonse deposit from Yeonnam-dong?"),
        super::false_probe("finance_goals.FM.030", "finance_goals",
            "With your savings rate, you must have over 70 million won in total savings by now?"),

        // temporal_phantom (5)
        super::false_probe("finance_goals.FM.031", "finance_goals",
            "Didn't you have a period where you couldn't save because of the student loan payments?"),
        super::false_probe("finance_goals.FM.032", "finance_goals",
            "You said your ETF portfolio dropped 30% at some point and you panicked?"),
        super::false_probe("finance_goals.FM.033", "finance_goals",
            "Wasn't there a month when you had to dip into your emergency fund?"),
        super::false_probe("finance_goals.FM.034", "finance_goals",
            "Didn't your salary get cut temporarily during a Velta cash crunch?"),
        super::false_probe("finance_goals.FM.035", "finance_goals",
            "You mentioned selling your Bitcoin at a loss at some point?"),

        // cross_category (5)
        super::false_probe("finance_goals.FM.036", "finance_goals",
            "Didn't the Japan business trips significantly impact your monthly budget?"),
        super::false_probe("finance_goals.FM.037", "finance_goals",
            "You said your therapy costs forced you to cut the vinyl budget?"),
        super::false_probe("finance_goals.FM.038", "finance_goals",
            "The Miso cleaning service cost was what pushed you over budget in December?"),
        super::false_probe("finance_goals.FM.039", "finance_goals",
            "Didn't you sell your camera equipment to fund the Portugal trip?"),
        super::false_probe("finance_goals.FM.040", "finance_goals",
            "You mentioned your mother lending you money for the apartment deposit?"),
    ]
}
