use crate::types::{Fact, Question};

pub fn facts() -> Vec<Fact> {
    vec![
        // === BASELINE HEALTH (early turns) ===
        super::fact("health_fitness.001", "health_fitness",
            "Has mild asthma since childhood, diagnosed at age 8 at Busan Paik Hospital",
            "I've had asthma since I was 8. Diagnosed at Busan Paik Hospital. It's mild but it's there.",
            70, 0.9, &["asthma", "childhood", "age 8", "Busan Paik Hospital"]),
        super::fact("health_fitness.002", "health_fitness",
            "Uses a Ventolin inhaler for asthma, keeps one at home and one in work bag at all times",
            "I always have two Ventolin inhalers. One at home, one in my bag. Can't risk being without it.",
            130, 0.8, &["Ventolin", "inhaler", "asthma", "two"]),
        super::fact("health_fitness.003", "health_fitness",
            "Height is 175cm, starting weight in January 2025 was 68kg",
            "I'm 175cm. Started this year at 68kg. Not bad but I wanted to get leaner.",
            160, 0.7, &["175cm", "68kg", "height", "weight"]),
        super::fact("health_fitness.004", "health_fitness",
            "Annual health checkup at Samsung Medical Center, last one was November 2025, all clear except mild vitamin D deficiency",
            "Annual checkup at Samsung Medical Center in November. Everything fine except low vitamin D. Hence the supplements.",
            240, 0.7, &["checkup", "Samsung Medical Center", "November", "vitamin D"]),
        super::fact("health_fitness.005", "health_fitness",
            "Blood type is A+, discovered during a blood donation at university",
            "Blood type A+. Found out when I donated blood at Yonsei freshman year.",
            350, 0.4, &["blood type", "A+", "blood donation", "Yonsei"]),

        // === RUNNING JOURNEY ===
        super::fact("health_fitness.006", "health_fitness",
            "Started running in March 2025, initially 3km along Yeonnam-dong's Gyeongui Line Forest Park",
            "I started running in March along the Gyeongui Line Forest Park near my apartment. Just 3km at first.",
            200, 0.7, &["running", "March 2025", "3km", "Gyeongui Line"]),
        super::fact("health_fitness.007", "health_fitness",
            "Running shoes: Nike Pegasus 41 in black, bought at Nike Hongdae store",
            "Got Nike Pegasus 41 at the Hongdae store. Black, nothing flashy but they feel great.",
            280, 0.4, &["Nike", "Pegasus 41", "running shoes", "Hongdae"]),
        super::fact("health_fitness.008", "health_fitness",
            "Built up to 5km runs by May 2025, running 3 times a week: Monday, Wednesday, Saturday morning",
            "By May I was doing 5km three times a week. Monday, Wednesday, Saturday mornings.",
            500, 0.6, &["5km", "3 times a week", "Monday", "Wednesday", "Saturday"]),
        super::fact("health_fitness.009", "health_fitness",
            "Used Strava app for tracking runs, had a 12-week running streak before the knee injury",
            "Strava was my running diary. Had a 12-week streak going before my knee ruined everything.",
            700, 0.5, &["Strava", "12-week streak", "tracking", "running"]),

        // === KNEE INJURY ===
        super::update("health_fitness.010", "health_fitness",
            "Developed runner's knee (patellofemoral pain syndrome) in right knee in August 2025 after increasing to 8km",
            "I pushed to 8km too fast and got runner's knee in August. Right knee. The pain was sharp going downstairs.",
            1200, 0.8, &["runner's knee", "patellofemoral", "right knee", "August 2025"],
            "knee_injury", 1),
        super::update("health_fitness.011", "health_fitness",
            "Saw an orthopedist Dr. Choi at Severance Hospital, prescribed 6 weeks rest and physical therapy",
            "Dr. Choi at Severance said 6 weeks rest and PT. No running. I was devastated.",
            1400, 0.7, &["Dr. Choi", "Severance Hospital", "6 weeks", "physical therapy"],
            "knee_injury", 2),
        super::update("health_fitness.012", "health_fitness",
            "Completed PT in October 2025, cleared to resume light exercise but advised to avoid running for 2 more months",
            "Finished PT in October. Cleared for light exercise but no running for 2 more months. So I found swimming.",
            1800, 0.6, &["PT completed", "October", "cleared", "no running"],
            "knee_injury", 3),

        // === SWIMMING PHASE ===
        super::update("health_fitness.013", "health_fitness",
            "Started swimming at Mapo District Public Pool, 25m lane pool, goes Monday/Wednesday/Friday at 7 AM",
            "Started swimming at Mapo public pool. 25m lanes, 7 AM, Mon/Wed/Fri. Great cardio without the knee pain.",
            2000, 0.7, &["swimming", "Mapo pool", "25m", "7 AM"],
            "exercise_type", 1),
        super::fact("health_fitness.014", "health_fitness",
            "Swimming membership costs 45,000 won per month at Mapo District Public Pool",
            "Pool membership is 45K a month. Cheap for how much use I get out of it.",
            2100, 0.4, &["swimming", "45K", "membership", "monthly"]),
        super::fact("health_fitness.015", "health_fitness",
            "Learned freestyle properly from a YouTube channel called 'Swim Smooth', previously only knew breaststroke",
            "I only knew breaststroke before. Learned proper freestyle from 'Swim Smooth' on YouTube. Game changer.",
            2300, 0.4, &["freestyle", "Swim Smooth", "YouTube", "breaststroke"]),
        super::fact("health_fitness.016", "health_fitness",
            "Can now swim 1km continuously in about 25 minutes, does 1.5km total per session",
            "I can do 1km non-stop now in about 25 minutes. Usually do 1.5km total per session.",
            2800, 0.5, &["1km", "25 minutes", "1.5km", "swimming"]),

        // === RETURN TO RUNNING ===
        super::update("health_fitness.017", "health_fitness",
            "Started running again in January 2026, slowly with 2km runs, knee feels stable with a compression sleeve",
            "Started running again in January! Just 2km with a knee compression sleeve. Knee feels good.",
            4200, 0.7, &["running again", "January 2026", "2km", "compression sleeve"],
            "exercise_type", 2),
        super::update("health_fitness.018", "health_fitness",
            "Back to 5km runs by March 2026, now alternates running and swimming through the week",
            "I'm back to 5km! Now I alternate: run Tue/Sat, swim Mon/Wed/Fri. Best of both worlds.",
            8000, 0.7, &["5km", "March 2026", "alternate", "running", "swimming"],
            "exercise_type", 3),

        // === WEIGHT JOURNEY ===
        super::update("health_fitness.019", "health_fitness",
            "Weight dropped to 66kg by June 2025 from running, felt lighter and more energetic",
            "Down to 66kg by June. Running really changed my body composition. Feel so much lighter.",
            800, 0.6, &["66kg", "weight loss", "June 2025", "running"],
            "weight_change", 1),
        super::update("health_fitness.020", "health_fitness",
            "Weight went back up to 67kg during knee injury recovery, less active and stress eating",
            "Gained back to 67kg during the knee injury. Less exercise plus stress eating. Not great.",
            1600, 0.5, &["67kg", "gained", "knee injury", "stress eating"],
            "weight_change", 2),
        super::update("health_fitness.021", "health_fitness",
            "Weight reached 64kg by February 2026 with swimming and better diet, lowest since college",
            "64kg as of February! Swimming plus cleaning up my diet. Haven't been this light since college.",
            5500, 0.7, &["64kg", "February 2026", "lowest", "college"],
            "weight_change", 3),

        // === THERAPY WITH DR. PARK ===
        super::fact("health_fitness.022", "health_fitness",
            "Started therapy with Dr. Park Jihwan at Maum Therapy Center in September 2025 for anxiety and work stress",
            "I started seeing Dr. Park at Maum Therapy Center in September. Anxiety and work stress mostly.",
            1500, 0.8, &["Dr. Park", "therapy", "Maum Therapy Center", "September 2025", "anxiety"]),
        super::fact("health_fitness.023", "health_fitness",
            "Therapy sessions are every other Saturday at 10 AM, 50 minutes each, costs 120,000 won per session",
            "I see Dr. Park every other Saturday at 10. 50 minutes, 120K per session. Worth every won.",
            1700, 0.7, &["therapy", "Saturday", "50 minutes", "120K", "biweekly"]),
        super::fact("health_fitness.024", "health_fitness",
            "Dr. Park is a clinical psychologist specializing in CBT (Cognitive Behavioral Therapy)",
            "Dr. Park does CBT, cognitive behavioral therapy. It's practical, which I like.",
            1900, 0.5, &["Dr. Park", "CBT", "clinical psychologist"]),
        super::fact("health_fitness.025", "health_fitness",
            "Therapy helped identify pattern of people-pleasing at work leading to burnout",
            "Dr. Park helped me see I'm a people-pleaser at work. That's a big part of why I burn out.",
            2500, 0.6, &["people-pleasing", "burnout", "therapy", "pattern"]),

        // === 10K RACE ===
        super::update("health_fitness.026", "health_fitness",
            "Registered for Seoul Spring 10K race in April 2026, first competitive run ever",
            "I signed up for the Seoul Spring 10K in April! My first ever race. Training starts now.",
            6000, 0.7, &["Seoul Spring 10K", "April 2026", "race", "first"],
            "10k_race", 1),
        super::update("health_fitness.027", "health_fitness",
            "Following a 10K training plan from a Naver blog, aiming to finish under 55 minutes",
            "I found a 10K plan on a Naver blog. Goal is under 55 minutes. We'll see.",
            7000, 0.6, &["10K training", "Naver blog", "55 minutes", "goal"],
            "10k_race", 2),
        super::update("health_fitness.028", "health_fitness",
            "Completed the Seoul Spring 10K in 53 minutes 22 seconds, emotional at the finish line",
            "I DID IT. 53:22. Under 55 minutes! I actually teared up at the finish line. Best feeling ever.",
            9500, 0.9, &["10K", "53:22", "completed", "finish line"],
            "10k_race", 3),

        // === DIET AND NUTRITION ===
        super::fact("health_fitness.029", "health_fitness",
            "Follows a mostly Korean diet but tries to eat more protein, target 100g per day",
            "I eat mostly Korean food but I try to get 100g of protein daily. Chicken breast is my friend.",
            600, 0.5, &["diet", "Korean", "protein", "100g", "chicken breast"]),
        super::fact("health_fitness.030", "health_fitness",
            "Protein supplement: drinks Optimum Nutrition whey shake after workouts, chocolate flavor",
            "I do a protein shake after workouts. Optimum Nutrition, chocolate. Nothing fancy.",
            900, 0.4, &["protein shake", "Optimum Nutrition", "chocolate", "whey"]),
        super::fact("health_fitness.031", "health_fitness",
            "Lactose intolerant, uses lactose-free milk (Maeil Seoul Milk) and avoids heavy dairy",
            "I'm lactose intolerant. Maeil Seoul Milk's lactose-free version is my go-to. Regular milk is a disaster.",
            400, 0.6, &["lactose intolerant", "Maeil", "lactose-free milk"]),
        super::fact("health_fitness.032", "health_fitness",
            "Meal prep Sundays include: grilled chicken, brown rice, and steamed broccoli for Monday-Tuesday lunches",
            "Sunday meal prep: grilled chicken, brown rice, broccoli. Boring but effective for Mon-Tue lunches.",
            1100, 0.4, &["meal prep", "chicken", "brown rice", "broccoli"]),

        // === MENTAL HEALTH ===
        super::fact("health_fitness.033", "health_fitness",
            "Had a panic attack at work in October 2025 during Series B preparation stress, went to emergency room",
            "I had a panic attack at work in October. Thought it was a heart attack. ER cleared me. That's when I knew I needed therapy.",
            2400, 0.8, &["panic attack", "October 2025", "emergency room", "work stress"]),
        super::fact("health_fitness.034", "health_fitness",
            "Dr. Park taught grounding technique: 5-4-3-2-1 sensory exercise for anxiety moments",
            "Dr. Park taught me the 5-4-3-2-1 grounding thing. Five things you see, four you touch... it actually works.",
            2700, 0.5, &["grounding", "5-4-3-2-1", "anxiety", "Dr. Park"]),
        super::fact("health_fitness.035", "health_fitness",
            "Sleep quality improved after starting therapy, average sleep went from 5.5 to 7 hours per night",
            "My sleep went from 5.5 to 7 hours after therapy started. I didn't realize how sleep deprived I was.",
            3000, 0.6, &["sleep", "5.5 hours", "7 hours", "improved"]),

        // === UPDATE CHAIN: Therapy progress ===
        super::update("health_fitness.036", "health_fitness",
            "Therapy reduced from biweekly to monthly after 6 months of progress, Dr. Park impressed with growth",
            "Dr. Park moved me to monthly sessions. Six months of progress. He said I've done great work.",
            6500, 0.6, &["therapy", "monthly", "6 months", "progress"],
            "therapy_frequency", 1),

        // === BOULDERING ===
        super::fact("health_fitness.037", "health_fitness",
            "Started bouldering in April 2025 at Climbing Park Hongdae with coworker Soyeon",
            "Soyeon dragged me to Climbing Park in Hongdae in April. Bouldering. I was terrible but hooked.",
            550, 0.6, &["bouldering", "April 2025", "Climbing Park", "Soyeon"]),
        super::fact("health_fitness.038", "health_fitness",
            "Current bouldering grade: V3-V4, can flash V3s consistently but V5 is the goal",
            "I flash V3s now and can do most V4s. V5 is my goal. Soyeon's already at V5, she's annoyingly good.",
            1300, 0.5, &["V3", "V4", "V5", "bouldering", "grade"]),

        // === UPDATE CHAIN: Bouldering progression ===
        super::update("health_fitness.039", "health_fitness",
            "Sent first V5 problem at Climbing Park in February 2026 after 10 months of climbing",
            "I SENT MY FIRST V5! Ten months of climbing and I finally did it. Soyeon screamed louder than me.",
            5000, 0.6, &["V5", "first send", "February 2026", "10 months"],
            "bouldering_grade", 1),

        // === ASTHMA MANAGEMENT ===
        super::update("health_fitness.040", "health_fitness",
            "Asthma flared up during spring pollen season in April 2025, had to use inhaler daily for 2 weeks",
            "My asthma went crazy in April with the pollen. Had to use my inhaler every day for two weeks.",
            650, 0.7, &["asthma", "pollen", "April", "daily inhaler"],
            "asthma_management", 1),
        super::update("health_fitness.041", "health_fitness",
            "Pulmonologist at Samsung Medical Center prescribed daily Seretide preventer in addition to Ventolin rescue",
            "My lung doctor added Seretide as a daily preventer on top of the Ventolin. More control, less emergency use.",
            850, 0.6, &["Seretide", "preventer", "pulmonologist", "Samsung Medical"],
            "asthma_management", 2),
        super::update("health_fitness.042", "health_fitness",
            "Asthma well-controlled with Seretide, only needed rescue inhaler twice in last 6 months",
            "Asthma is way better with the Seretide. Only used my rescue inhaler twice in 6 months. Running helps too.",
            4500, 0.5, &["asthma", "well-controlled", "Seretide", "twice"],
            "asthma_management", 3),

        // === DENTAL AND VISION ===
        super::fact("health_fitness.043", "health_fitness",
            "Gets dental checkup every 6 months at YesPlan Dental in Yeonnam-dong, had one cavity filled in 2025",
            "YesPlan Dental is my dentist. Every 6 months. Had one cavity filled, first one in 10 years.",
            1050, 0.4, &["dental", "YesPlan", "Yeonnam-dong", "cavity", "6 months"]),
        super::fact("health_fitness.044", "health_fitness",
            "Prescription glasses/contacts: -2.5 both eyes, slight astigmatism in left eye",
            "My prescription is -2.5 both eyes with slight astigmatism in the left. Been stable for years.",
            750, 0.4, &["prescription", "-2.5", "astigmatism", "left eye"]),
        super::fact("health_fitness.045", "health_fitness",
            "Contact lenses are Acuvue Oasys daily disposables, orders them from Lens Town online",
            "I use Acuvue Oasys dailies. Order from Lens Town online, way cheaper than the eye doctor.",
            1150, 0.3, &["Acuvue Oasys", "contact lenses", "Lens Town", "daily"]),

        // === STRETCHING AND YOGA ===
        super::fact("health_fitness.046", "health_fitness",
            "Does 15 minutes of stretching every morning, follows a routine from YouTube channel 'Yoga with Adriene'",
            "I do 15 minutes of stretching every morning. Yoga with Adriene on YouTube. Her voice is so calming.",
            950, 0.5, &["stretching", "morning", "15 minutes", "Yoga with Adriene"]),
        super::fact("health_fitness.047", "health_fitness",
            "Tried a hot yoga class once at Yoga Pod Gangnam, felt like dying, never went back",
            "I tried hot yoga once at Yoga Pod in Gangnam. Nearly passed out. Never again.",
            2200, 0.3, &["hot yoga", "Yoga Pod", "Gangnam", "never again"]),

        // === SLEEP TRACKING ===
        super::fact("health_fitness.048", "health_fitness",
            "Tracks sleep with Apple Watch Ultra 2, average sleep score is 82/100",
            "My Apple Watch tracks sleep. Average score is 82. I'm proud of that, it used to be like 60.",
            1350, 0.4, &["Apple Watch", "sleep tracking", "score 82"]),
        super::fact("health_fitness.049", "health_fitness",
            "Best sleep habit improvement: no caffeine after 2 PM, suggested by Dr. Park",
            "No caffeine after 2 PM. Dr. Park suggested it and my sleep improved dramatically.",
            2600, 0.5, &["caffeine", "2 PM", "sleep", "Dr. Park"]),

        // === UPDATE CHAIN: Fitness goals ===
        super::update("health_fitness.050", "health_fitness",
            "Set 2026 fitness goals: complete a 10K, reach V5 in bouldering, maintain 64-65kg weight",
            "2026 goals: 10K race, V5 in climbing, stay around 64-65kg. All achievable if I'm consistent.",
            4000, 0.6, &["2026 goals", "10K", "V5", "64-65kg"],
            "fitness_goals", 1),
        super::update("health_fitness.051", "health_fitness",
            "Achieved all three 2026 fitness goals by March: 10K done, V5 sent, weight at 64kg",
            "All three fitness goals DONE by March. 10K completed, V5 sent, 64kg. Setting new goals now.",
            9700, 0.7, &["goals achieved", "all three", "March"],
            "fitness_goals", 2),

        // === MISC HEALTH FACTS ===
        super::fact("health_fitness.052", "health_fitness",
            "Has a slight fear of needles, gets anxious before blood draws and vaccinations",
            "I hate needles. Like genuinely anxious before blood draws. A grown adult who has to look away.",
            480, 0.3, &["needles", "fear", "blood draws", "anxious"]),
        super::fact("health_fitness.053", "health_fitness",
            "Got COVID in February 2024, mild symptoms for 5 days, lost taste for 2 weeks",
            "Got COVID in February 2024. Five days of feeling crappy, lost taste for 2 weeks. That was weird.",
            360, 0.5, &["COVID", "February 2024", "lost taste", "mild"]),
        super::fact("health_fitness.054", "health_fitness",
            "Flu shot every October at a local clinic in Yeonnam-dong, 35,000 won out of pocket",
            "I get my flu shot every October. Little clinic in Yeonnam-dong, 35K won. Quick and done.",
            1450, 0.3, &["flu shot", "October", "35K", "Yeonnam-dong"]),
        super::fact("health_fitness.055", "health_fitness",
            "Occasional lower back pain from desk work, uses a lumbar support cushion at the office",
            "My lower back complains from desk work. Got a lumbar support cushion for the office chair.",
            1550, 0.4, &["lower back pain", "desk work", "lumbar cushion"]),
        super::fact("health_fitness.056", "health_fitness",
            "Tried a 3-day water fast in July 2025 after reading about autophagy, quit after 36 hours",
            "I tried a water fast in July. Was supposed to be 3 days. Made it 36 hours. Not for me.",
            1000, 0.3, &["water fast", "July 2025", "36 hours", "autophagy"]),
        super::fact("health_fitness.057", "health_fitness",
            "Resting heart rate improved from 72 to 62 bpm over the past year with regular exercise",
            "My resting heart rate went from 72 to 62. A year of exercise does that. Apple Watch doesn't lie.",
            3200, 0.5, &["resting heart rate", "72", "62", "improved"]),
        super::fact("health_fitness.058", "health_fitness",
            "Has a foam roller for post-workout recovery, does 10 minutes after every run",
            "Foam rolling after runs is non-negotiable. 10 minutes. My IT band thanks me.",
            3400, 0.3, &["foam roller", "recovery", "10 minutes", "IT band"]),
        super::fact("health_fitness.059", "health_fitness",
            "Swimming cap color: navy blue silicone. Goggles: Speedo Vanquisher 2.0 with mirrored lenses",
            "Navy blue swim cap, Speedo Vanquisher goggles with mirrored lenses. I look ridiculous but functional.",
            3600, 0.3, &["swim cap", "navy blue", "Speedo", "goggles", "Vanquisher"]),
        super::fact("health_fitness.060", "health_fitness",
            "Dr. Park recommended journaling as complementary to therapy, writes 3 pages every night (morning pages adapted to evening)",
            "Dr. Park suggested journaling. I do 3 pages every night. Adapted morning pages to my schedule.",
            3800, 0.4, &["journaling", "3 pages", "night", "Dr. Park"]),

        // === INJURY PREVENTION ===
        super::fact("health_fitness.061", "health_fitness",
            "Wears a knee compression sleeve during runs (Bauerfeind GenuTrain), prevents re-injury",
            "I wear a Bauerfeind GenuTrain knee sleeve when running. Not taking any chances with that knee.",
            4400, 0.5, &["Bauerfeind", "GenuTrain", "knee sleeve", "prevention"]),
        super::fact("health_fitness.062", "health_fitness",
            "Does hip strengthening exercises (clamshells, bridges) 3 times a week per PT recommendation",
            "My PT said weak hips caused the knee issue. So I do clamshells and bridges 3 times a week now.",
            4600, 0.4, &["hip strengthening", "clamshells", "bridges", "PT"]),

        // === UPDATE CHAIN: Supplements ===
        super::update("health_fitness.063", "health_fitness",
            "Added magnesium supplement before bed for sleep quality, recommended by a health podcast",
            "Started taking magnesium before bed. Some health podcast recommended it. Sleep feels even deeper.",
            4800, 0.4, &["magnesium", "supplement", "sleep", "podcast"],
            "supplements", 1),
        super::update("health_fitness.064", "health_fitness",
            "Current supplement stack: vitamin D, omega-3, magnesium, and occasional zinc during cold season",
            "My supplement routine: vitamin D and omega-3 in morning, magnesium at night, zinc when I feel a cold coming.",
            7500, 0.4, &["vitamin D", "omega-3", "magnesium", "zinc"],
            "supplements", 2),

        // === UPDATE CHAIN: Running pace ===
        super::update("health_fitness.065", "health_fitness",
            "5km personal best was 28:42 in June 2025 before the knee injury",
            "My 5K PB was 28:42 in June. Right before the knee went. Should've eased off.",
            800, 0.5, &["5km", "28:42", "personal best", "June 2025"],
            "running_pace", 1),
        super::update("health_fitness.066", "health_fitness",
            "After returning from injury, 5km time is 30:15, slower but prioritizing form over speed",
            "My 5K is 30:15 now. Slower than before but I'm focusing on form. Speed will come.",
            7200, 0.5, &["5km", "30:15", "slower", "form"],
            "running_pace", 2),
        super::update("health_fitness.067", "health_fitness",
            "Set new 5km personal best of 27:58 in March 2026 during 10K training",
            "New 5K PB: 27:58! The 10K training made me faster across all distances.",
            9000, 0.6, &["5km", "27:58", "personal best", "March 2026"],
            "running_pace", 3),

        // === MISC LATER FACTS ===
        super::fact("health_fitness.068", "health_fitness",
            "Bought a Theragun Mini for muscle recovery, uses it on calves and quads after climbing",
            "Got a Theragun Mini. My calves after bouldering sessions... this thing saves me.",
            5200, 0.3, &["Theragun", "Mini", "muscle recovery", "calves"]),
        super::fact("health_fitness.069", "health_fitness",
            "Tried intermittent fasting (16:8) for 3 weeks in November 2025, found it too hard with work schedule",
            "Did 16:8 intermittent fasting for 3 weeks. With my work schedule it was miserable. Dropped it.",
            3100, 0.4, &["intermittent fasting", "16:8", "3 weeks", "November"]),
        super::fact("health_fitness.070", "health_fitness",
            "Maximum plank hold time: 3 minutes 20 seconds, achieved in January 2026",
            "My plank record is 3 minutes 20 seconds. January 2026. Almost died but made it.",
            4000, 0.3, &["plank", "3 minutes 20 seconds", "record"]),
        super::fact("health_fitness.071", "health_fitness",
            "Has a gym bag always packed: change of clothes, towel, shower kit, extra inhaler, protein bar",
            "My gym bag stays packed: clothes, towel, shower stuff, spare inhaler, protein bar. Grab and go.",
            5400, 0.3, &["gym bag", "packed", "inhaler", "protein bar"]),
        super::fact("health_fitness.072", "health_fitness",
            "Bouldering chalk preference: Mammut Loose Chalk, keeps it in a Black Diamond chalk bag",
            "Mammut loose chalk in a Black Diamond bag. Soyeon uses liquid chalk but I prefer the powder.",
            5600, 0.3, &["chalk", "Mammut", "Black Diamond", "bouldering"]),
        super::fact("health_fitness.073", "health_fitness",
            "Recovery day routine: foam rolling, stretching, casual walk, bath with Epsom salts",
            "Recovery days: foam roll, stretch, walk, Epsom salt bath. My body needs the TLC.",
            5800, 0.3, &["recovery day", "Epsom salt", "bath", "stretching"]),
        super::fact("health_fitness.074", "health_fitness",
            "VO2 max estimated at 42 ml/kg/min from Apple Watch, up from 38 a year ago",
            "Apple Watch says my VO2 max is 42 now. Was 38 a year ago. Cardio fitness is improving.",
            6200, 0.4, &["VO2 max", "42", "38", "Apple Watch"]),
        super::fact("health_fitness.075", "health_fitness",
            "Tried rock climbing outdoors at Bukhansan once with Soyeon, was terrified of heights but loved it",
            "Soyeon took me outdoor climbing at Bukhansan once. I'm scared of heights but the rush was amazing.",
            6400, 0.4, &["Bukhansan", "outdoor climbing", "heights", "Soyeon"]),
        super::fact("health_fitness.076", "health_fitness",
            "Eunji joined for swimming once, she's a better swimmer but hates the cold water",
            "Eunji came swimming with me once. She's way better than me but complained the water was freezing.",
            6600, 0.3, &["Eunji", "swimming", "better swimmer", "cold water"]),
        super::fact("health_fitness.077", "health_fitness",
            "Therapy topic in March 2026: processing decision to move in with Eunji, fear of losing independence",
            "March therapy session was about moving in with Eunji. I'm excited but scared of losing my alone time.",
            8500, 0.5, &["therapy", "March", "Eunji", "moving in", "independence"]),
        super::fact("health_fitness.078", "health_fitness",
            "Skin condition: mild eczema on inner elbows during dry winter months, uses Cerave moisturizer",
            "My eczema flares up in winter on my inner elbows. Cerave keeps it manageable.",
            6800, 0.4, &["eczema", "winter", "inner elbows", "Cerave"]),
        super::fact("health_fitness.079", "health_fitness",
            "Morning run route: apartment → Gyeongui Line Forest Park → Yeonnam-dong loop → home, exactly 5.2km",
            "My run route is apartment through Gyeongui Line park, loop around Yeonnam-dong, back home. 5.2km exactly.",
            7000, 0.4, &["run route", "Gyeongui Line", "5.2km", "loop"]),
        super::fact("health_fitness.080", "health_fitness",
            "Has a body composition scale (InBody H20N) at home, measures body fat percentage monthly",
            "I have an InBody scale at home. Check body fat monthly. Currently at 18.5%, down from 22%.",
            7200, 0.4, &["InBody", "body fat", "18.5%", "22%"]),
        super::fact("health_fitness.081", "health_fitness",
            "Tried pilates reformer class twice in 2025, liked it but couldn't commit to the schedule",
            "Did reformer pilates twice. Great workout but the class times didn't work with my schedule.",
            7400, 0.3, &["pilates", "reformer", "twice", "schedule"]),
        super::fact("health_fitness.082", "health_fitness",
            "Running in rain: has a lightweight Gore-Tex running jacket from Salomon for wet days",
            "My Salomon Gore-Tex jacket for rainy runs is perfect. Light, doesn't overheat, keeps me dry.",
            7600, 0.3, &["Gore-Tex", "Salomon", "running jacket", "rain"]),
        super::fact("health_fitness.083", "health_fitness",
            "Step count goal: 10,000 steps daily, achieves it about 5 days a week",
            "10K steps is my daily goal. Hit it about 5 days a week. Remote days are tough.",
            7800, 0.3, &["10000 steps", "daily goal", "5 days"]),
        super::fact("health_fitness.084", "health_fitness",
            "Post-run breakfast: avocado toast on sourdough with eggs and a protein shake",
            "Post-run breakfast is avocado toast on my sourdough bread with eggs plus a shake. Perfect fuel.",
            8200, 0.3, &["avocado toast", "sourdough", "eggs", "post-run"]),
        super::fact("health_fitness.085", "health_fitness",
            "Swimming milestone: completed 2km non-stop in March 2026, took 48 minutes",
            "Swam 2km non-stop! 48 minutes. Didn't think I'd ever say that. A year ago I could barely do 200m.",
            8800, 0.5, &["2km", "48 minutes", "swimming milestone"]),
        super::fact("health_fitness.086", "health_fitness",
            "Has an emergency medical bracelet with asthma info and blood type, wears during races",
            "I wear a medical bracelet during races. Asthma + blood type A+. Just in case.",
            9200, 0.4, &["medical bracelet", "asthma", "blood type", "races"]),
        super::fact("health_fitness.087", "health_fitness",
            "Dr. Park suggested mindfulness-based stress reduction (MBSR) course, considering it for 2026",
            "Dr. Park mentioned an MBSR course. Mindfulness-based stress reduction. Might do it later this year.",
            8400, 0.4, &["MBSR", "mindfulness", "Dr. Park", "2026"]),
        super::fact("health_fitness.088", "health_fitness",
            "Favorite post-bouldering meal: samgyeopsal at a nearby BBQ place in Hongdae with Soyeon",
            "After bouldering, Soyeon and I always hit this samgyeopsal place in Hongdae. Protein refuel.",
            8600, 0.3, &["samgyeopsal", "bouldering", "Hongdae", "Soyeon"]),
        super::fact("health_fitness.089", "health_fitness",
            "Tried CBD oil for sleep once, didn't notice much difference, stuck with magnesium",
            "Tried CBD oil for sleep. Didn't do anything for me. Magnesium is way more effective.",
            9000, 0.3, &["CBD oil", "sleep", "didn't work", "magnesium"]),
        super::fact("health_fitness.090", "health_fitness",
            "Annual eye exam at Noon Eye Clinic in Gangnam, last visit was January 2026, prescription stable",
            "Eye exam at Noon Clinic in Gangnam. January 2026, prescription hasn't changed. No LASIK for now.",
            9100, 0.3, &["eye exam", "Noon Clinic", "Gangnam", "January 2026"]),
        super::fact("health_fitness.091", "health_fitness",
            "Has a first aid kit at home: bandages, antiseptic, pain relievers, allergy meds, spare inhaler",
            "Home first aid kit has the basics plus allergy meds and a spare inhaler. Boy Scout preparedness.",
            9300, 0.3, &["first aid kit", "home", "bandages", "inhaler"]),
        super::fact("health_fitness.092", "health_fitness",
            "Hydration strategy during runs: no water for under 5km, carries handheld bottle for longer",
            "Under 5K I don't carry water. Anything longer, I have a handheld running bottle.",
            9400, 0.3, &["hydration", "running", "handheld bottle", "5km"]),
        super::fact("health_fitness.093", "health_fitness",
            "Flexibility goal: can almost touch toes, daily stretching helping gradually",
            "I still can't fully touch my toes. Almost though. Daily stretching is slowly getting me there.",
            9600, 0.3, &["flexibility", "touch toes", "stretching", "goal"]),
        super::fact("health_fitness.094", "health_fitness",
            "Health app data shows average daily calories burned: 2,200 on rest days, 2,800 on exercise days",
            "My watch says I burn about 2,200 calories on rest days, 2,800 on active days. Eating accordingly.",
            9700, 0.3, &["calories", "2200", "2800", "rest days", "exercise days"]),
        super::fact("health_fitness.095", "health_fitness",
            "Considered getting a personal trainer but decided self-guided training with YouTube is sufficient",
            "Thought about a personal trainer. Decided YouTube plus Strava is good enough for now.",
            9800, 0.3, &["personal trainer", "self-guided", "YouTube", "considered"]),
        super::fact("health_fitness.096", "health_fitness",
            "Post-10K race goal: now training for a half marathon in October 2026",
            "Next goal after the 10K: half marathon in October 2026. Ambitious but why not.",
            9850, 0.6, &["half marathon", "October 2026", "next goal"]),
        super::fact("health_fitness.097", "health_fitness",
            "Therapy insight: learned to separate work identity from personal identity, major breakthrough",
            "Biggest therapy breakthrough: I am not my job. Sounds obvious but it wasn't to me.",
            8700, 0.6, &["therapy", "breakthrough", "work identity", "personal identity"]),
        super::fact("health_fitness.098", "health_fitness",
            "Has a meditation corner in bedroom with a cushion from Muji and a small incense holder",
            "I set up a meditation corner. Muji cushion, incense holder. Five minutes in the morning.",
            8900, 0.4, &["meditation corner", "Muji", "cushion", "incense"]),
        super::fact("health_fitness.099", "health_fitness",
            "Bouldering injury: minor finger pulley strain in March 2026, taping A2 pulley on left ring finger",
            "Strained my A2 pulley on my left ring finger bouldering. Taping it and resting from crimps.",
            9900, 0.4, &["pulley strain", "A2", "left ring finger", "taping"]),
        super::fact("health_fitness.100", "health_fitness",
            "Overall health assessment: best shape of his life at 30, credits running, swimming, therapy, and Eunji's cooking",
            "I'm honestly in the best shape of my life at 30. Running, swimming, therapy, and Eunji feeding me well.",
            9950, 0.6, &["best shape", "30", "overall health"]),
    ]
}

pub fn false_probes() -> Vec<Question> {
    vec![
        // never_mentioned (15)
        super::false_probe("health_fitness.FM.001", "health_fitness",
            "What gym membership do you have? You mentioned a place in Gangnam?"),
        super::false_probe("health_fitness.FM.002", "health_fitness",
            "You said you were diagnosed with depression, right?"),
        super::false_probe("health_fitness.FM.003", "health_fitness",
            "What was the name of that nutritionist you were seeing?"),
        super::false_probe("health_fitness.FM.004", "health_fitness",
            "Didn't you mention having a shoulder injury from swimming?"),
        super::false_probe("health_fitness.FM.005", "health_fitness",
            "You said you take blood pressure medication, right?"),
        super::false_probe("health_fitness.FM.006", "health_fitness",
            "What was the name of that marathon you ran in Busan?"),
        super::false_probe("health_fitness.FM.007", "health_fitness",
            "Didn't you say you've been doing CrossFit?"),
        super::false_probe("health_fitness.FM.008", "health_fitness",
            "You mentioned having surgery on your knee, right?"),
        super::false_probe("health_fitness.FM.009", "health_fitness",
            "What was that meditation retreat you went to in Gangwon-do?"),
        super::false_probe("health_fitness.FM.010", "health_fitness",
            "You said Dr. Park prescribed anti-anxiety medication?"),
        super::false_probe("health_fitness.FM.011", "health_fitness",
            "Didn't you mention getting food poisoning from that sushi restaurant?"),
        super::false_probe("health_fitness.FM.012", "health_fitness",
            "You said you had a cycling accident, right?"),
        super::false_probe("health_fitness.FM.013", "health_fitness",
            "What was the weight loss app you were using?"),
        super::false_probe("health_fitness.FM.014", "health_fitness",
            "Didn't you say you started boxing classes?"),
        super::false_probe("health_fitness.FM.015", "health_fitness",
            "You mentioned breaking your arm as a child?"),

        // adjacent_entity (10)
        super::false_probe("health_fitness.FM.016", "health_fitness",
            "Your orthopedist Dr. Choi is at Asan Medical Center, right?"),
        super::false_probe("health_fitness.FM.017", "health_fitness",
            "You swim at Gangnam District pool, don't you?"),
        super::false_probe("health_fitness.FM.018", "health_fitness",
            "Your running shoes are Asics Gel-Kayano, right?"),
        super::false_probe("health_fitness.FM.019", "health_fitness",
            "Dr. Park uses psychodynamic therapy, doesn't he?"),
        super::false_probe("health_fitness.FM.020", "health_fitness",
            "Your bouldering grade is V6 now, right?"),
        super::false_probe("health_fitness.FM.021", "health_fitness",
            "You track runs with Nike Run Club, right?"),
        super::false_probe("health_fitness.FM.022", "health_fitness",
            "Your 10K race was the Seoul Autumn Marathon, wasn't it?"),
        super::false_probe("health_fitness.FM.023", "health_fitness",
            "Your weight dropped to 62kg at some point?"),
        super::false_probe("health_fitness.FM.024", "health_fitness",
            "Therapy sessions are 150,000 won each, right?"),
        super::false_probe("health_fitness.FM.025", "health_fitness",
            "You do bouldering at Climbing Zone in Gangnam?"),

        // plausible_inference (5)
        super::false_probe("health_fitness.FM.026", "health_fitness",
            "With your asthma, do you avoid swimming in chlorinated pools?"),
        super::false_probe("health_fitness.FM.027", "health_fitness",
            "Since you're doing a half marathon, have you hired a running coach?"),
        super::false_probe("health_fitness.FM.028", "health_fitness",
            "With your shellfish allergy and asthma, do you carry multiple EpiPens?"),
        super::false_probe("health_fitness.FM.029", "health_fitness",
            "Given your fear of needles, do you do your vitamin D via oral spray instead of injection?"),
        super::false_probe("health_fitness.FM.030", "health_fitness",
            "Since you had a panic attack, did you get an EKG at the hospital?"),

        // temporal_phantom (5)
        super::false_probe("health_fitness.FM.031", "health_fitness",
            "Didn't you have a second knee injury that required surgery?"),
        super::false_probe("health_fitness.FM.032", "health_fitness",
            "You mentioned stopping therapy for a few months and then restarting?"),
        super::false_probe("health_fitness.FM.033", "health_fitness",
            "Wasn't there a period when your weight dropped below 62kg and you were concerned?"),
        super::false_probe("health_fitness.FM.034", "health_fitness",
            "Didn't you get hospitalized for an asthma attack in 2025?"),
        super::false_probe("health_fitness.FM.035", "health_fitness",
            "You said your 10K time was 48 minutes initially, right?"),

        // cross_category (5)
        super::false_probe("health_fitness.FM.036", "health_fitness",
            "Didn't you say Mochi the cat helps with your anxiety at home?"),
        super::false_probe("health_fitness.FM.037", "health_fitness",
            "You said running helps with your asthma because of the Jeju sea air during that trip?"),
        super::false_probe("health_fitness.FM.038", "health_fitness",
            "Didn't you start swimming because Eunji recommended it?"),
        super::false_probe("health_fitness.FM.039", "health_fitness",
            "Your Figma work at Velta contributed to the wrist strain, right?"),
        super::false_probe("health_fitness.FM.040", "health_fitness",
            "Didn't you say the bouldering gym is where you met your friend Chanwoo?"),
    ]
}
