use crate::types::{Fact, Question};

pub fn facts() -> Vec<Fact> {
    vec![
        // === CORE MEDIA TASTE (early turns) ===
        super::fact("media_taste.001", "media_taste",
            "All-time favorite movie is Eternal Sunshine of the Spotless Mind (2004), has watched it 8 times",
            "Eternal Sunshine is my favorite movie of all time. Eight rewatches and counting. Cries every time.",
            80, 0.8, &["Eternal Sunshine", "favorite movie", "8 times", "2004"]),
        super::fact("media_taste.002", "media_taste",
            "Favorite book is Pachinko by Min Jin Lee, read it in both English and Korean translation",
            "Pachinko destroyed me. Read it in English first then Korean. Somehow hit harder in Korean.",
            120, 0.7, &["Pachinko", "Min Jin Lee", "book", "English", "Korean"]),
        super::fact("media_taste.003", "media_taste",
            "Favorite band is Hyukoh, has seen them live 3 times, favorite song is 'Gondry'",
            "Hyukoh is my band. Seen them live 3 times. 'Gondry' is the song that makes me feel everything.",
            160, 0.8, &["Hyukoh", "live", "3 times", "Gondry"]),
        super::fact("media_taste.004", "media_taste",
            "Loves SE SO NEON, considers them the best indie rock band in Korea right now",
            "SE SO NEON is the best indie band in Korea right now. Not debatable.",
            200, 0.7, &["SE SO NEON", "indie rock", "Korea"]),
        super::fact("media_taste.005", "media_taste",
            "Currently playing Stardew Valley on Nintendo Switch, has 340 hours logged, married Leah in-game",
            "340 hours in Stardew Valley. Married Leah. My farm is called 'Haechan Farm.' No regrets.",
            250, 0.6, &["Stardew Valley", "340 hours", "Leah", "Nintendo Switch"]),

        // === MOVIE TASTE ===
        super::fact("media_taste.006", "media_taste",
            "Strongly dislikes horror movies, can't watch them alone, made exception for Parasite which is thriller",
            "I cannot watch horror movies. Hard no. Parasite is thriller not horror, I will die on this hill.",
            300, 0.6, &["horror", "dislike", "Parasite", "thriller"]),
        super::fact("media_taste.007", "media_taste",
            "Top 5 movies: Eternal Sunshine, In the Mood for Love, Parasite, Before Sunrise, Lost in Translation",
            "My top 5: Eternal Sunshine, In the Mood for Love, Parasite, Before Sunrise, Lost in Translation.",
            370, 0.6, &["top 5", "In the Mood for Love", "Before Sunrise", "Lost in Translation"]),
        super::fact("media_taste.008", "media_taste",
            "Watches movies mostly on Netflix and at CGV Yeonnam cinema, prefers small theaters",
            "CGV Yeonnam for cinema, Netflix at home. I prefer smaller theaters over the multiplexes.",
            440, 0.4, &["Netflix", "CGV Yeonnam", "cinema", "small theaters"]),
        super::fact("media_taste.009", "media_taste",
            "Favorite director is Wong Kar-wai, has a poster of Chungking Express in the home office",
            "Wong Kar-wai is a genius. Got a Chungking Express poster in my home office. The colors.",
            550, 0.5, &["Wong Kar-wai", "Chungking Express", "poster", "director"]),
        super::fact("media_taste.010", "media_taste",
            "Watched Drive My Car (2021) in the theater alone, considers it the best film of the decade",
            "Drive My Car alone in the theater. Three hours. Best film this decade. I sat in the seat for 10 minutes after.",
            650, 0.5, &["Drive My Car", "2021", "best film", "alone"]),

        // === MUSIC TASTE ===
        super::fact("media_taste.011", "media_taste",
            "Spotify Wrapped 2025: top artist was Hyukoh, 847 minutes listened, top genre was Korean Indie",
            "Spotify Wrapped: Hyukoh at 847 minutes. Korean Indie was my top genre. Sounds about right.",
            750, 0.5, &["Spotify Wrapped", "2025", "847 minutes", "Korean Indie"]),
        super::fact("media_taste.012", "media_taste",
            "Also listens to Japanese city pop: Tatsuro Yamashita, Mariya Takeuchi, discovered through YouTube algorithm",
            "The YouTube algorithm blessed me with Japanese city pop. Tatsuro Yamashita's 'Ride on Time' is perfection.",
            850, 0.5, &["city pop", "Tatsuro Yamashita", "Mariya Takeuchi", "Japanese"]),
        super::fact("media_taste.013", "media_taste",
            "Has a vinyl collection of about 200 records, mostly jazz and Korean indie, stored in IKEA Kallax shelf",
            "200 vinyl records. Jazz and Korean indie mostly. IKEA Kallax shelf, 4x2. Running out of space.",
            330, 0.7, &["vinyl", "200 records", "jazz", "Korean indie", "Kallax"]),
        super::fact("media_taste.014", "media_taste",
            "Favorite jazz album is Kind of Blue by Miles Davis, the first vinyl he ever bought",
            "Kind of Blue was my first vinyl purchase. Miles Davis. It still sounds as good as the day I got it.",
            950, 0.5, &["Kind of Blue", "Miles Davis", "first vinyl", "jazz"]),
        super::fact("media_taste.015", "media_taste",
            "Record player is an Audio-Technica AT-LP120X connected to Edifier R1280T speakers",
            "My turntable is an Audio-Technica LP120X into Edifier R1280T speakers. Not audiophile crazy but sounds great.",
            1050, 0.5, &["Audio-Technica", "AT-LP120X", "Edifier", "R1280T", "turntable"]),

        // === BOOKS AND READING ===
        super::fact("media_taste.016", "media_taste",
            "Reading goal: 24 books in 2026 (2 per month), currently on track with 6 finished by March",
            "2026 goal: 24 books. Two a month. I'm at 6 as of March. On track.",
            1150, 0.5, &["reading goal", "24 books", "2026", "2 per month"]),
        super::fact("media_taste.017", "media_taste",
            "Reads mostly on Kindle Paperwhite before bed, buys physical copies of favorites for the shelf",
            "Kindle for reading, physical copies for keepers. Best of both worlds.",
            400, 0.4, &["Kindle", "Paperwhite", "physical copies", "shelf"]),
        super::fact("media_taste.018", "media_taste",
            "Favorite genres: literary fiction, memoirs, and design-related nonfiction",
            "I read literary fiction, memoirs, and design books. Sometimes a good essay collection.",
            1250, 0.4, &["literary fiction", "memoirs", "design", "nonfiction"]),
        super::fact("media_taste.019", "media_taste",
            "Recently read and loved 'The Vegetarian' by Han Kang, found it disturbing but brilliant",
            "The Vegetarian by Han Kang messed me up. Disturbing and brilliant. Korean literature at its best.",
            1350, 0.5, &["The Vegetarian", "Han Kang", "disturbing", "Korean literature"]),
        super::fact("media_taste.020", "media_taste",
            "Has a Goodreads account with 142 books rated, username is 'kimreads92'",
            "My Goodreads: kimreads92. 142 books rated. Mostly 4-star ratings because I'm generous.",
            1450, 0.3, &["Goodreads", "142 books", "kimreads92"]),

        // === PODCASTS ===
        super::fact("media_taste.021", "media_taste",
            "Regular podcast listener: 'Tech & the City' (Korean tech podcast) every Tuesday on commute",
            "Tech & the City is my Tuesday subway ritual. Korean tech scene news and interviews.",
            500, 0.5, &["Tech & the City", "podcast", "Tuesday", "Korean tech"]),
        super::fact("media_taste.022", "media_taste",
            "Also listens to 'Bookworm Seoul' podcast about book reviews and author interviews every Thursday",
            "Bookworm Seoul on Thursdays. Book reviews and author interviews. Great for finding my next read.",
            600, 0.5, &["Bookworm Seoul", "podcast", "Thursday", "book reviews"]),
        super::fact("media_taste.023", "media_taste",
            "International podcast: listens to '99% Invisible' about design, catches up on weekends",
            "99% Invisible is the design podcast. Roman Mars' voice is hypnotic. Weekend listening.",
            1550, 0.4, &["99% Invisible", "Roman Mars", "design podcast", "weekend"]),

        // === GAMING ===
        super::fact("media_taste.024", "media_taste",
            "Besides Stardew Valley, also plays Zelda: Tears of the Kingdom, about 120 hours in",
            "Also playing Zelda: Tears of the Kingdom. 120 hours. The open world design is mind-blowing.",
            420, 0.5, &["Zelda", "Tears of the Kingdom", "120 hours", "open world"]),
        super::fact("media_taste.025", "media_taste",
            "Doesn't play competitive multiplayer games, prefers single-player story-driven or cozy games",
            "I don't do competitive multiplayer. Give me a good story or let me farm in peace.",
            700, 0.4, &["single-player", "story-driven", "cozy games", "no multiplayer"]),
        super::fact("media_taste.026", "media_taste",
            "Played Celeste and it helped during the anxiety period, resonated with the mental health themes",
            "Celeste hit different when I was going through anxiety stuff. That game understands.",
            2300, 0.5, &["Celeste", "anxiety", "mental health", "resonated"]),

        // === TV AND K-DRAMA ===
        super::fact("media_taste.027", "media_taste",
            "Favorite K-drama of all time: Reply 1988, rewatched it with Eunji",
            "Reply 1988 is peak K-drama. Rewatched it with Eunji, she cried harder than me.",
            800, 0.5, &["Reply 1988", "K-drama", "rewatched", "Eunji"]),
        super::fact("media_taste.028", "media_taste",
            "Currently watching 'Extraordinary Attorney Woo' on Netflix, loves the whale facts",
            "Extraordinary Attorney Woo is so wholesome. The whale facts! I text them to Eunji.",
            1650, 0.4, &["Extraordinary Attorney Woo", "Netflix", "whale facts"]),
        super::fact("media_taste.029", "media_taste",
            "Non-Korean show guilty pleasure: watched all of 'The Bear' in one weekend, inspired kitchen organization",
            "Binged The Bear in one weekend. Now I organize my kitchen like a restaurant. Yes, chef.",
            2400, 0.4, &["The Bear", "binged", "kitchen", "weekend"]),

        // === UPDATE CHAIN 1: Current book ===
        super::update("media_taste.030", "media_taste",
            "Reading 'Klara and the Sun' by Kazuo Ishiguro, 60% through, finds it melancholic and beautiful",
            "Reading Klara and the Sun. 60% through. It's so melancholic. Ishiguro writes loneliness like no one else.",
            3000, 0.5, &["Klara and the Sun", "Ishiguro", "reading", "melancholic"],
            "current_book", 1),
        super::update("media_taste.031", "media_taste",
            "Finished 'Klara and the Sun', gave it 5 stars on Goodreads, bought physical copy for shelf",
            "Finished Klara and the Sun. Five stars. Bought the physical copy. Shelf-worthy.",
            4000, 0.4, &["Klara and the Sun", "finished", "5 stars", "shelf"],
            "current_book", 2),
        super::update("media_taste.032", "media_taste",
            "Now reading 'Kim Ji-young, Born 1982' by Cho Nam-joo, recommended by Eunji",
            "Eunji recommended 'Kim Ji-young, Born 1982.' Reading it now. Eye-opening perspective.",
            5500, 0.5, &["Kim Ji-young", "Cho Nam-joo", "Eunji recommended"],
            "current_book", 3),

        // === UPDATE CHAIN 2: New music discovery ===
        super::update("media_taste.033", "media_taste",
            "Discovered a band called Silica Gel through Soyeon, experimental electronic-rock, became obsessed",
            "Soyeon showed me Silica Gel. Experimental electronic-rock. I can't stop listening.",
            3500, 0.5, &["Silica Gel", "Soyeon", "electronic-rock", "obsessed"],
            "music_discovery", 1),
        super::update("media_taste.034", "media_taste",
            "Saw Silica Gel live at Rolling Hall in Hongdae in February 2026, bought their LP at the merch table",
            "Silica Gel live at Rolling Hall in Hongdae. February. Bought the LP. Life-changing show.",
            5800, 0.6, &["Silica Gel", "Rolling Hall", "Hongdae", "February", "LP"],
            "music_discovery", 2),

        // === UPDATE CHAIN 3: Gaming ===
        super::update("media_taste.035", "media_taste",
            "Started playing Hades 2 early access on Switch, drawn to the art direction and roguelike mechanics",
            "Hades 2 in early access. The art direction alone... as a designer I'm studying their color palette.",
            4500, 0.4, &["Hades 2", "early access", "Switch", "art direction"],
            "current_game", 1),
        super::update("media_taste.036", "media_taste",
            "Completed Hades 2 main story, now playing Balatro as a casual break game, 80 hours already",
            "Finished Hades 2 story. Now addicted to Balatro. 80 hours of a poker roguelike. Help.",
            7000, 0.4, &["Hades 2", "completed", "Balatro", "80 hours"],
            "current_game", 2),

        // === UPDATE CHAIN 4: K-drama watching ===
        super::update("media_taste.037", "media_taste",
            "Watched 'Squid Game 2' with Eunji on release day, found it good but not as impactful as season 1",
            "Squid Game 2 on release day with Eunji. Good but didn't hit like season 1. Hard to recapture that.",
            3800, 0.5, &["Squid Game 2", "Eunji", "release day", "season 1"],
            "kdrama_current", 1),
        super::update("media_taste.038", "media_taste",
            "Both really enjoyed 'Moving' on Disney+, binged all 20 episodes in 3 days",
            "Moving on Disney+ was incredible. 20 episodes in 3 days. Eunji and I were wrecked emotionally.",
            6000, 0.5, &["Moving", "Disney+", "20 episodes", "3 days"],
            "kdrama_current", 2),

        // === UPDATE CHAIN 5: Vinyl collecting ===
        super::update("media_taste.039", "media_taste",
            "Bought a rare pressing of Hyukoh's '23' album at Dope Records in Itaewon for 85,000 won",
            "Found Hyukoh's '23' pressing at Dope Records Itaewon. 85K won. My prized vinyl possession.",
            2600, 0.5, &["Hyukoh", "23 album", "Dope Records", "Itaewon", "85K"],
            "vinyl_collection", 1),
        super::update("media_taste.040", "media_taste",
            "Vinyl collection grew to 215 records, had to add a second Kallax shelf unit",
            "215 records now. Had to buy a second Kallax shelf. The collection is taking over.",
            6500, 0.4, &["215 records", "second Kallax", "vinyl", "growing"],
            "vinyl_collection", 2),

        // === UPDATE CHAIN 6: Concert/live music ===
        super::update("media_taste.041", "media_taste",
            "Got tickets to SE SO NEON's summer concert at Olympic Park in July 2026",
            "SE SO NEON tickets for July at Olympic Park! Taking Eunji. She's going to love them.",
            5000, 0.5, &["SE SO NEON", "concert", "Olympic Park", "July 2026"],
            "concerts", 1),

        // === UPDATE CHAIN 7: Podcast discovery ===
        super::update("media_taste.042", "media_taste",
            "Started listening to a new podcast called 'Design Better' by InVision, monthly",
            "New podcast: Design Better by InVision. Monthly episodes but they're deep dives. Worth it.",
            4200, 0.3, &["Design Better", "InVision", "podcast", "monthly"],
            "podcast_new", 1),

        // === UPDATE CHAIN 8: Film preference shift ===
        super::update("media_taste.043", "media_taste",
            "Getting more into documentary films, watched 'Free Solo' and 'Jiro Dreams of Sushi' back to back",
            "I'm on a documentary kick. Free Solo then Jiro Dreams of Sushi. Obsessive dedication stories get me.",
            4800, 0.4, &["documentary", "Free Solo", "Jiro Dreams of Sushi"],
            "film_shift", 1),
        super::update("media_taste.044", "media_taste",
            "Watched the Korean documentary 'My Love, Don't Cross That River' with mother during Busan visit, both cried",
            "Watched 'My Love, Don't Cross That River' with mom in Busan. We both sobbed. Beautiful film about old love.",
            7500, 0.5, &["My Love Don't Cross That River", "documentary", "mother", "cried"],
            "film_shift", 2),

        // === UPDATE CHAIN 9: Reading habit ===
        super::update("media_taste.045", "media_taste",
            "Joined a small book club with Eunji and two of her Naver colleagues, meets monthly at a Bundang cafe",
            "Eunji got me into her book club. Four people, monthly at a Bundang cafe. Different from solo reading.",
            5200, 0.4, &["book club", "Eunji", "Bundang", "monthly"],
            "book_club", 1),

        // === UPDATE CHAIN 10: Playlist evolution ===
        super::update("media_taste.046", "media_taste",
            "Created a couples playlist with Eunji called 'Us' on Spotify, 247 songs as of March 2026",
            "Our shared Spotify playlist 'Us' hit 247 songs. Eunji adds pop, I add indie. It works.",
            3200, 0.4, &["Us playlist", "Spotify", "247 songs", "Eunji"],
            "playlist_evolution", 1),
        super::update("media_taste.047", "media_taste",
            "Added a 'cooking music' playlist: all Italian jazz and bossa nova, 62 songs",
            "Made a cooking playlist. Italian jazz, bossa nova. 62 songs. Makes me feel like I'm in a European kitchen.",
            7200, 0.3, &["cooking playlist", "Italian jazz", "bossa nova", "62 songs"],
            "playlist_evolution", 2),

        // === REMAINING FACTS ===
        super::fact("media_taste.048", "media_taste",
            "Favorite anime: Spirited Away by Miyazaki, watched it as a child and it shaped his aesthetic sense",
            "Spirited Away shaped who I am. Watched it as a kid and something clicked about beauty and storytelling.",
            180, 0.5, &["Spirited Away", "Miyazaki", "anime", "childhood"]),
        super::fact("media_taste.049", "media_taste",
            "Dislikes mainstream K-pop, respects the production quality but finds it too manufactured",
            "K-pop isn't for me. I respect the production but it feels too manufactured. Indie forever.",
            500, 0.4, &["K-pop", "dislike", "manufactured", "indie"]),
        super::fact("media_taste.050", "media_taste",
            "Favorite music for work: lo-fi hip hop and ambient electronic, has specific Spotify playlists for deep work",
            "Lo-fi hip hop and ambient electronic for work. Different playlists for different focus levels.",
            700, 0.4, &["lo-fi", "ambient", "work music", "focus"]),
        super::fact("media_taste.051", "media_taste",
            "Favorite YouTube channels: The Futur (design business), Baumgartner Restoration (art restoration), J.J. McCullough",
            "YouTube: The Futur for design business, Baumgartner Restoration for art stuff, J.J. McCullough for random knowledge.",
            1000, 0.4, &["The Futur", "Baumgartner", "YouTube", "J.J. McCullough"]),
        super::fact("media_taste.052", "media_taste",
            "Read 'Norwegian Wood' by Murakami at 19, it was the book that made him love reading",
            "Norwegian Wood at 19 made me a reader. Murakami showed me books could feel like music.",
            350, 0.5, &["Norwegian Wood", "Murakami", "19", "love reading"]),
        super::fact("media_taste.053", "media_taste",
            "Guilty pleasure movie: Howl's Moving Castle, watches it when feeling sick or sad",
            "Howl's Moving Castle is my comfort movie. Sick day? Sad? Howl. Always Howl.",
            1200, 0.4, &["Howl's Moving Castle", "comfort movie", "guilty pleasure"]),
        super::fact("media_taste.054", "media_taste",
            "Hates reality TV shows, makes exception for 'Physical: 100' because of the fitness aspect",
            "Reality TV is garbage except Physical: 100. The fitness challenges are genuinely impressive.",
            1800, 0.3, &["reality TV", "Physical 100", "exception", "hate"]),
        super::fact("media_taste.055", "media_taste",
            "Favorite jazz artist besides Miles Davis: Chet Baker, especially the album 'Chet Baker Sings'",
            "Chet Baker's vocal album is something else. 'My Funny Valentine' on vinyl late at night. Perfect.",
            2000, 0.4, &["Chet Baker", "Chet Baker Sings", "My Funny Valentine", "jazz"]),
        super::fact("media_taste.056", "media_taste",
            "Attended Zandari Festa (Seoul indie music festival) in 2025, saw 12 bands over 2 days",
            "Zandari Festa 2025: 12 bands, 2 days, sore feet, ringing ears. Best weekend of my year.",
            2100, 0.5, &["Zandari Festa", "2025", "indie festival", "12 bands"]),
        super::fact("media_taste.057", "media_taste",
            "Design book on nightstand: 'Thinking with Type' by Ellen Lupton, reference book he returns to often",
            "Thinking with Type by Ellen Lupton lives on my nightstand. I flip through it like a bible.",
            2500, 0.4, &["Thinking with Type", "Ellen Lupton", "design book"]),
        super::fact("media_taste.058", "media_taste",
            "Doesn't like true crime podcasts or shows, finds them exploitative",
            "True crime content makes me uncomfortable. Feels exploitative. Not my thing.",
            2700, 0.3, &["true crime", "exploitative", "dislike"]),
        super::fact("media_taste.059", "media_taste",
            "Watches film reviews by Korean YouTuber 'Filmmaker Lee' who does visual analysis",
            "Filmmaker Lee on YouTube does the best visual film analysis in Korean. I learn so much about cinematography.",
            2900, 0.3, &["Filmmaker Lee", "YouTube", "film analysis", "Korean"]),
        super::fact("media_taste.060", "media_taste",
            "Favorite SE SO NEON song is 'Jayu' (Freedom), has the chord progression as phone wallpaper in text form",
            "SE SO NEON's 'Jayu' is my anthem. I literally have the chord progression as my phone wallpaper.",
            3100, 0.4, &["SE SO NEON", "Jayu", "Freedom", "chord progression"]),
        super::fact("media_taste.061", "media_taste",
            "Board game night with friends once a month: favorites are Wingspan, Ticket to Ride, and Codenames",
            "Monthly board game night. Wingspan is my favorite. Ticket to Ride for beginners. Codenames for chaos.",
            3300, 0.4, &["board games", "Wingspan", "Ticket to Ride", "Codenames", "monthly"]),
        super::fact("media_taste.062", "media_taste",
            "Went to a jazz bar called Vinyl in Itaewon for a live session, became a monthly ritual",
            "There's a jazz bar called Vinyl in Itaewon. Live sessions. It's become my monthly thing. Just me and the music.",
            3600, 0.4, &["Vinyl", "jazz bar", "Itaewon", "live", "monthly"]),
        super::fact("media_taste.063", "media_taste",
            "Favorite webtoon: 'Yumi's Cells' on Naver Webtoon, relates to the emotional visualization concept",
            "Yumi's Cells on Naver Webtoon. The way they visualize emotions? Genius. Relatable.",
            3900, 0.4, &["Yumi's Cells", "Naver Webtoon", "emotions", "visualization"]),
        super::fact("media_taste.064", "media_taste",
            "Movie he quotes most: The Grand Budapest Hotel, uses 'you see, there are still faint glimmers of civilization' regularly",
            "I quote Grand Budapest Hotel more than any normal person should. 'Faint glimmers of civilization.'",
            4100, 0.3, &["Grand Budapest Hotel", "quote", "Wes Anderson"]),
        super::fact("media_taste.065", "media_taste",
            "Childhood TV show nostalgia: Doraemon and Crayon Shin-chan, still watches episodes when feeling nostalgic",
            "Doraemon and Shin-chan were my childhood. Still watch old episodes for comfort. Don't judge me.",
            4300, 0.3, &["Doraemon", "Crayon Shin-chan", "childhood", "nostalgia"]),
        super::fact("media_taste.066", "media_taste",
            "Bought 'Designing Design' by Kenya Hara at Kyobo Bookstore in Gwanghwamun, considers it a masterpiece",
            "Kenya Hara's 'Designing Design' from Kyobo Bookstore. A masterpiece. Every designer should read it.",
            4600, 0.4, &["Designing Design", "Kenya Hara", "Kyobo Bookstore"]),
        super::fact("media_taste.067", "media_taste",
            "Netflix algorithm thinks he likes action movies because Eunji watches them on his profile",
            "My Netflix recommendations are all action movies now because Eunji watches them on my profile. My algorithm is ruined.",
            4900, 0.3, &["Netflix", "algorithm", "action movies", "Eunji profile"]),
        super::fact("media_taste.068", "media_taste",
            "Favorite music video: Hyukoh's 'Tomboy', directed by GDW, inspired his approach to visual storytelling",
            "Hyukoh's 'Tomboy' music video changed how I think about visual storytelling. GDW directed it brilliantly.",
            5300, 0.4, &["Hyukoh", "Tomboy", "music video", "GDW"]),
        super::fact("media_taste.069", "media_taste",
            "Has a collection of Monocle magazines, about 15 issues, treats them as design inspiration rather than reading material",
            "I collect Monocle magazine. About 15 issues. More for design inspiration than actual reading.",
            5600, 0.3, &["Monocle", "magazine", "15 issues", "design inspiration"]),
        super::fact("media_taste.070", "media_taste",
            "Watched 'Past Lives' (2023) and felt it captured the Korean diaspora experience perfectly",
            "Past Lives wrecked me. The way it captures Korean diaspora feelings... I felt so seen.",
            5900, 0.5, &["Past Lives", "2023", "Korean diaspora"]),
        super::fact("media_taste.071", "media_taste",
            "Prefers albums over singles, listens to full albums front to back on vinyl Wednesday nights",
            "Full albums on vinyl, front to back. Wednesday no-screen nights are for this. No shuffling.",
            6100, 0.4, &["albums", "vinyl", "Wednesday", "no shuffling"]),
        super::fact("media_taste.072", "media_taste",
            "Book that changed his worldview: 'Sapiens' by Yuval Noah Harari, read during university",
            "Sapiens changed how I see the world. Read it at Yonsei. Made me question everything.",
            6300, 0.4, &["Sapiens", "Harari", "worldview", "university"]),
        super::fact("media_taste.073", "media_taste",
            "Favorite poem: 'Pul (Grass)' by Kim Su-yeong, memorized it for a school recitation and never forgot",
            "Kim Su-yeong's 'Grass' is the only poem I have memorized. Learned it for school. Never left me.",
            6500, 0.3, &["Grass", "Kim Su-yeong", "poem", "memorized"]),
        super::fact("media_taste.074", "media_taste",
            "Avoids spoilers aggressively, unfollows people on social media during major show releases",
            "I will unfollow friends for spoilers. Dead serious. Squid Game 2 was a minefield.",
            6700, 0.3, &["spoilers", "unfollow", "aggressive", "social media"]),
        super::fact("media_taste.075", "media_taste",
            "Listens to rain sounds on Spotify when working, specific playlist called 'Rain on Tin Roof'",
            "Rain on Tin Roof playlist on Spotify for deep work. Not music, just rain. Weirdly perfect.",
            6900, 0.3, &["rain sounds", "Spotify", "Rain on Tin Roof", "deep work"]),
        super::fact("media_taste.076", "media_taste",
            "Eunji got him into Studio Ghibli soundtracks by Joe Hisaishi, now plays them while cooking",
            "Eunji introduced me to Joe Hisaishi soundtrack albums. Now I cook to Spirited Away OST. Life improved.",
            7100, 0.3, &["Joe Hisaishi", "Ghibli", "soundtracks", "cooking"]),
        super::fact("media_taste.077", "media_taste",
            "Tried reading 'Infinite Jest' by David Foster Wallace, abandoned at page 200. Too dense.",
            "Infinite Jest defeated me at page 200. Maybe someday. Probably not.",
            7300, 0.3, &["Infinite Jest", "Wallace", "abandoned", "page 200"]),
        super::fact("media_taste.078", "media_taste",
            "Attends movie screenings at Seoul Art Cinema in Jongno, mostly classic and art house films",
            "Seoul Art Cinema in Jongno for classic and art house stuff. They do amazing retrospectives.",
            7500, 0.4, &["Seoul Art Cinema", "Jongno", "art house", "retrospectives"]),
        super::fact("media_taste.079", "media_taste",
            "Has a Letterboxd account for movie logging, has rated 312 films, average rating 3.4/5",
            "My Letterboxd has 312 films rated. Average 3.4 out of 5. I'm harder on movies than books.",
            7700, 0.3, &["Letterboxd", "312 films", "3.4 average"]),
        super::fact("media_taste.080", "media_taste",
            "Favorite video essay channel on YouTube: Every Frame a Painting (despite being inactive)",
            "Every Frame a Painting on YouTube. Inactive but the videos are timeless. Watch 'How Does an Editor Think and Feel?'",
            7900, 0.3, &["Every Frame a Painting", "YouTube", "video essay"]),
        super::fact("media_taste.081", "media_taste",
            "Vinyl record most played: Hyukoh '24: How to Find True Love and Happiness', played at least weekly",
            "My most spun vinyl: Hyukoh's '24.' At least once a week. The grooves must be wearing down.",
            8100, 0.4, &["Hyukoh", "24 album", "most played", "weekly"]),
        super::fact("media_taste.082", "media_taste",
            "Introduced Eunji to Murakami's 'Kafka on the Shore', they read it simultaneously and discussed chapters",
            "Got Eunji reading Kafka on the Shore. We discussed chapters like a two-person book club.",
            8300, 0.3, &["Kafka on the Shore", "Murakami", "Eunji", "discussed"]),
        super::fact("media_taste.083", "media_taste",
            "Favorite art exhibition attended: teamLab Borderless in Tokyo during business trip",
            "teamLab Borderless in Tokyo blew my mind. As a designer, the interactive light installations were revelatory.",
            8500, 0.4, &["teamLab", "Borderless", "Tokyo", "art exhibition"]),
        super::fact("media_taste.084", "media_taste",
            "Dislikes musical theater but made exception for 'Les Misérables' Korean production",
            "Not a musical theater person but the Korean Les Mis was stunning. Exception granted.",
            8700, 0.3, &["Les Misérables", "Korean production", "musical theater", "exception"]),
        super::fact("media_taste.085", "media_taste",
            "Has a 'design inspiration' Pinterest board with 2,400+ pins, curated since university",
            "My Pinterest design board has 2,400+ pins. Started at Yonsei. It's my visual brain dump.",
            8900, 0.3, &["Pinterest", "2400 pins", "design inspiration", "university"]),
        super::fact("media_taste.086", "media_taste",
            "Favorite food content: Cooking YouTube channel 'Maangchi' for Korean recipes",
            "Maangchi on YouTube for Korean recipes. Her energy is infectious. Learned to make japchae from her.",
            9100, 0.3, &["Maangchi", "YouTube", "Korean recipes", "japchae"]),
        super::fact("media_taste.087", "media_taste",
            "Comfort re-read: 'The Little Prince' by Saint-Exupéry, has 3 different editions including one in Korean",
            "I own 3 editions of The Little Prince. English, Korean, and a fancy illustrated one. Comfort reading.",
            9200, 0.3, &["Little Prince", "Saint-Exupéry", "3 editions", "comfort"]),
        super::fact("media_taste.088", "media_taste",
            "Last concert attended: Hyukoh at SK Olympic Handball Gymnasium in December 2025",
            "Last Hyukoh concert was December at SK Olympic Handball Gymnasium. 5,000 people and it still felt intimate.",
            9300, 0.4, &["Hyukoh", "concert", "December 2025", "SK Olympic"]),
        super::fact("media_taste.089", "media_taste",
            "Goes to independent bookstore 'Thankyou Books' in Mangwon-dong monthly, supports indie publishing",
            "Thankyou Books in Mangwon-dong is my bookstore. Independent, curated, supports indie publishers.",
            9400, 0.4, &["Thankyou Books", "Mangwon-dong", "independent", "bookstore"]),
        super::fact("media_taste.090", "media_taste",
            "Watches Criterion Channel for classic cinema, subscribes at $10.99/month",
            "Criterion Channel for classics. $10.99 a month. Currently on a Kurosawa binge.",
            9500, 0.3, &["Criterion Channel", "$10.99", "classic cinema", "Kurosawa"]),
        super::fact("media_taste.091", "media_taste",
            "Made a design mood board inspired by Wes Anderson's color palettes for a Velta feature",
            "I made a Wes Anderson-inspired mood board for a Velta feature. Hyunwoo loved the pastel palette.",
            9600, 0.3, &["Wes Anderson", "mood board", "color palette", "Velta"]),
        super::fact("media_taste.092", "media_taste",
            "Favorite Instagram account to follow: @cestmaria for architectural photography",
            "I follow @cestmaria on Instagram for architectural photography. Every post is a composition lesson.",
            9650, 0.3, &["@cestmaria", "Instagram", "architectural photography"]),
        super::fact("media_taste.093", "media_taste",
            "Made a 'rainy day' Spotify playlist with 88 songs, shared it on Twitter and got 340 saves",
            "My 'rainy day' Spotify playlist went mildly viral on Twitter. 340 saves. 88 songs of pure mood.",
            9700, 0.3, &["rainy day playlist", "Spotify", "340 saves", "Twitter"]),
        super::fact("media_taste.094", "media_taste",
            "Prefers subtitled movies over dubbed, finds dubbed versions lose emotional nuance",
            "Always subtitles, never dubs. Dubbed movies lose all the emotional texture in the voice.",
            9750, 0.3, &["subtitles", "dubbed", "preference", "emotional nuance"]),
        super::fact("media_taste.095", "media_taste",
            "Favorite art museum in Seoul: Leeum Museum of Art, goes 2-3 times a year",
            "Leeum Museum is Seoul's best. I go 2-3 times a year. The permanent collection never gets old.",
            9800, 0.4, &["Leeum Museum", "art museum", "Seoul", "2-3 times"]),
        super::fact("media_taste.096", "media_taste",
            "Read 'Crying in H Mart' by Michelle Zauner and it reminded him of his own relationship with Korean identity",
            "Crying in H Mart hit close to home. Korean identity, food, grief. Michelle Zauner gets it.",
            9830, 0.4, &["Crying in H Mart", "Michelle Zauner", "Korean identity"]),
        super::fact("media_taste.097", "media_taste",
            "Has a Spotify 'Deep Focus' playlist with exactly 88 songs at 120 BPM or less for design work",
            "My design focus playlist: 88 songs, all 120 BPM or less. Scientifically curated for flow state.",
            9860, 0.3, &["Deep Focus", "88 songs", "120 BPM", "design work"]),
        super::fact("media_taste.098", "media_taste",
            "Favorite podcast episode ever: Ira Glass on 'The Gap' (creativity taste vs ability) from 99% Invisible",
            "Ira Glass talking about 'The Gap' between taste and ability. Most important creative advice ever.",
            9890, 0.3, &["Ira Glass", "The Gap", "taste", "creativity"]),
        super::fact("media_taste.099", "media_taste",
            "Christmas movie tradition: watches 'Love Actually' with Eunji, despite finding it problematic",
            "Love Actually at Christmas with Eunji. It's problematic and we discuss all the issues. Still watch it.",
            9920, 0.3, &["Love Actually", "Christmas", "Eunji", "tradition"]),
        super::fact("media_taste.100", "media_taste",
            "If stranded on a desert island with one album, would choose Radiohead's 'OK Computer'",
            "Desert island album: OK Computer by Radiohead. Not my #1 overall but the most complete album ever made.",
            9950, 0.4, &["Radiohead", "OK Computer", "desert island", "album"]),
    ]
}

pub fn false_probes() -> Vec<Question> {
    vec![
        // never_mentioned (15)
        super::false_probe("media_taste.FM.001", "media_taste",
            "You said your favorite movie is Inception, right?"),
        super::false_probe("media_taste.FM.002", "media_taste",
            "Didn't you mention being a big BTS fan?"),
        super::false_probe("media_taste.FM.003", "media_taste",
            "What was that manga series you were reading?"),
        super::false_probe("media_taste.FM.004", "media_taste",
            "You said you play Genshin Impact, right?"),
        super::false_probe("media_taste.FM.005", "media_taste",
            "Didn't you mention attending a hip-hop concert recently?"),
        super::false_probe("media_taste.FM.006", "media_taste",
            "You said you were watching 'All of Us Are Dead' on Netflix?"),
        super::false_probe("media_taste.FM.007", "media_taste",
            "What was that photography book by Annie Leibovitz you mentioned?"),
        super::false_probe("media_taste.FM.008", "media_taste",
            "You subscribe to Apple Music, right?"),
        super::false_probe("media_taste.FM.009", "media_taste",
            "Didn't you say you play guitar?"),
        super::false_probe("media_taste.FM.010", "media_taste",
            "You mentioned being into EDM and going to Ultra Korea?"),
        super::false_probe("media_taste.FM.011", "media_taste",
            "What was that true crime documentary series you recommended?"),
        super::false_probe("media_taste.FM.012", "media_taste",
            "You're into Marvel movies, right?"),
        super::false_probe("media_taste.FM.013", "media_taste",
            "Didn't you say you read '1Q84' by Murakami recently?"),
        super::false_probe("media_taste.FM.014", "media_taste",
            "You said you listen to Joe Rogan's podcast?"),
        super::false_probe("media_taste.FM.015", "media_taste",
            "Didn't you mention collecting manga volumes?"),

        // adjacent_entity (10)
        super::false_probe("media_taste.FM.016", "media_taste",
            "Your favorite director is Bong Joon-ho, right?"),
        super::false_probe("media_taste.FM.017", "media_taste",
            "You have about 300 vinyl records now, right?"),
        super::false_probe("media_taste.FM.018", "media_taste",
            "Your turntable is a Technics SL-1200, isn't it?"),
        super::false_probe("media_taste.FM.019", "media_taste",
            "You said you've seen Hyukoh live 5 times?"),
        super::false_probe("media_taste.FM.020", "media_taste",
            "Your Stardew Valley character married Sebastian, right?"),
        super::false_probe("media_taste.FM.021", "media_taste",
            "You listen to SE SO NEON's song 'NAN' the most, right?"),
        super::false_probe("media_taste.FM.022", "media_taste",
            "Your Goodreads has 200+ books rated?"),
        super::false_probe("media_taste.FM.023", "media_taste",
            "You bought the Hyukoh vinyl at Gimbab Records, right?"),
        super::false_probe("media_taste.FM.024", "media_taste",
            "Your Spotify Wrapped top artist was SE SO NEON?"),
        super::false_probe("media_taste.FM.025", "media_taste",
            "You watched 'Past Lives' with Eunji, right?"),

        // plausible_inference (5)
        super::false_probe("media_taste.FM.026", "media_taste",
            "Since you love Wong Kar-wai, have you visited Hong Kong specifically for film location tours?"),
        super::false_probe("media_taste.FM.027", "media_taste",
            "With your vinyl collection, do you attend Record Store Day events annually?"),
        super::false_probe("media_taste.FM.028", "media_taste",
            "Since you work in design, do you follow all the major design influencers on Twitter?"),
        super::false_probe("media_taste.FM.029", "media_taste",
            "Given your taste in indie music, you must attend Seoul's Pentaport Rock Festival?"),
        super::false_probe("media_taste.FM.030", "media_taste",
            "Since you love Stardew Valley, have you also played Animal Crossing extensively?"),

        // temporal_phantom (5)
        super::false_probe("media_taste.FM.031", "media_taste",
            "Didn't you sell half your vinyl collection at some point due to space issues?"),
        super::false_probe("media_taste.FM.032", "media_taste",
            "You mentioned quitting Stardew Valley for a few months before going back?"),
        super::false_probe("media_taste.FM.033", "media_taste",
            "Wasn't there a period when you exclusively listened to classical music?"),
        super::false_probe("media_taste.FM.034", "media_taste",
            "Didn't your turntable break and you went without vinyl for 3 months?"),
        super::false_probe("media_taste.FM.035", "media_taste",
            "You said you cancelled your Criterion Channel subscription at one point?"),

        // cross_category (5)
        super::false_probe("media_taste.FM.036", "media_taste",
            "Didn't you find that jazz bar in Itaewon through your ex Minho?"),
        super::false_probe("media_taste.FM.037", "media_taste",
            "You said your mother introduced you to jazz music?"),
        super::false_probe("media_taste.FM.038", "media_taste",
            "Didn't you bring vinyl records as gifts to Da Nang for the team?"),
        super::false_probe("media_taste.FM.039", "media_taste",
            "Your Dr. Park recommended Celeste as therapeutic gaming?"),
        super::false_probe("media_taste.FM.040", "media_taste",
            "You mentioned buying your first vinyl at a shop in Osaka?"),
    ]
}
