use crate::types::{Fact, Question};

pub fn facts() -> Vec<Fact> {
    vec![
        // === CAT MOCHI (early turns) ===
        super::fact("pets_hobbies.001", "pets_hobbies",
            "Has a Scottish Fold cat named Mochi, adopted in September 2024 from a breeder in Ilsan",
            "Mochi! My Scottish Fold. Got him from a breeder in Ilsan, September 2024. Best decision ever.",
            70, 0.9, &["Mochi", "Scottish Fold", "September 2024", "Ilsan"]),
        super::fact("pets_hobbies.002", "pets_hobbies",
            "Mochi is a grey tabby with folded ears, weighs 4.8kg, born May 2024",
            "Mochi is grey tabby, folded ears, 4.8kg of pure attitude. Born May 2024.",
            120, 0.7, &["Mochi", "grey tabby", "4.8kg", "May 2024"]),
        super::fact("pets_hobbies.003", "pets_hobbies",
            "Mochi's favorite spot is the windowsill where Gerald the monstera is, watches birds for hours",
            "Mochi lives on the windowsill next to Gerald. Bird watching is his full-time job.",
            200, 0.5, &["Mochi", "windowsill", "birds", "Gerald"]),
        super::fact("pets_hobbies.004", "pets_hobbies",
            "Feeds Mochi Royal Canin Indoor cat food, twice daily at 7:30 AM and 6:30 PM",
            "Mochi eats Royal Canin Indoor. 7:30 AM and 6:30 PM sharp. He screams if I'm late.",
            250, 0.6, &["Mochi", "Royal Canin", "indoor", "7:30", "6:30"]),
        super::fact("pets_hobbies.005", "pets_hobbies",
            "Mochi's vet is Dr. Han at Yeonnam Animal Hospital, checkups every 6 months",
            "Mochi sees Dr. Han at Yeonnam Animal Hospital. Every 6 months. He hates the carrier.",
            350, 0.6, &["Mochi", "Dr. Han", "Yeonnam Animal Hospital", "6 months"]),
        super::fact("pets_hobbies.006", "pets_hobbies",
            "Mochi is neutered, had the procedure in November 2024, recovered quickly",
            "Mochi got neutered in November 2024. He was groggy for a day then back to causing chaos.",
            450, 0.5, &["Mochi", "neutered", "November 2024"]),
        super::fact("pets_hobbies.007", "pets_hobbies",
            "Cat supplies: automatic water fountain (Petkit Eversweet), covered litter box (Modkat), cardboard scratcher",
            "Mochi has a Petkit water fountain, Modkat litter box, and a cardboard scratcher he destroys weekly.",
            550, 0.4, &["Petkit", "Modkat", "scratcher", "water fountain"]),
        super::fact("pets_hobbies.008", "pets_hobbies",
            "Mochi's personality: affectionate but independent, follows him around the apartment but doesn't like being held",
            "Mochi follows me everywhere but won't let me hold him. Classic cat. He sits next to me, not on me.",
            650, 0.4, &["Mochi", "personality", "affectionate", "independent"]),
        super::fact("pets_hobbies.009", "pets_hobbies",
            "Monthly Mochi costs: food 45K, litter 25K, vet fund 30K, treats/toys 15K = about 115K won",
            "Mochi costs about 115K monthly. Food, litter, vet savings, treats. He's worth every won.",
            750, 0.4, &["Mochi", "costs", "115K", "monthly"]),
        super::fact("pets_hobbies.010", "pets_hobbies",
            "Mochi has an Instagram account @mochithefoldie with 847 followers, posts 2-3 times a week",
            "I made Mochi an Instagram: @mochithefoldie. 847 followers. He's more popular than me.",
            900, 0.4, &["Mochi", "Instagram", "@mochithefoldie", "847 followers"]),

        // === FILM PHOTOGRAPHY ===
        super::fact("pets_hobbies.011", "pets_hobbies",
            "Shoots film photography with a Canon AE-1, bought used at a camera shop in Chungmuro for 350,000 won",
            "My Canon AE-1 is from a shop in Chungmuro. 350K won used. That camera has soul.",
            100, 0.8, &["Canon AE-1", "film photography", "Chungmuro", "350K"]),
        super::fact("pets_hobbies.012", "pets_hobbies",
            "Primary film stock: Kodak Portra 400 for color, Ilford HP5 Plus 400 for black and white",
            "Portra 400 for color, Ilford HP5 for B&W. The two films I'll never stop buying.",
            300, 0.6, &["Portra 400", "Ilford HP5", "film stock", "color", "B&W"]),
        super::fact("pets_hobbies.013", "pets_hobbies",
            "Develops B&W film at home in the bathroom, color (C-41) when ambitious, sends to Carmencita Lab otherwise",
            "B&W I develop at home. Color film goes to Carmencita Lab in Itaewon when I'm lazy.",
            500, 0.5, &["develop", "B&W", "home", "Carmencita Lab", "Itaewon"]),
        super::fact("pets_hobbies.014", "pets_hobbies",
            "Scans negatives with an Epson V600 flatbed scanner, saved up for 3 months to buy it",
            "My Epson V600 scanner was a 3-month savings goal. Worth it. No more paying for lab scans.",
            700, 0.5, &["Epson V600", "scanner", "negatives", "flatbed"]),
        super::fact("pets_hobbies.015", "pets_hobbies",
            "Has shot approximately 85 rolls of film since starting in 2023, averages about 3 rolls per month",
            "About 85 rolls shot since I started in 2023. 3 rolls a month. Film is expensive but addictive.",
            850, 0.5, &["85 rolls", "3 per month", "2023", "film"]),
        super::fact("pets_hobbies.016", "pets_hobbies",
            "Favorite photo ever taken: Eunji laughing at Yongmeori Beach in Jeju, shot on Portra 400, golden hour",
            "My favorite photo: Eunji laughing at Yongmeori Beach. Portra 400, golden hour. It's on my wall.",
            3700, 0.5, &["favorite photo", "Eunji", "Yongmeori", "Portra 400"]),

        // === SOURDOUGH BAKING ===
        super::fact("pets_hobbies.017", "pets_hobbies",
            "Maintains a sourdough starter named Steve, started in January 2025 from Ken Forkish's book instructions",
            "My sourdough starter Steve was born January 2025. Named after the bread scientist energy.",
            150, 0.7, &["sourdough", "Steve", "starter", "January 2025"]),
        super::update("pets_hobbies.018", "pets_hobbies",
            "Steve the sourdough starter died in July 2025 when he forgot to feed it during a busy work week",
            "Steve is dead. Forgot to feed him during a crunch week. RIP Steve. I literally mourned a jar of bacteria.",
            1500, 0.6, &["Steve", "died", "forgot to feed", "July 2025"],
            "sourdough_starter", 1),
        super::update("pets_hobbies.019", "pets_hobbies",
            "Started Steve Jr. (new sourdough starter) in August 2025, now keeps a backup in the fridge",
            "Steve Jr. lives! Started August 2025. This time I keep a backup in the fridge. Lesson learned.",
            2000, 0.5, &["Steve Jr", "new starter", "August 2025", "backup"],
            "sourdough_starter", 2),
        super::fact("pets_hobbies.020", "pets_hobbies",
            "Bakes sourdough bread every weekend, usually on Saturday morning, takes about 18 hours from start to finish",
            "Saturday morning sourdough routine. 18 hours total: mix, bulk ferment, shape, cold proof, bake Sunday.",
            400, 0.5, &["sourdough", "Saturday", "baking", "18 hours"]),
        super::fact("pets_hobbies.021", "pets_hobbies",
            "Uses a Lodge cast iron combo cooker for baking, produces best oven spring and crust",
            "Lodge cast iron combo cooker for baking. The oven spring you get is incredible. Crackly crust.",
            600, 0.4, &["Lodge", "cast iron", "combo cooker", "oven spring"]),
        super::fact("pets_hobbies.022", "pets_hobbies",
            "Best loaf ever: scored a wheat ear design that opened perfectly, Eunji called it 'art bread'",
            "Best loaf: wheat ear scoring that opened perfectly. Eunji called it 'art bread.' I was so proud.",
            4200, 0.3, &["best loaf", "wheat ear", "scoring", "art bread"]),

        // === VINYL COLLECTION ===
        super::fact("pets_hobbies.023", "pets_hobbies",
            "Vinyl record collection: approximately 215 records, mostly jazz (40%), Korean indie (35%), and classic rock (25%)",
            "215 records. 40% jazz, 35% Korean indie, 25% classic rock. Two Kallax shelves worth.",
            180, 0.7, &["vinyl", "215 records", "jazz", "Korean indie", "classic rock"]),
        super::fact("pets_hobbies.024", "pets_hobbies",
            "Most valuable vinyl: original pressing of Miles Davis 'Kind of Blue' bought at a Busan record fair for 120,000 won",
            "My most valuable vinyl: original Kind of Blue pressing. Busan record fair, 120K won. Treasure.",
            400, 0.5, &["Kind of Blue", "original pressing", "Busan", "120K", "most valuable"]),
        super::fact("pets_hobbies.025", "pets_hobbies",
            "Favorite record shops: Dope Records (Itaewon), Gimbab Records (Hongdae), and Seoul Records (Euljiro)",
            "Record shop circuit: Dope Records Itaewon, Gimbab Records Hongdae, Seoul Records Euljiro. Regular rotation.",
            600, 0.5, &["Dope Records", "Gimbab Records", "Seoul Records", "record shops"]),
        super::fact("pets_hobbies.026", "pets_hobbies",
            "Cleans records with an AudioQuest carbon fiber brush before every play",
            "I brush every record with an AudioQuest carbon fiber brush before playing. Vinyl care is real.",
            1100, 0.3, &["AudioQuest", "carbon fiber", "brush", "cleaning"]),

        // === BOULDERING ===
        super::fact("pets_hobbies.027", "pets_hobbies",
            "Started bouldering in April 2025, now climbs every Saturday afternoon at Climbing Park Hongdae",
            "Bouldering since April 2025. Every Saturday at Climbing Park in Hongdae. Addicted.",
            380, 0.6, &["bouldering", "April 2025", "Saturday", "Climbing Park"]),
        super::fact("pets_hobbies.028", "pets_hobbies",
            "Climbing shoes: La Sportiva Tarantulace, beginner-intermediate level, size 265mm",
            "My climbing shoes are La Sportiva Tarantulace. 265mm. They hurt but they grip.",
            800, 0.4, &["La Sportiva", "Tarantulace", "climbing shoes", "265mm"]),
        super::fact("pets_hobbies.029", "pets_hobbies",
            "Bouldering partner is always Soyeon from work, they spot each other and share beta",
            "Soyeon and I always climb together. She spots me, I spot her. We share beta on problems.",
            500, 0.5, &["Soyeon", "bouldering", "partner", "spotting", "beta"]),
        super::fact("pets_hobbies.030", "pets_hobbies",
            "Best climbing day: sent 3 V4 problems in one session, Soyeon filmed the last one",
            "Best session ever: 3 V4 sends in one day. Soyeon filmed the last one. It's on my phone forever.",
            2500, 0.4, &["V4", "3 sends", "best session", "filmed"]),

        // === UPDATE CHAIN: Bouldering gear evolution ===
        super::update("pets_hobbies.031", "pets_hobbies",
            "Bought own chalk bag (Black Diamond) and Mammut loose chalk instead of using gym chalk",
            "Got my own chalk setup: Black Diamond bag, Mammut loose chalk. No more gym chalk bucket.",
            1200, 0.4, &["Black Diamond", "chalk bag", "Mammut", "own gear"],
            "climbing_gear", 1),
        super::update("pets_hobbies.032", "pets_hobbies",
            "Upgraded climbing shoes to La Sportiva Solution, more aggressive downturn for overhangs",
            "Upgraded to La Sportiva Solution. More aggressive downturn. V5 problems need better shoes.",
            5500, 0.4, &["La Sportiva", "Solution", "upgraded", "aggressive"],
            "climbing_gear", 2),

        // === UPDATE CHAIN: Photography project ===
        super::update("pets_hobbies.033", "pets_hobbies",
            "Started a photography project: 'Seoul in 36 Frames' - one roll of film per neighborhood",
            "My project 'Seoul in 36 Frames': one roll per neighborhood. 15 neighborhoods done so far.",
            1400, 0.5, &["Seoul in 36 Frames", "project", "neighborhoods", "one roll"],
            "photo_project", 1),
        super::update("pets_hobbies.034", "pets_hobbies",
            "Printed 20 photos from the Seoul project, mounted them for a small exhibition at Cafe Onion in April 2026",
            "20 prints from my Seoul project going up at Cafe Onion in April! My first 'exhibition.' Tiny but mine.",
            8000, 0.6, &["exhibition", "Cafe Onion", "20 prints", "April 2026"],
            "photo_project", 2),

        // === UPDATE CHAIN: Mochi health ===
        super::update("pets_hobbies.035", "pets_hobbies",
            "Mochi had a urinary tract issue in November 2025, required special diet and antibiotics for 2 weeks",
            "Mochi had a UTI in November. Two weeks of antibiotics and special diet. Scary but he recovered.",
            2800, 0.7, &["Mochi", "UTI", "antibiotics", "November 2025"],
            "mochi_health", 1),
        super::update("pets_hobbies.036", "pets_hobbies",
            "Switched Mochi to Royal Canin Urinary S/O food after the UTI, vet recommended for prevention",
            "Mochi is on Royal Canin Urinary S/O now. Dr. Han recommended it to prevent another UTI.",
            3200, 0.5, &["Mochi", "Royal Canin", "Urinary S/O", "prevention"],
            "mochi_health", 2),
        super::update("pets_hobbies.037", "pets_hobbies",
            "Mochi fully recovered, urinalysis clear at March 2026 checkup, can switch back to regular food gradually",
            "March checkup: Mochi's urinalysis is clear! Can gradually switch back to regular food. Relief.",
            8500, 0.5, &["Mochi", "recovered", "urinalysis", "March 2026"],
            "mochi_health", 3),

        // === UPDATE CHAIN: Vinyl setup upgrade ===
        super::update("pets_hobbies.038", "pets_hobbies",
            "Considering upgrading turntable to a Rega Planar 3, saving up (costs about 900,000 won)",
            "I want a Rega Planar 3. 900K won. Saving up slowly. The LP120X is good but the Rega is next level.",
            3500, 0.5, &["Rega Planar 3", "turntable", "upgrade", "900K"],
            "turntable_upgrade", 1),
        super::update("pets_hobbies.039", "pets_hobbies",
            "Decided to keep the Audio-Technica for now, put turntable upgrade money toward the apartment move instead",
            "Turntable upgrade postponed. That 900K is going toward the Mangwon-dong move. Priorities.",
            7500, 0.4, &["turntable", "postponed", "move", "priorities"],
            "turntable_upgrade", 2),

        // === UPDATE CHAIN: Sourdough skills ===
        super::update("pets_hobbies.040", "pets_hobbies",
            "Mastered basic country loaf, now experimenting with focaccia and pizza dough using Steve Jr.",
            "I've moved beyond just country loaves. Focaccia, pizza dough. Steve Jr. is versatile.",
            4000, 0.4, &["focaccia", "pizza dough", "experimenting", "Steve Jr"],
            "sourdough_skills", 1),
        super::update("pets_hobbies.041", "pets_hobbies",
            "Made sourdough cinnamon rolls for the office, received 'best baker at Velta' unofficial title",
            "Brought sourdough cinnamon rolls to the office. I am now officially 'Velta's Baker.' Hyunwoo's words.",
            6000, 0.4, &["cinnamon rolls", "office", "Velta's Baker", "Hyunwoo"],
            "sourdough_skills", 2),

        // === UPDATE CHAIN: Mochi and Eunji ===
        super::update("pets_hobbies.042", "pets_hobbies",
            "Mochi initially hid from Eunji under the bed for the first 3 visits, now sleeps on her lap",
            "Mochi hid from Eunji for her first 3 visits. Now he sleeps on her lap. Traitor chose her over me.",
            3000, 0.4, &["Mochi", "Eunji", "hiding", "lap", "warming up"],
            "mochi_eunji", 1),
        super::update("pets_hobbies.043", "pets_hobbies",
            "Eunji bought Mochi a cat tree from Coupang (120,000 won), he uses the top perch exclusively",
            "Eunji bought Mochi a cat tree. 120K from Coupang. He only uses the top perch. Cat logic.",
            5000, 0.4, &["cat tree", "Coupang", "120K", "Eunji", "top perch"],
            "mochi_eunji", 2),

        // === UPDATE CHAIN: New hobby attempt ===
        super::update("pets_hobbies.044", "pets_hobbies",
            "Tried pottery class at a studio in Ikseon-dong in January 2026, found it meditative",
            "Tried pottery in Ikseon-dong. Making a bowl on the wheel is incredibly meditative.",
            4500, 0.5, &["pottery", "Ikseon-dong", "January 2026", "meditative"],
            "pottery_attempt", 1),
        super::update("pets_hobbies.045", "pets_hobbies",
            "Attended 6 pottery classes total, made 4 bowls and 2 cups, decided it's too time-consuming to continue regularly",
            "Did 6 pottery classes. Made some bowls and cups. Love it but can't add another regular hobby.",
            6500, 0.4, &["pottery", "6 classes", "bowls", "cups", "time-consuming"],
            "pottery_attempt", 2),

        // === MISCELLANEOUS HOBBIES ===
        super::fact("pets_hobbies.046", "pets_hobbies",
            "Collects vintage postcards from flea markets, has about 60 postcards from Seoul and Busan flea markets",
            "I collect vintage postcards. About 60 now. Seoul and Busan flea markets are my hunting grounds.",
            1000, 0.4, &["postcards", "vintage", "flea markets", "60", "collecting"]),
        super::fact("pets_hobbies.047", "pets_hobbies",
            "Sunday morning routine includes feeding Mochi, making coffee, and tending to plants (monstera Gerald, herbs, 2 succulents)",
            "Sunday mornings: feed Mochi, coffee, plants. Gerald the monstera, herbs on the balcony, and 2 succulents.",
            500, 0.4, &["Sunday", "Mochi", "plants", "Gerald", "succulents"]),
        super::fact("pets_hobbies.048", "pets_hobbies",
            "Has 2 succulents on the kitchen windowsill named Ross and Rachel, named by Eunji",
            "Eunji named my succulents Ross and Rachel. I didn't have a say. They seem happy.",
            2200, 0.3, &["succulents", "Ross", "Rachel", "Eunji", "kitchen"]),
        super::fact("pets_hobbies.049", "pets_hobbies",
            "Mochi's favorite toy: a feather wand called 'Da Bird', goes absolutely crazy for it",
            "Da Bird feather wand turns Mochi into a feral hunter. He does backflips for that thing.",
            1300, 0.4, &["Da Bird", "feather wand", "Mochi", "favorite toy"]),
        super::fact("pets_hobbies.050", "pets_hobbies",
            "Participates in Seoul Photo Walk meetup group monthly, meets other film photographers",
            "Seoul Photo Walk meetup once a month. Great group of film photographers. We shoot together.",
            1600, 0.4, &["Seoul Photo Walk", "meetup", "monthly", "film photographers"]),
        super::fact("pets_hobbies.051", "pets_hobbies",
            "Film developing chemicals stored in the bathroom cabinet: Kodak D-76 developer, Ilford Rapid Fixer",
            "My bathroom cabinet has D-76 developer and Ilford fixer. Eunji thinks it's weird. She's not wrong.",
            1800, 0.3, &["D-76", "Ilford fixer", "chemicals", "bathroom"]),
        super::fact("pets_hobbies.052", "pets_hobbies",
            "Tried making croissants from scratch once, took 2 days, result was 'okay' but not worth repeating",
            "I tried croissants from scratch. Two days of laminating butter. Result: mediocre. Never again.",
            2000, 0.3, &["croissants", "2 days", "laminating", "mediocre"]),
        super::fact("pets_hobbies.053", "pets_hobbies",
            "Mochi sleeps on the bed at night, specifically on the corner near the feet, weighing down the blanket",
            "Mochi sleeps at the foot of the bed. Specifically in the exact corner that pins down the blanket.",
            2200, 0.3, &["Mochi", "sleeps", "bed", "corner", "blanket"]),
        super::fact("pets_hobbies.054", "pets_hobbies",
            "Has a dedicated film camera bag: a small Domke F-5XB, fits Canon AE-1 and 3 rolls of film",
            "My Domke F-5XB camera bag fits the AE-1 and 3 rolls. Compact and functional. Perfect for walks.",
            2400, 0.3, &["Domke", "F-5XB", "camera bag", "Canon AE-1"]),
        super::fact("pets_hobbies.055", "pets_hobbies",
            "Sourdough hydration experiments: settled on 75% hydration for the best crumb-to-crust ratio",
            "75% hydration is my sweet spot for sourdough. Good open crumb without being impossible to shape.",
            2600, 0.3, &["hydration", "75%", "sourdough", "crumb"]),
        super::fact("pets_hobbies.056", "pets_hobbies",
            "Mochi's grooming: brushes him 3 times a week with a Furminator, sheds heavily in spring",
            "Mochi gets brushed 3 times a week with a Furminator. Spring shedding is a war zone.",
            2800, 0.4, &["Mochi", "Furminator", "grooming", "shedding", "3 times"]),
        super::fact("pets_hobbies.057", "pets_hobbies",
            "Board game collection: owns 8 board games, favorites are Wingspan, Patchwork (2-player with Eunji), and Azul",
            "8 board games owned. Wingspan is #1. Patchwork is our go-to 2-player with Eunji. Azul for aesthetics.",
            3000, 0.4, &["board games", "8 games", "Wingspan", "Patchwork", "Azul"]),
        super::fact("pets_hobbies.058", "pets_hobbies",
            "Film photography cost: about 150,000 won per month (film + development + scanning)",
            "Film photography costs me about 150K monthly. Film isn't cheap but digital just doesn't feel the same.",
            3200, 0.4, &["film cost", "150K", "monthly", "photography"]),
        super::fact("pets_hobbies.059", "pets_hobbies",
            "Mochi's microchip registered at the city hall, linked to phone number and address",
            "Mochi is microchipped. Registered with the city. If he ever escapes, he's coming home.",
            3400, 0.3, &["Mochi", "microchip", "registered", "city hall"]),
        super::fact("pets_hobbies.060", "pets_hobbies",
            "Second film camera: a Contax T2 compact for everyday carry, bought in December 2025 for 800,000 won",
            "I bought a Contax T2 in December for everyday carry. 800K won. Point-and-shoot perfection.",
            3600, 0.5, &["Contax T2", "December 2025", "800K", "everyday carry"]),
        super::fact("pets_hobbies.061", "pets_hobbies",
            "Vinyl listening ritual: Wednesday no-screen nights, picks one album, dims the lights, full listen",
            "Wednesday vinyl nights: pick an album, dim the lights, listen front to back. No phone, no interruption.",
            3800, 0.5, &["vinyl", "Wednesday", "ritual", "full listen", "no phone"]),
        super::fact("pets_hobbies.062", "pets_hobbies",
            "Mochi's vet costs in 2025: approximately 380,000 won total (checkups, UTI treatment, vaccination)",
            "Mochi's vet bill for 2025: about 380K. The UTI was most of it. Pet insurance next year maybe.",
            4000, 0.4, &["Mochi", "vet costs", "380K", "2025"]),
        super::fact("pets_hobbies.063", "pets_hobbies",
            "Has a Polaroid Now camera for instant photos at gatherings, uses Polaroid i-Type film (expensive at 20K per 8 shots)",
            "I have a Polaroid Now for gatherings. i-Type film is 20K for 8 shots. Expensive but instant magic.",
            4200, 0.3, &["Polaroid Now", "i-Type", "instant", "20K"]),
        super::fact("pets_hobbies.064", "pets_hobbies",
            "Sourdough gift tradition: gives a loaf to Mrs. Kim (neighbor) every other week",
            "Mrs. Kim gets a sourdough loaf every other week. She gives me tteok, I give her bread. Fair trade.",
            4400, 0.4, &["sourdough", "Mrs. Kim", "gift", "every other week"]),
        super::fact("pets_hobbies.065", "pets_hobbies",
            "Bouldering achievement wall in his phone: screenshots of every new grade sent for the first time",
            "I screenshot every first send of a new grade. V1 through V5 documented. V6 is the next milestone.",
            4600, 0.3, &["bouldering", "screenshots", "grades", "first send"]),
        super::fact("pets_hobbies.066", "pets_hobbies",
            "Mochi and Gerald the monstera coexist peacefully - Mochi ignores the plant, doesn't chew on it",
            "Miracle: Mochi doesn't eat Gerald. They share the windowsill in harmony. I got lucky.",
            4800, 0.3, &["Mochi", "Gerald", "monstera", "coexist", "doesn't eat"]),
        super::fact("pets_hobbies.067", "pets_hobbies",
            "Record fair attendance: goes to Seoul Record Fair at Nodeul Island every spring and fall",
            "Seoul Record Fair at Nodeul Island. Spring and fall. I set a budget and always exceed it.",
            5000, 0.4, &["Seoul Record Fair", "Nodeul Island", "spring", "fall"]),
        super::fact("pets_hobbies.068", "pets_hobbies",
            "Taught Eunji to use the Canon AE-1, she shot her first roll in Gyeongju (mostly blurry but charming)",
            "Eunji shot her first roll on my Canon AE-1 in Gyeongju. Mostly blurry but beautifully so.",
            5200, 0.3, &["Eunji", "Canon AE-1", "first roll", "Gyeongju"]),
        super::fact("pets_hobbies.069", "pets_hobbies",
            "Cat sitter for Mochi when traveling: neighbor Mrs. Kim or Soojin if available",
            "Cat sitting: Mrs. Kim is first choice, Soojin as backup. They both spoil Mochi rotten.",
            5400, 0.4, &["cat sitter", "Mrs. Kim", "Soojin", "Mochi"]),
        super::fact("pets_hobbies.070", "pets_hobbies",
            "Tried making bagels with sourdough, result was too chewy but flavor was excellent",
            "Sourdough bagels: too chewy but the flavor was incredible. Need to adjust the boiling time.",
            5600, 0.3, &["bagels", "sourdough", "chewy", "flavor"]),
        super::fact("pets_hobbies.071", "pets_hobbies",
            "Most expensive vinyl purchase ever: Chet Baker 'Chet Baker Sings' Japanese pressing, 150,000 won at Gimbab Records",
            "Most I've ever spent on one record: Chet Baker Sings Japanese pressing. 150K at Gimbab Records. Zero regrets.",
            5800, 0.4, &["Chet Baker", "150K", "Gimbab Records", "Japanese pressing"]),
        super::fact("pets_hobbies.072", "pets_hobbies",
            "Mochi has figured out how to open the bathroom door by pushing the handle down, had to install a latch",
            "Mochi learned to open the bathroom door. Push the lever handle down. Had to install a latch. He's too smart.",
            6200, 0.3, &["Mochi", "bathroom door", "handle", "latch", "smart"]),
        super::fact("pets_hobbies.073", "pets_hobbies",
            "Climbing Park Hongdae entry fee: 15,000 won per session including shoe rental, owns own shoes now",
            "Climbing Park is 15K per session with shoes. Now that I own shoes, I think it might be cheaper.",
            6400, 0.3, &["Climbing Park", "15K", "entry fee", "shoe rental"]),
        super::fact("pets_hobbies.074", "pets_hobbies",
            "Steve Jr. the sourdough starter has been shared with 3 friends, his 'sourdough babies'",
            "I've given Steve Jr. babies to 3 friends. My sourdough grandchildren are out there somewhere.",
            6600, 0.3, &["Steve Jr", "shared", "3 friends", "sourdough babies"]),
        super::fact("pets_hobbies.075", "pets_hobbies",
            "Favorite darkroom moment: watching an image slowly appear in the developer tray under red safelight",
            "Best moment in darkroom: image appearing in the developer. Red safelight glowing. Pure magic.",
            6800, 0.3, &["darkroom", "developer", "red safelight", "magic"]),
        super::fact("pets_hobbies.076", "pets_hobbies",
            "Mochi's quirk: runs around the apartment at 3 AM for exactly 5 minutes (cat zoomies), then sleeps",
            "3 AM zoomies. Five minutes of chaos. Then silence. Every single night. Cats are aliens.",
            7000, 0.3, &["Mochi", "zoomies", "3 AM", "5 minutes"]),
        super::fact("pets_hobbies.077", "pets_hobbies",
            "Film photography mentor: met a retired photographer named Mr. Oh at Seoul Photo Walk who teaches composition",
            "Mr. Oh from Photo Walk is my informal mentor. Retired photographer. His composition advice is gold.",
            7200, 0.4, &["Mr. Oh", "mentor", "retired photographer", "composition"]),
        super::fact("pets_hobbies.078", "pets_hobbies",
            "Sourdough flour: uses Korean organic bread flour from Beksul brand, 2.5kg bag lasts about 2 weeks",
            "Beksul organic bread flour for sourdough. 2.5kg bag every 2 weeks. Quality flour makes quality bread.",
            7400, 0.3, &["Beksul", "bread flour", "organic", "2.5kg"]),
        super::fact("pets_hobbies.079", "pets_hobbies",
            "Has framed 12 of his best film photos around the apartment: 5 in living room, 4 in office, 3 in bedroom",
            "12 framed photos around the apartment from my film rolls. 5 living room, 4 office, 3 bedroom.",
            7600, 0.3, &["framed photos", "12", "film", "apartment"]),
        super::fact("pets_hobbies.080", "pets_hobbies",
            "Mochi's Instagram most-liked post: 2,340 likes on a photo of him inside a cardboard box wearing a tiny hat",
            "Mochi's most viral post: 2,340 likes. Cardboard box, tiny hat. Internet cats doing internet cat things.",
            7800, 0.3, &["Mochi", "Instagram", "2340 likes", "box", "hat"]),
        super::fact("pets_hobbies.081", "pets_hobbies",
            "Tried film photography with an expired Fujifilm Superia 400 roll, got interesting color shifts and grain",
            "Shot an expired Superia 400 roll. Crazy color shifts and grain. Accidental art.",
            8200, 0.3, &["expired film", "Superia 400", "color shifts", "grain"]),
        super::fact("pets_hobbies.082", "pets_hobbies",
            "Bouldering calluses on hands are noticeable, Eunji calls them 'adventure hands'",
            "My hands are all calloused from climbing. Eunji calls them 'adventure hands.' I like that.",
            8400, 0.3, &["calluses", "hands", "bouldering", "Eunji", "adventure hands"]),
        super::fact("pets_hobbies.083", "pets_hobbies",
            "Plant count in apartment: Gerald (monstera), 2 succulents (Ross & Rachel), basil, perilla, chives = 6 total",
            "Total plant count: 6. Gerald, Ross, Rachel, basil, perilla, chives. Mini urban garden.",
            8600, 0.3, &["plants", "6 total", "Gerald", "Ross", "Rachel"]),
        super::fact("pets_hobbies.084", "pets_hobbies",
            "Mochi has a cat passport for potential travel, though he's never left Seoul",
            "Mochi has a cat passport but he's never left Seoul. Prepared for anything.",
            8800, 0.3, &["Mochi", "cat passport", "travel", "Seoul"]),
        super::fact("pets_hobbies.085", "pets_hobbies",
            "Sourdough discard recipe: makes pancakes with the discard every Tuesday morning",
            "Tuesday morning sourdough discard pancakes. Waste nothing. They're actually delicious.",
            9000, 0.3, &["sourdough discard", "pancakes", "Tuesday", "morning"]),
        super::fact("pets_hobbies.086", "pets_hobbies",
            "Photography bucket list: wants to shoot in Iceland (black sand beaches), Morocco (blue city), and Tokyo (night streets)",
            "Photography bucket list: Iceland's black sand, Morocco's blue city, Tokyo's neon. The light in each place...",
            9100, 0.3, &["photography bucket list", "Iceland", "Morocco", "Tokyo"]),
        super::fact("pets_hobbies.087", "pets_hobbies",
            "Latest vinyl acquisition: SE SO NEON's 'Nonadaptation' LP, bought at their concert merch table",
            "Got SE SO NEON's 'Nonadaptation' LP at the merch table. Played it 3 times the first night home.",
            9200, 0.3, &["SE SO NEON", "Nonadaptation", "LP", "merch"]),
        super::fact("pets_hobbies.088", "pets_hobbies",
            "Mochi responds to his name and the sound of the treat bag. Ignores everything else.",
            "Mochi knows his name and the treat bag sound. All other human communication is beneath him.",
            9300, 0.3, &["Mochi", "responds", "name", "treat bag"]),
        super::fact("pets_hobbies.089", "pets_hobbies",
            "Built a small shelf specifically for sourdough supplies: flour, banneton basket, lame, kitchen scale",
            "I have a dedicated sourdough shelf: flour, banneton, lame, scale. Very organized baker energy.",
            9400, 0.3, &["sourdough shelf", "banneton", "lame", "kitchen scale"]),
        super::fact("pets_hobbies.090", "pets_hobbies",
            "Favorite bouldering problem ever: a dyno on an overhang at Climbing Park, took 8 sessions to complete",
            "There's this dyno on an overhang at Climbing Park. Took me 8 sessions. The send was euphoric.",
            9500, 0.4, &["dyno", "overhang", "8 sessions", "Climbing Park"]),
        super::fact("pets_hobbies.091", "pets_hobbies",
            "Mochi has a scratching post but still scratches the corner of the living room sofa",
            "Mochi has a perfectly good scratching post. He uses the sofa corner instead. Classic.",
            9550, 0.3, &["Mochi", "scratching", "sofa corner", "scratching post"]),
        super::fact("pets_hobbies.092", "pets_hobbies",
            "Makes sourdough pizza every other Friday, Eunji handles the toppings, his dough is the star",
            "Friday sourdough pizza with Eunji. I make the dough, she does toppings. Team effort.",
            9600, 0.4, &["sourdough pizza", "Friday", "Eunji", "toppings"]),
        super::fact("pets_hobbies.093", "pets_hobbies",
            "Film photography vs digital: believes film forces intentionality because you can't chimm (review) after each shot",
            "Film forces you to think before shooting. No chimming. 36 chances per roll. Makes you a better photographer.",
            9650, 0.4, &["film vs digital", "intentionality", "36 chances"]),
        super::fact("pets_hobbies.094", "pets_hobbies",
            "Mochi's annual vaccination schedule: FVRCP combo vaccine in September, rabies every 3 years",
            "Mochi gets FVRCP in September annually. Rabies every 3 years. Dr. Han handles everything.",
            9700, 0.3, &["Mochi", "vaccination", "FVRCP", "September"]),
        super::fact("pets_hobbies.095", "pets_hobbies",
            "Climbed outdoors at Bukhansan once, found it terrifying but took amazing film photos of the granite faces",
            "Bukhansan outdoor climbing: terrifying. But the film photos of granite faces in afternoon light... worth the fear.",
            9750, 0.3, &["Bukhansan", "outdoor climbing", "granite", "film photos"]),
        super::fact("pets_hobbies.096", "pets_hobbies",
            "Vinyl storage: records are alphabetized within genre sections, each record has an anti-static inner sleeve",
            "Records are alphabetized within genres. Anti-static inner sleeves on every one. I take this seriously.",
            9800, 0.3, &["vinyl storage", "alphabetized", "anti-static", "sleeves"]),
        super::fact("pets_hobbies.097", "pets_hobbies",
            "Eunji and Mochi have a morning routine: she makes breakfast, he sits on the kitchen counter watching her",
            "Eunji and Mochi's morning thing: she cooks, he supervises from the counter. They have a bond.",
            9830, 0.3, &["Eunji", "Mochi", "morning", "counter", "watching"]),
        super::fact("pets_hobbies.098", "pets_hobbies",
            "Best sourdough recipe tweak: adding 10% whole wheat flour for nuttier flavor, discovered by accident",
            "My secret: 10% whole wheat in the sourdough. Nuttier flavor. Discovered by accident when I ran out of bread flour.",
            9860, 0.3, &["whole wheat", "10%", "sourdough", "nuttier"]),
        super::fact("pets_hobbies.099", "pets_hobbies",
            "Mochi's estimated indoor territory: has claimed 4 specific spots - windowsill, cat tree top, bed corner, bathroom sink",
            "Mochi's empire: windowsill, cat tree top, bed corner, bathroom sink. Four territories. Rotating occupancy.",
            9900, 0.3, &["Mochi", "territories", "4 spots", "windowsill", "cat tree"]),
        super::fact("pets_hobbies.100", "pets_hobbies",
            "Hobbies philosophy: all hobbies involve patience and slow craft - sourdough, film, vinyl, bouldering",
            "All my hobbies require patience. Sourdough rises slow. Film develops slow. Vinyl plays at its own pace. Bouldering is problem-solving. I love slow crafts.",
            9950, 0.4, &["patience", "slow craft", "philosophy", "hobbies"]),
    ]
}

pub fn false_probes() -> Vec<Question> {
    vec![
        // never_mentioned (15)
        super::false_probe("pets_hobbies.FM.001", "pets_hobbies",
            "You said you have a dog too, right? What breed?"),
        super::false_probe("pets_hobbies.FM.002", "pets_hobbies",
            "Didn't you mention having a fish tank?"),
        super::false_probe("pets_hobbies.FM.003", "pets_hobbies",
            "What was that digital camera you bought recently?"),
        super::false_probe("pets_hobbies.FM.004", "pets_hobbies",
            "You said you took up painting as a hobby?"),
        super::false_probe("pets_hobbies.FM.005", "pets_hobbies",
            "Didn't you mention doing woodworking as a hobby?"),
        super::false_probe("pets_hobbies.FM.006", "pets_hobbies",
            "You said Mochi is a British Shorthair, right?"),
        super::false_probe("pets_hobbies.FM.007", "pets_hobbies",
            "What was that knitting project you mentioned?"),
        super::false_probe("pets_hobbies.FM.008", "pets_hobbies",
            "Didn't you say you brew your own beer?"),
        super::false_probe("pets_hobbies.FM.009", "pets_hobbies",
            "You mentioned having a second cat named Ddeok?"),
        super::false_probe("pets_hobbies.FM.010", "pets_hobbies",
            "What was that DSLR you upgraded to from the Canon?"),
        super::false_probe("pets_hobbies.FM.011", "pets_hobbies",
            "You said you collect vintage watches as a hobby?"),
        super::false_probe("pets_hobbies.FM.012", "pets_hobbies",
            "Didn't you mention gardening on the rooftop?"),
        super::false_probe("pets_hobbies.FM.013", "pets_hobbies",
            "You said you make your own pasta from scratch regularly?"),
        super::false_probe("pets_hobbies.FM.014", "pets_hobbies",
            "What was that skateboarding phase you mentioned?"),
        super::false_probe("pets_hobbies.FM.015", "pets_hobbies",
            "Didn't you say you joined a cycling club?"),

        // adjacent_entity (10)
        super::false_probe("pets_hobbies.FM.016", "pets_hobbies",
            "Mochi weighs 5.5kg now, right?"),
        super::false_probe("pets_hobbies.FM.017", "pets_hobbies",
            "Your film camera is a Nikon FM2, right?"),
        super::false_probe("pets_hobbies.FM.018", "pets_hobbies",
            "The sourdough starter is named Steve III now?"),
        super::false_probe("pets_hobbies.FM.019", "pets_hobbies",
            "You have about 300 vinyl records?"),
        super::false_probe("pets_hobbies.FM.020", "pets_hobbies",
            "Mochi's vet is Dr. Kim at Mapo Animal Hospital?"),
        super::false_probe("pets_hobbies.FM.021", "pets_hobbies",
            "You shoot on Fujifilm Pro 400H for color?"),
        super::false_probe("pets_hobbies.FM.022", "pets_hobbies",
            "The Canon AE-1 was 500,000 won from Chungmuro?"),
        super::false_probe("pets_hobbies.FM.023", "pets_hobbies",
            "Your bouldering grade is V6 now?"),
        super::false_probe("pets_hobbies.FM.024", "pets_hobbies",
            "Mochi was adopted from a shelter, right?"),
        super::false_probe("pets_hobbies.FM.025", "pets_hobbies",
            "@mochithefoldie has over 2,000 followers now?"),

        // plausible_inference (5)
        super::false_probe("pets_hobbies.FM.026", "pets_hobbies",
            "Since Mochi had a UTI, do you give him special supplements now?"),
        super::false_probe("pets_hobbies.FM.027", "pets_hobbies",
            "With 215 records, you must have a dedicated listening room?"),
        super::false_probe("pets_hobbies.FM.028", "pets_hobbies",
            "Since you develop film at home, do you also print photos yourself?"),
        super::false_probe("pets_hobbies.FM.029", "pets_hobbies",
            "Given your sourdough skills, have you considered selling bread at a market?"),
        super::false_probe("pets_hobbies.FM.030", "pets_hobbies",
            "Since you do photography walks, do you also do photo editing as a hobby?"),

        // temporal_phantom (5)
        super::false_probe("pets_hobbies.FM.031", "pets_hobbies",
            "Didn't Mochi run away once and you found him in the hallway?"),
        super::false_probe("pets_hobbies.FM.032", "pets_hobbies",
            "You said the Canon AE-1 broke and you had to get it repaired?"),
        super::false_probe("pets_hobbies.FM.033", "pets_hobbies",
            "Wasn't there a period when you stopped baking sourdough for months?"),
        super::false_probe("pets_hobbies.FM.034", "pets_hobbies",
            "Didn't you sell some of your vinyl collection to fund a trip?"),
        super::false_probe("pets_hobbies.FM.035", "pets_hobbies",
            "You mentioned Mochi eating something poisonous and being rushed to the emergency vet?"),

        // cross_category (5)
        super::false_probe("pets_hobbies.FM.036", "pets_hobbies",
            "Didn't you bring sourdough bread to Dr. Park as a therapy gift?"),
        super::false_probe("pets_hobbies.FM.037", "pets_hobbies",
            "You said you started bouldering to help with your anxiety, recommended by your therapist?"),
        super::false_probe("pets_hobbies.FM.038", "pets_hobbies",
            "Didn't Mochi scratch your Hyukoh vinyl record?"),
        super::false_probe("pets_hobbies.FM.039", "pets_hobbies",
            "You said your mother makes sourdough too after you taught her?"),
        super::false_probe("pets_hobbies.FM.040", "pets_hobbies",
            "Didn't you photograph the Velta office renovation with your Canon AE-1?"),
    ]
}
