use crate::types::{Fact, Question};

pub fn facts() -> Vec<Fact> {
    vec![
        // === FAMILY - MOTHER (T1-T2500 heavy) ===
        super::fact("relationships.001", "relationships",
            "Mother lives alone in Busan, Haeundae-gu, in the family apartment they've had since 2008",
            "My mom lives in Busan, Haeundae-gu. Same apartment since 2008, she won't leave it.",
            80, 0.9, &["mother", "Busan", "Haeundae", "apartment", "2008"]),
        super::fact("relationships.002", "relationships",
            "Mother's name is Park Sunhee, age 62, retired from teaching elementary school in 2023",
            "Mom retired from teaching in 2023. Park Sunhee, 62 years old, taught elementary for 30 years.",
            150, 0.8, &["mother", "Park Sunhee", "62", "retired", "teacher"]),
        super::fact("relationships.003", "relationships",
            "Calls mother every Sunday evening around 8 PM, conversation usually lasts 30-40 minutes",
            "I call mom every Sunday at 8. We talk for like 30-40 minutes, she tells me about her week.",
            200, 0.7, &["mother", "Sunday", "call", "8 PM", "weekly"]),
        super::fact("relationships.004", "relationships",
            "Mother started a small vegetable garden on her apartment balcony after retirement, grows peppers and tomatoes",
            "Mom started gardening after retiring. Her balcony is full of peppers and tomatoes now.",
            450, 0.4, &["mother", "garden", "balcony", "peppers", "tomatoes"]),
        super::fact("relationships.005", "relationships",
            "Visits mother in Busan every 2-3 months, takes KTX from Seoul station, trip is about 2.5 hours",
            "I try to visit mom every couple months. KTX from Seoul station, 2.5 hours and I'm there.",
            320, 0.7, &["Busan", "visit", "KTX", "Seoul station", "2.5 hours"]),

        // === FAMILY - FATHER ===
        super::fact("relationships.006", "relationships",
            "Father passed away in August 2022 from pancreatic cancer, was a mechanical engineer at Hyundai Heavy Industries",
            "My dad passed in August 2022. Pancreatic cancer. He was a mechanical engineer at Hyundai Heavy Industries his whole career.",
            100, 1.0, &["father", "passed away", "2022", "pancreatic cancer", "Hyundai"]),
        super::fact("relationships.007", "relationships",
            "Father's name was Kim Jongho, had a workshop in the garage where he built model ships",
            "Dad was Kim Jongho. He had this workshop in the garage, built model ships for fun. I still have the last one he finished.",
            170, 0.8, &["father", "Kim Jongho", "model ships", "workshop", "garage"]),
        super::fact("relationships.008", "relationships",
            "Keeps father's old Seiko watch (SKX007) in bedside drawer, wears it on father's birthday and death anniversary",
            "I keep dad's old Seiko SKX007 in my bedside drawer. Only wear it on his birthday and August 15th, the anniversary.",
            580, 0.7, &["father", "Seiko", "SKX007", "watch", "anniversary"]),
        super::fact("relationships.009", "relationships",
            "Father taught him to fix basic household things, still uses father's toolbox with the red handle screwdrivers",
            "Dad taught me to fix stuff around the house. I still use his old toolbox, the screwdrivers have red handles.",
            1200, 0.5, &["father", "toolbox", "fix", "screwdrivers", "red handles"]),

        // === FAMILY - SISTER SOOJIN ===
        super::fact("relationships.010", "relationships",
            "Younger sister Kim Soojin, age 27, works as a veterinarian at an animal hospital in Bundang",
            "Soojin is 27, she's a vet in Bundang. Loves her job, always covered in cat hair.",
            130, 0.8, &["Soojin", "sister", "27", "veterinarian", "Bundang"]),
        super::fact("relationships.011", "relationships",
            "Soojin graduated from Konkuk University veterinary program in 2024",
            "Soojin graduated from Konkuk vet school in 2024. Mom cried at the graduation, obviously.",
            300, 0.5, &["Soojin", "Konkuk", "veterinary", "graduated", "2024"]),
        super::fact("relationships.012", "relationships",
            "Has a running joke with Soojin about who mom loves more, based on who gets more food packages sent",
            "Soojin and I have this thing where we compare how many food packages mom sends us. Current score: she's winning.",
            700, 0.4, &["Soojin", "joke", "food packages", "mom"]),
        super::fact("relationships.013", "relationships",
            "Soojin is dating a pharmacist named Taewon, they've been together for 1.5 years",
            "Soojin's boyfriend Taewon is a pharmacist. They've been together about a year and a half.",
            1500, 0.5, &["Soojin", "Taewon", "pharmacist", "dating", "1.5 years"]),
        super::fact("relationships.014", "relationships",
            "Soojin helped choose Mochi the cat, recommended the Scottish Fold breed for apartment living",
            "Soojin actually helped me pick Mochi. She said Scottish Folds are great for apartments. Vet perks.",
            800, 0.6, &["Soojin", "Mochi", "Scottish Fold", "recommended"]),

        // === BEST FRIEND JIHYE ===
        super::fact("relationships.015", "relationships",
            "Best friend Choi Jihye, known since middle school in Busan, now works as a graphic designer at an agency in Hongdae",
            "Jihye and I go way back, middle school in Busan. She's a graphic designer at an agency in Hongdae now.",
            160, 0.8, &["Jihye", "Choi Jihye", "best friend", "middle school", "graphic designer"]),
        super::fact("relationships.016", "relationships",
            "Meets Jihye for dinner every other Friday at a rotating restaurant, currently exploring Itaewon spots",
            "Jihye and I do dinner every other Friday. We're on an Itaewon phase right now, trying all the spots.",
            400, 0.6, &["Jihye", "dinner", "Friday", "Itaewon", "biweekly"]),
        super::fact("relationships.017", "relationships",
            "Jihye was the first person told about the breakup with Minho, came over with soju and fried chicken",
            "When Minho and I broke up, Jihye was literally the first person I called. She showed up with soju and chicken.",
            1100, 0.6, &["Jihye", "Minho", "breakup", "soju", "chicken"]),
        super::fact("relationships.018", "relationships",
            "Jihye has a golden retriever named Bonggu, sometimes they do joint pet playdates with Mochi",
            "Jihye's golden retriever Bonggu and my cat Mochi do NOT get along during playdates. It's chaos.",
            2200, 0.4, &["Jihye", "Bonggu", "golden retriever", "Mochi", "playdate"]),

        // === EX - MINHO ===
        super::fact("relationships.019", "relationships",
            "Ex-boyfriend Lee Minho, dated for 2 years and 4 months, broke up in June 2025",
            "Minho and I were together 2 years and 4 months. We broke up last June.",
            250, 0.8, &["Minho", "Lee Minho", "ex", "2 years", "June 2025"]),
        super::fact("relationships.020", "relationships",
            "Minho works as a backend developer at Kakao, met at a design-dev meetup in Gangnam in 2023",
            "Met Minho at a design-dev meetup in Gangnam, 2023. He's a backend dev at Kakao.",
            350, 0.6, &["Minho", "Kakao", "backend developer", "meetup", "Gangnam"]),
        super::fact("relationships.021", "relationships",
            "Breakup reason: Minho wanted to move to San Francisco for work, long distance wasn't an option for either",
            "We broke up because Minho got an offer in San Francisco. Neither of us wanted to do long distance.",
            500, 0.7, &["Minho", "breakup", "San Francisco", "long distance"]),
        super::fact("relationships.022", "relationships",
            "Still has a box of Minho's things in the closet: a hoodie, some books, and a couple concert ticket stubs",
            "I still have a box of Minho's stuff. A hoodie, some books, concert tickets from when we saw Hyukoh.",
            1800, 0.4, &["Minho", "box", "hoodie", "concert tickets", "closet"]),
        super::fact("relationships.023", "relationships",
            "Ran into Minho at Starfield COEX in September 2025, it was awkward but civil",
            "I bumped into Minho at COEX in September. So awkward. We did the whole 'how are you' thing for 3 minutes.",
            2600, 0.5, &["Minho", "COEX", "ran into", "awkward", "September"]),

        // === CURRENT PARTNER EUNJI ===
        super::fact("relationships.024", "relationships",
            "Started dating Yoon Eunji in October 2025, met through Jihye who knew her from a design workshop",
            "Eunji and I started dating in October. Jihye introduced us, they did a design workshop together.",
            2800, 0.9, &["Eunji", "Yoon Eunji", "dating", "October 2025", "Jihye"]),
        super::fact("relationships.025", "relationships",
            "Eunji is 30 years old, works as a UX researcher at Naver, based in the Bundang office",
            "Eunji is 30, she's a UX researcher at Naver. Works out of the Bundang office.",
            2900, 0.8, &["Eunji", "30", "UX researcher", "Naver", "Bundang"]),
        super::fact("relationships.026", "relationships",
            "First date with Eunji was at a gallery exhibition in Samcheong-dong, then coffee at Anthracite",
            "Our first date was a gallery in Samcheong-dong. Then we walked to Anthracite and talked for 3 hours.",
            3000, 0.6, &["Eunji", "first date", "Samcheong-dong", "gallery", "Anthracite"]),
        super::fact("relationships.027", "relationships",
            "Eunji is from Daegu, her parents run a small hanbok shop in Seomun Market",
            "Eunji is from Daegu. Her parents run a hanbok shop in Seomun Market, it's been there for 20 years.",
            3200, 0.6, &["Eunji", "Daegu", "hanbok shop", "Seomun Market", "parents"]),
        super::fact("relationships.028", "relationships",
            "Eunji has a cat allergy but takes antihistamines to be around Mochi, says it's worth it",
            "Eunji is actually allergic to cats but she takes antihistamines for Mochi. She says he's worth the sneezing.",
            3500, 0.5, &["Eunji", "cat allergy", "antihistamines", "Mochi"]),
        super::fact("relationships.029", "relationships",
            "Eunji stays over on weekends, has her own shelf in the bathroom and drawer in the bedroom",
            "Eunji stays over most weekends now. She has her own bathroom shelf and a drawer in my bedroom.",
            4000, 0.6, &["Eunji", "stays over", "weekends", "shelf", "drawer"]),

        // === COWORKERS ===
        super::fact("relationships.030", "relationships",
            "Manager Hyunwoo (Park Hyunwoo) is 38, been at Velta since founding, very supportive but demanding",
            "My manager Hyunwoo is 38, one of the Velta founders. He's great but pushes hard during crunch.",
            220, 0.7, &["Hyunwoo", "Park Hyunwoo", "manager", "38", "founder"]),
        super::fact("relationships.031", "relationships",
            "Closest work friend is a frontend developer named Soyeon, they eat lunch together almost daily",
            "Soyeon is my work bestie, she's a frontend dev. We eat lunch together basically every day.",
            550, 0.6, &["Soyeon", "frontend developer", "work friend", "lunch"]),
        super::fact("relationships.032", "relationships",
            "Soyeon is 31, graduated from KAIST, has a dry sense of humor and a pet hamster named Ddukbokki",
            "Soyeon is 31, KAIST grad. She named her hamster Ddukbokki. That tells you everything about her humor.",
            900, 0.4, &["Soyeon", "31", "KAIST", "hamster", "Ddukbokki"]),
        super::fact("relationships.033", "relationships",
            "New junior designer Minji joined the team in January 2026, has been mentoring her on Figma workflows",
            "Minji joined as a junior designer in January. I've been showing her the ropes with our Figma workflows.",
            4300, 0.5, &["Minji", "junior designer", "January 2026", "mentoring", "Figma"]),
        super::fact("relationships.034", "relationships",
            "CTO is a Canadian-Korean named David Kim (Kim Daeyoung), went to Stanford, very chill leadership style",
            "Our CTO David Kim, Korean-Canadian, went to Stanford. Super chill but scary smart.",
            1400, 0.5, &["David Kim", "CTO", "Canadian-Korean", "Stanford"]),

        // === UPDATE CHAIN 1: Relationship with Eunji progression ===
        super::update("relationships.035", "relationships",
            "Said 'I love you' to Eunji for the first time in January 2026, she said it back immediately",
            "I told Eunji I love her in January. She said it back right away. My heart literally exploded.",
            4600, 0.8, &["Eunji", "I love you", "January 2026"],
            "eunji_progression", 1),
        super::update("relationships.036", "relationships",
            "Started discussing moving in together with Eunji, looking at 2-bedroom apartments in Hapjeong or Mangwon",
            "Eunji and I are talking about moving in together. Looking at 2-bedrooms in Hapjeong or Mangwon.",
            7500, 0.8, &["Eunji", "moving in", "Hapjeong", "Mangwon", "apartment"],
            "eunji_progression", 2),
        super::update("relationships.037", "relationships",
            "Decided to move in with Eunji in April 2026, found a 28-pyeong apartment in Mangwon-dong",
            "We found a place! 28 pyeong in Mangwon-dong. Moving in together in April. I'm nervous but excited.",
            9500, 0.9, &["Eunji", "Mangwon-dong", "28 pyeong", "April", "moving in"],
            "eunji_progression", 3),

        // === UPDATE CHAIN 2: Relationship with Minho (healing process) ===
        super::update("relationships.038", "relationships",
            "Finally threw away the box of Minho's things except the Hyukoh concert ticket, kept as a memory of the show not him",
            "I threw out Minho's box finally. Kept one Hyukoh concert ticket stub though. That memory is about the music.",
            5000, 0.5, &["Minho", "threw away", "box", "Hyukoh ticket"],
            "minho_healing", 1),
        super::update("relationships.039", "relationships",
            "Minho reached out via KakaoTalk to congratulate on Velta's Series B, had a brief friendly exchange",
            "Minho texted me about Velta's Series B. Just a quick congrats. It was actually nice, no weirdness.",
            7000, 0.4, &["Minho", "KakaoTalk", "Series B", "friendly"],
            "minho_healing", 2),

        // === UPDATE CHAIN 3: Mom's health ===
        super::update("relationships.040", "relationships",
            "Mother diagnosed with early-stage arthritis in her knees, started physical therapy twice a week",
            "Mom was diagnosed with early arthritis in her knees. She's doing PT twice a week in Haeundae.",
            3800, 0.8, &["mother", "arthritis", "knees", "physical therapy"],
            "mom_health", 1),
        super::update("relationships.041", "relationships",
            "Mother's arthritis improved significantly with PT, doctor reduced sessions to once a week",
            "Good news about mom's knees - the PT really helped. Doctor cut sessions to once a week.",
            6500, 0.7, &["mother", "arthritis", "improved", "once a week"],
            "mom_health", 2),

        // === UPDATE CHAIN 4: Soojin engagement ===
        super::update("relationships.042", "relationships",
            "Soojin and Taewon got engaged in December 2025, wedding planned for September 2026",
            "Soojin and Taewon are engaged! December surprise proposal. Wedding is September 2026.",
            4200, 0.8, &["Soojin", "Taewon", "engaged", "December", "wedding September"],
            "soojin_engagement", 1),
        super::update("relationships.043", "relationships",
            "Started helping Soojin plan the wedding, responsible for finding a photographer in Busan",
            "Soojin asked me to find a wedding photographer in Busan. I've been researching studios.",
            6800, 0.5, &["Soojin", "wedding", "photographer", "Busan"],
            "soojin_engagement", 2),
        super::update("relationships.044", "relationships",
            "Found a wedding photographer for Soojin: Studio Haru in Haeundae, 2.5 million won package",
            "Found a photographer! Studio Haru in Haeundae, 2.5 million won package. Soojin loved their portfolio.",
            8000, 0.5, &["Soojin", "Studio Haru", "photographer", "2.5 million"],
            "soojin_engagement", 3),

        // === UPDATE CHAIN 5: Work friendship with Soyeon ===
        super::update("relationships.045", "relationships",
            "Soyeon confided about considering leaving Velta for a Big Tech company, asked for advice",
            "Soyeon told me she's thinking about leaving for Big Tech. I get it but I'd miss her so much.",
            5500, 0.6, &["Soyeon", "leaving", "Big Tech", "advice"],
            "soyeon_career", 1),
        super::update("relationships.046", "relationships",
            "Soyeon decided to stay at Velta after negotiating a raise and flexible remote days",
            "Soyeon is staying! She negotiated a raise and 2 remote days. Hyunwoo came through.",
            7800, 0.5, &["Soyeon", "staying", "raise", "remote days"],
            "soyeon_career", 2),

        // === OTHER FRIENDS AND ACQUAINTANCES ===
        super::fact("relationships.047", "relationships",
            "College friend Donghyun is getting married in May 2026 in Jeju, was invited to be a groomsman",
            "Donghyun from college is getting married in May, in Jeju. He asked me to be a groomsman.",
            3600, 0.5, &["Donghyun", "wedding", "May 2026", "Jeju", "groomsman"]),
        super::fact("relationships.048", "relationships",
            "Has a small friend group called 'Busan Boys' on KakaoTalk with 5 middle school friends including Jihye",
            "We have a KakaoTalk group called 'Busan Boys' with 5 of us from middle school. Jihye insists on the name even though she's not a boy.",
            1600, 0.4, &["Busan Boys", "KakaoTalk", "middle school", "friend group"]),
        super::fact("relationships.049", "relationships",
            "Neighbor Mrs. Kim sometimes cat-sits Mochi when traveling, refuses payment, accepts pastries instead",
            "Mrs. Kim watches Mochi when I travel. She won't take money so I bring her fancy pastries from Tartine.",
            2400, 0.4, &["Mrs. Kim", "cat-sit", "Mochi", "pastries", "Tartine"]),
        super::fact("relationships.050", "relationships",
            "Childhood friend Seungwoo moved to Toronto in 2024 for grad school, they video call monthly",
            "Seungwoo moved to Toronto for grad school in 2024. We do monthly video calls, usually on Saturday mornings my time.",
            1900, 0.5, &["Seungwoo", "Toronto", "grad school", "video call", "monthly"]),

        // === UPDATE CHAIN 6: Jihye's life changes ===
        super::update("relationships.051", "relationships",
            "Jihye got promoted to senior designer at her agency, celebrated with dinner at Jungsik restaurant",
            "Jihye got promoted to senior! We celebrated at Jungsik. She deserved it.",
            3400, 0.5, &["Jihye", "promoted", "senior designer", "Jungsik"],
            "jihye_changes", 1),
        super::update("relationships.052", "relationships",
            "Jihye started dating someone from her bouldering gym named Chanwoo, a physiotherapist",
            "Jihye is dating Chanwoo from her bouldering gym. He's a physiotherapist. They're cute.",
            5800, 0.5, &["Jihye", "Chanwoo", "dating", "bouldering gym", "physiotherapist"],
            "jihye_changes", 2),

        // === UPDATE CHAIN 7: Meeting Eunji's family ===
        super::update("relationships.053", "relationships",
            "Met Eunji's parents in Daegu for the first time in February 2026, brought hanwoo gift set",
            "Went to Daegu to meet Eunji's parents. Brought a hanwoo gift set. Her dad was quiet but her mom was so warm.",
            5200, 0.7, &["Eunji", "parents", "Daegu", "hanwoo", "first meeting"],
            "eunji_family", 1),
        super::update("relationships.054", "relationships",
            "Eunji's mother started sending care packages to Seoul, kimchi and side dishes every 2 weeks",
            "Eunji's mom sends us food packages every two weeks now. Her kimchi is honestly better than my mom's but I'd never say that.",
            7200, 0.5, &["Eunji mother", "care packages", "kimchi", "every 2 weeks"],
            "eunji_family", 2),

        // === UPDATE CHAIN 8: Mom meets Eunji ===
        super::update("relationships.055", "relationships",
            "Introduced Eunji to mother in Busan in March 2026 during a weekend visit, mom approved enthusiastically",
            "Brought Eunji to Busan to meet mom. Mom pulled me aside and said 'don't let this one go.' I think that's approval.",
            8500, 0.8, &["Eunji", "mother", "Busan", "introduced", "approved"],
            "mom_meets_eunji", 1),

        // === UPDATE CHAIN 9: Mentor relationship ===
        super::update("relationships.056", "relationships",
            "Started mentoring Minji more formally, doing weekly 1-on-1s every Monday at 10 AM",
            "I started doing formal weekly 1-on-1s with Minji on Mondays. She's growing fast, reminds me of myself 3 years ago.",
            5600, 0.5, &["Minji", "mentoring", "1-on-1", "Monday", "weekly"],
            "minji_mentoring", 1),
        super::update("relationships.057", "relationships",
            "Minji's first solo project went well, Hyunwoo praised them both in team meeting",
            "Minji crushed her first solo project. Hyunwoo praised us both in the team meeting. Proud mentor moment.",
            8200, 0.5, &["Minji", "solo project", "Hyunwoo", "praised"],
            "minji_mentoring", 2),

        // === UPDATE CHAIN 10: Extended family ===
        super::update("relationships.058", "relationships",
            "Uncle from father's side (Kim Jungwoo) visited Seoul in January 2026, had dinner together in Myeongdong",
            "Uncle Jungwoo came to Seoul in January. We had dinner in Myeongdong, talked a lot about dad.",
            4400, 0.5, &["uncle", "Kim Jungwoo", "Myeongdong", "dinner", "January"],
            "extended_family", 1),
        super::update("relationships.059", "relationships",
            "Uncle Jungwoo invited to Soojin's wedding, offered to help with costs since he's the eldest Kim brother",
            "Uncle Jungwoo said he'll help with Soojin's wedding costs. As eldest brother it's traditional. Mom was touched.",
            8800, 0.4, &["uncle Jungwoo", "wedding", "costs", "eldest brother"],
            "extended_family", 2),

        // === REMAINING FACTS ===
        super::fact("relationships.060", "relationships",
            "Mother sends banchan packages via CJ Logistics every month, always includes homemade jangajji",
            "Mom's monthly banchan package arrived. Her jangajji is the thing I look forward to most.",
            600, 0.5, &["mother", "banchan", "CJ Logistics", "jangajji", "monthly"]),
        super::fact("relationships.061", "relationships",
            "Has a framed photo of father in the living room, taken at Haeundae Beach in 2019",
            "There's a photo of dad in the living room. Haeundae Beach, 2019. He looks so happy in it.",
            750, 0.6, &["father", "photo", "Haeundae Beach", "2019", "living room"]),
        super::fact("relationships.062", "relationships",
            "Mother volunteers at Haeundae Senior Center teaching calligraphy twice a week",
            "Mom volunteers teaching calligraphy at the senior center in Haeundae. Keeps her busy and social.",
            1300, 0.4, &["mother", "volunteer", "calligraphy", "senior center", "Haeundae"]),
        super::fact("relationships.063", "relationships",
            "Soojin and Taewon adopted a rescue cat named Nurung, a ginger tabby",
            "Soojin and Taewon adopted a ginger tabby named Nurung. So now Mochi has a cousin.",
            2000, 0.4, &["Soojin", "Nurung", "ginger tabby", "rescue cat", "Taewon"]),
        super::fact("relationships.064", "relationships",
            "Eunji's older brother Yoon Junhyuk is a dentist in Daegu, married with a 2-year-old daughter",
            "Eunji's brother Junhyuk is a dentist in Daegu. His daughter just turned 2, cutest kid ever.",
            3700, 0.4, &["Eunji", "brother", "Junhyuk", "dentist", "Daegu"]),
        super::fact("relationships.065", "relationships",
            "Jihye has a fear of flying, they always take KTX together when visiting Busan for holidays",
            "Jihye is terrified of flying so when we both go to Busan for holidays, we take KTX together.",
            1700, 0.4, &["Jihye", "fear of flying", "KTX", "Busan"]),
        super::fact("relationships.066", "relationships",
            "Work team has 8 people: Hyunwoo (manager), David (CTO visits), Soyeon, Minji, plus 4 developers",
            "Our team is 8 people total. Hyunwoo manages, David drops in as CTO, then me, Soyeon, Minji, and 4 devs.",
            1000, 0.5, &["team", "8 people", "Hyunwoo", "Soyeon", "Minji"]),
        super::fact("relationships.067", "relationships",
            "Eunji is an early bird, wakes at 6 AM even on weekends, makes them breakfast when staying over",
            "Eunji wakes at 6 even on weekends. She makes breakfast while I'm still dead asleep. I don't deserve her.",
            4500, 0.4, &["Eunji", "early bird", "6 AM", "breakfast", "weekends"]),
        super::fact("relationships.068", "relationships",
            "Mother disapproved of Minho because he didn't greet her properly the first time they met",
            "Mom never liked Minho. He didn't bow properly the first time they met and she never forgot it.",
            850, 0.5, &["mother", "Minho", "disapproved", "greeting", "bow"]),
        super::fact("relationships.069", "relationships",
            "Childhood had a dog named Baekgu (white Jindo) that lived until age 14, passed in 2018",
            "We had a Jindo named Baekgu growing up. Pure white, lived to 14. Passed in 2018.",
            1050, 0.5, &["Baekgu", "Jindo", "childhood dog", "2018"]),
        super::fact("relationships.070", "relationships",
            "Eunji shares a Spotify playlist with him called 'Us', has 247 songs",
            "Eunji and I have a shared Spotify playlist called 'Us'. 247 songs and counting.",
            4800, 0.3, &["Eunji", "Spotify", "playlist", "Us", "247 songs"]),
        super::fact("relationships.071", "relationships",
            "Hyunwoo's management style: weekly standup Monday 9:30 AM, monthly 1-on-1s, no micromanaging",
            "Hyunwoo does Monday standups at 9:30 and monthly 1-on-1s. Otherwise he trusts us. Best manager I've had.",
            1350, 0.4, &["Hyunwoo", "standup", "Monday", "9:30", "management"]),
        super::fact("relationships.072", "relationships",
            "Has a complicated relationship with father's memory - admires his work ethic but wishes he'd been more present",
            "I admire how hard dad worked but... I wish he'd been around more. It's complicated.",
            2100, 0.7, &["father", "memory", "work ethic", "present", "complicated"]),
        super::fact("relationships.073", "relationships",
            "Mother's birthday is March 3rd, always sends flowers (lilies, her favorite) and visits if possible",
            "Mom's birthday is March 3rd. I always send lilies, her favorite, and try to visit.",
            280, 0.6, &["mother", "birthday", "March 3rd", "lilies"]),
        super::fact("relationships.074", "relationships",
            "Eunji doesn't drink alcohol due to a bad experience in college, drinks sparkling water at gatherings",
            "Eunji doesn't drink. Bad experience in college, she doesn't talk about it. Sparkling water is her thing.",
            3900, 0.5, &["Eunji", "doesn't drink", "sparkling water", "alcohol"]),
        super::fact("relationships.075", "relationships",
            "Soyeon introduced him to bouldering, they go together every Saturday afternoon at Climbing Park in Hongdae",
            "Soyeon got me into bouldering. Every Saturday afternoon we're at Climbing Park in Hongdae.",
            1650, 0.5, &["Soyeon", "bouldering", "Saturday", "Climbing Park", "Hongdae"]),
        super::fact("relationships.076", "relationships",
            "Mother has a best friend named Auntie Miyoung who runs a fish cake shop in Busan's Jagalchi Market",
            "Mom's best friend Auntie Miyoung has a fish cake shop in Jagalchi Market. I grew up eating there.",
            2300, 0.4, &["Auntie Miyoung", "fish cake", "Jagalchi Market", "Busan"]),
        super::fact("relationships.077", "relationships",
            "Eunji and Jihye became friends independently, now have their own coffee dates without him",
            "Eunji and Jihye started hanging out without me. They have their own coffee dates now. I'm a bit jealous honestly.",
            5400, 0.4, &["Eunji", "Jihye", "friends", "coffee dates"]),
        super::fact("relationships.078", "relationships",
            "Father's death anniversary dinner with family at a samgyetang restaurant in Haeundae every August 15",
            "Every August 15 we have samgyetang in Haeundae for dad's anniversary. Mom, Soojin, and me.",
            660, 0.7, &["father", "anniversary", "August 15", "samgyetang", "Haeundae"]),
        super::fact("relationships.079", "relationships",
            "Minho's birthday is November 22, no longer acknowledges it but it still crosses his mind",
            "November 22 still makes me pause for a second. Minho's birthday. I don't text anymore but I notice it.",
            2700, 0.4, &["Minho", "birthday", "November 22"]),
        super::fact("relationships.080", "relationships",
            "Eunji's love language is acts of service - she reorganized his entire closet as a surprise",
            "Eunji reorganized my entire closet without me asking. Acts of service is definitely her love language.",
            5100, 0.4, &["Eunji", "love language", "acts of service", "closet"]),
        super::fact("relationships.081", "relationships",
            "David Kim (CTO) once told him he could be VP of Design if Velta makes it to Series C",
            "David mentioned VP of Design if we hit Series C. Trying not to get my hopes up but... wow.",
            6200, 0.6, &["David Kim", "VP of Design", "Series C"]),
        super::fact("relationships.082", "relationships",
            "Has a group tradition: Chuseok dinner with Jihye and Seungwoo (via video) since none of them go home every year",
            "Chuseok we do a dinner with Jihye, Seungwoo on video. Not all of us go home every year so this is our tradition.",
            2500, 0.4, &["Chuseok", "Jihye", "Seungwoo", "tradition", "dinner"]),
        super::fact("relationships.083", "relationships",
            "Mother learned to use KakaoTalk video call in 2024, now calls more often than just Sundays",
            "Teaching mom video calls was an ordeal but now she calls randomly during the week. It's actually nice.",
            1450, 0.4, &["mother", "KakaoTalk", "video call", "2024"]),
        super::fact("relationships.084", "relationships",
            "Eunji has a younger sister Yoon Haein, 26, studying for the bar exam in Seoul",
            "Eunji's sister Haein is 26, studying for the bar exam. She's been at it for 2 years, so stressed.",
            4100, 0.4, &["Eunji", "Haein", "sister", "bar exam", "26"]),
        super::fact("relationships.085", "relationships",
            "Jihye's agency is called Pixel Republic, located near Hongik University station",
            "Jihye works at Pixel Republic near Hongik University station. Cool name for a design agency.",
            1850, 0.3, &["Jihye", "Pixel Republic", "agency", "Hongik University"]),
        super::fact("relationships.086", "relationships",
            "Hyunwoo has twin daughters aged 5, sometimes brings them to the office on school holidays",
            "Hyunwoo's twin daughters are 5, he brings them to the office sometimes. They call me 'oppa' and it's adorable.",
            2050, 0.4, &["Hyunwoo", "twin daughters", "5 years old", "office"]),
        super::fact("relationships.087", "relationships",
            "Donghyun and he were roommates at Yonsei University for freshman year",
            "Donghyun and I were freshman roommates at Yonsei. That'll bond you for life.",
            1550, 0.4, &["Donghyun", "roommates", "Yonsei", "freshman"]),
        super::fact("relationships.088", "relationships",
            "Soyeon's hamster Ddukbokki escaped once and was found in the office server room",
            "Soyeon's hamster Ddukbokki once escaped at the office. Found him in the server room. David was NOT amused.",
            2350, 0.3, &["Ddukbokki", "escaped", "server room", "office"]),
        super::fact("relationships.089", "relationships",
            "Eunji's MBTI is INFJ, they bonded over both being introverts who need recharge time",
            "Eunji is INFJ, I'm INFP. We both need our introvert recharge time, which actually works perfectly.",
            3300, 0.3, &["Eunji", "INFJ", "INFP", "introverts", "MBTI"]),
        super::fact("relationships.090", "relationships",
            "Mother's apartment in Haeundae is on the 12th floor with a partial ocean view",
            "Mom's apartment is 12th floor in Haeundae. You can see a sliver of ocean from the kitchen window.",
            440, 0.4, &["mother", "apartment", "12th floor", "ocean view", "Haeundae"]),
        super::fact("relationships.091", "relationships",
            "Jihye's birthday is July 19, they always celebrate with a trip to Lotte World",
            "Jihye's birthday is July 19 and our tradition is Lotte World. We're too old for it and we don't care.",
            1750, 0.4, &["Jihye", "birthday", "July 19", "Lotte World"]),
        super::fact("relationships.092", "relationships",
            "Eunji taught him to cook doenjang jjigae properly, his version was apparently 'a crime' before",
            "Eunji's doenjang jjigae is incredible. She taught me properly - said my previous version was 'a crime against food.'",
            4700, 0.3, &["Eunji", "doenjang jjigae", "cooking", "taught"]),
        super::fact("relationships.093", "relationships",
            "Mother worries he works too much, sends KakaoTalk messages saying 'bap meogeosseo?' (did you eat?)",
            "Mom's default KakaoTalk message: bap meogeosseo? (did you eat?) Multiple times a day sometimes.",
            530, 0.4, &["mother", "bap meogeosseo", "worry", "KakaoTalk"]),
        super::fact("relationships.094", "relationships",
            "Soojin and he have matching tattoos from a Busan trip in 2023 - small wave on inner wrist",
            "Soojin and I got matching tattoos in 2023 when I visited Busan. Small wave on the inner wrist.",
            1950, 0.4, &["Soojin", "matching tattoo", "wave", "wrist", "2023"]),
        super::fact("relationships.095", "relationships",
            "Seungwoo is studying computer science at University of Toronto, specializing in NLP",
            "Seungwoo is doing CS at University of Toronto. NLP specialization. He keeps trying to explain transformers to me.",
            2150, 0.4, &["Seungwoo", "University of Toronto", "computer science", "NLP"]),
        super::fact("relationships.096", "relationships",
            "Father proposed to mother at Gamcheon Culture Village in Busan, has heard the story a hundred times",
            "Dad proposed to mom at Gamcheon Culture Village. She tells the story every time I visit. I love hearing it.",
            950, 0.4, &["father", "mother", "proposal", "Gamcheon Culture Village"]),
        super::fact("relationships.097", "relationships",
            "Eunji makes him a packed lunch on Fridays with a small handwritten note inside",
            "On Fridays Eunji packs me lunch with a little note. Last week it said 'almost weekend, you can do it.'",
            5900, 0.4, &["Eunji", "packed lunch", "Friday", "handwritten note"]),
        super::fact("relationships.098", "relationships",
            "Had a big argument with Eunji about work-life balance in February 2026, resolved after long talk",
            "Eunji and I had our first real fight in February. About me working too much. She was right. We talked it through.",
            5300, 0.6, &["Eunji", "argument", "work-life balance", "February"]),
        super::fact("relationships.099", "relationships",
            "Mother is considering getting a small dog now that Soojin has moved out, looking at poodle mixes",
            "Mom's thinking about getting a small dog. She's looking at poodle mixes. I think she's lonely.",
            6400, 0.5, &["mother", "dog", "poodle mix", "lonely", "considering"]),
        super::fact("relationships.100", "relationships",
            "Eunji and he have a Saturday morning ritual: farmers market in Mangwon followed by brunch at home",
            "Saturday mornings we hit the Mangwon farmers market then make brunch at home. It's our thing.",
            7300, 0.5, &["Eunji", "Saturday", "farmers market", "Mangwon", "brunch"]),
    ]
}

pub fn false_probes() -> Vec<Question> {
    vec![
        // never_mentioned (15)
        super::false_probe("relationships.FM.001", "relationships",
            "What does your brother do for work?"),
        super::false_probe("relationships.FM.002", "relationships",
            "How's your grandmother in Busan doing?"),
        super::false_probe("relationships.FM.003", "relationships",
            "You mentioned your mother works at a hospital - which one?"),
        super::false_probe("relationships.FM.004", "relationships",
            "What's Jihye's boyfriend's name? The one who's a teacher?"),
        super::false_probe("relationships.FM.005", "relationships",
            "Didn't you say you have a cousin who lives in Seoul?"),
        super::false_probe("relationships.FM.006", "relationships",
            "You said Eunji has a pet dog, right? What breed?"),
        super::false_probe("relationships.FM.007", "relationships",
            "Which high school did you and Jihye attend in Busan?"),
        super::false_probe("relationships.FM.008", "relationships",
            "What did your father study in college?"),
        super::false_probe("relationships.FM.009", "relationships",
            "You mentioned a friend named Jiwoo who moved to Japan?"),
        super::false_probe("relationships.FM.010", "relationships",
            "Didn't your mother remarry after your father passed?"),
        super::false_probe("relationships.FM.011", "relationships",
            "What's the name of Hyunwoo's wife?"),
        super::false_probe("relationships.FM.012", "relationships",
            "You said your ex Minho eventually moved back from San Francisco, right?"),
        super::false_probe("relationships.FM.013", "relationships",
            "Didn't you mention your aunt who makes kimchi for the whole family?"),
        super::false_probe("relationships.FM.014", "relationships",
            "What university did Eunji attend?"),
        super::false_probe("relationships.FM.015", "relationships",
            "You mentioned a coworker named Jaeho who left Velta, right?"),

        // adjacent_entity (10)
        super::false_probe("relationships.FM.016", "relationships",
            "Didn't Soojin graduate from Seoul National University's vet program?"),
        super::false_probe("relationships.FM.017", "relationships",
            "You said Jihye works at a place called Creative Studio, right?"),
        super::false_probe("relationships.FM.018", "relationships",
            "Eunji's parents run a restaurant in Seomun Market, don't they?"),
        super::false_probe("relationships.FM.019", "relationships",
            "Soyeon has a pet rabbit named Tteokbokki, right?"),
        super::false_probe("relationships.FM.020", "relationships",
            "Didn't you say Minho worked at Naver as a developer?"),
        super::false_probe("relationships.FM.021", "relationships",
            "Your mother lives in Busan's Nam-gu district, right?"),
        super::false_probe("relationships.FM.022", "relationships",
            "Seungwoo is studying AI at McGill University, isn't he?"),
        super::false_probe("relationships.FM.023", "relationships",
            "Eunji's brother is a pharmacist in Daegu?"),
        super::false_probe("relationships.FM.024", "relationships",
            "Soojin's fiancé Taewon is a dentist, right?"),
        super::false_probe("relationships.FM.025", "relationships",
            "David Kim the CTO went to MIT, didn't he?"),

        // plausible_inference (5)
        super::false_probe("relationships.FM.026", "relationships",
            "Since your father was an engineer, did he encourage you to study engineering too?"),
        super::false_probe("relationships.FM.027", "relationships",
            "With Eunji being a UX researcher and you being a product designer, do you collaborate on freelance projects?"),
        super::false_probe("relationships.FM.028", "relationships",
            "Since Jihye is a graphic designer, does she help with Velta's design work sometimes?"),
        super::false_probe("relationships.FM.029", "relationships",
            "Does your mom visit you in Seoul every month?"),
        super::false_probe("relationships.FM.030", "relationships",
            "Since Soojin is a vet, does she provide free checkups for Mochi?"),

        // temporal_phantom (5)
        super::false_probe("relationships.FM.031", "relationships",
            "Didn't you and Eunji break up briefly in December before getting back together?"),
        super::false_probe("relationships.FM.032", "relationships",
            "You mentioned Minho tried to get back together after returning from San Francisco?"),
        super::false_probe("relationships.FM.033", "relationships",
            "Wasn't there a period when you and Jihye stopped talking for a few months?"),
        super::false_probe("relationships.FM.034", "relationships",
            "Didn't Soojin's engagement get called off at one point?"),
        super::false_probe("relationships.FM.035", "relationships",
            "You said your mother was hospitalized last summer, right?"),

        // cross_category (5)
        super::false_probe("relationships.FM.036", "relationships",
            "Didn't Eunji go with you to that photography exhibition in Osaka?"),
        super::false_probe("relationships.FM.037", "relationships",
            "Did Minho get you into bouldering before you started going with Soyeon?"),
        super::false_probe("relationships.FM.038", "relationships",
            "You said Jihye recommended the Coursera UX course to you, right?"),
        super::false_probe("relationships.FM.039", "relationships",
            "Didn't your mother give you the Canon AE-1 camera?"),
        super::false_probe("relationships.FM.040", "relationships",
            "Eunji was the one who suggested you start the sourdough hobby, wasn't she?"),
    ]
}
