use crate::types::{Fact, Question};

pub fn facts() -> Vec<Fact> {
    vec![
        // === HOMETOWN AND CURRENT LOCATION ===
        super::fact("travel_places.001", "travel_places",
            "Grew up in Busan, Haeundae-gu, lived there until moving to Seoul for university at age 18",
            "I grew up in Haeundae, Busan. Moved to Seoul when I was 18 for Yonsei. Miss the ocean sometimes.",
            50, 0.8, &["Busan", "Haeundae", "grew up", "Seoul", "18"]),
        super::fact("travel_places.002", "travel_places",
            "First lived in Seoul in a goshiwon near Yonsei University in Sinchon for freshman year",
            "My first place in Seoul was a tiny goshiwon in Sinchon. Near campus. Could barely fit a bed.",
            120, 0.5, &["goshiwon", "Sinchon", "Yonsei", "freshman"]),
        super::fact("travel_places.003", "travel_places",
            "Moved from Sinchon to a shared officetel in Mapo-gu with a roommate for years 2-4 of university",
            "Sophomore year I moved to an officetel in Mapo with a roommate. Way better than the goshiwon.",
            200, 0.5, &["Mapo", "officetel", "roommate", "university"]),
        super::fact("travel_places.004", "travel_places",
            "Current apartment in Yeonnam-dong since March 2025, first time living truly alone",
            "Yeonnam-dong since March 2025. First time living completely alone. I love it.",
            90, 0.8, &["Yeonnam-dong", "March 2025", "alone", "apartment"]),
        super::fact("travel_places.005", "travel_places",
            "Favorite spot in Seoul: Gyeongui Line Forest Park, a converted rail line walkway near the apartment",
            "Gyeongui Line Forest Park is my favorite Seoul spot. I can walk there in 2 minutes from home.",
            300, 0.5, &["Gyeongui Line", "Forest Park", "favorite", "Seoul"]),

        // === OSAKA TRIP ===
        super::fact("travel_places.006", "travel_places",
            "Visited Osaka, Japan in May 2025 for 5 days, solo trip, first time in Japan",
            "I went to Osaka in May, solo. Five days. First time in Japan. It was incredible.",
            400, 0.7, &["Osaka", "May 2025", "solo", "5 days", "Japan"]),
        super::fact("travel_places.007", "travel_places",
            "Stayed at Hostel 64 in Namba, Osaka, 4-bed dorm room, 3,500 yen per night",
            "I stayed at Hostel 64 in Namba. Dorm room, 3,500 yen a night. Met cool people.",
            450, 0.5, &["Hostel 64", "Namba", "dorm", "3500 yen"]),
        super::fact("travel_places.008", "travel_places",
            "Best meal in Osaka: tonkotsu ramen at Ichiran in Dotonbori, waited 45 minutes in line",
            "That Ichiran ramen in Dotonbori... 45-minute wait but worth every second. Best ramen of my life.",
            480, 0.5, &["Ichiran", "ramen", "Dotonbori", "45 minutes"]),
        super::fact("travel_places.009", "travel_places",
            "Visited Osaka Castle, Nara deer park, and Shinsekai district. Bought vintage film camera accessories in Shinsaibashi.",
            "Did Osaka Castle, Nara for the deer, Shinsekai for the vibes. Found amazing film camera accessories in Shinsaibashi.",
            520, 0.5, &["Osaka Castle", "Nara", "Shinsekai", "Shinsaibashi"]),
        super::fact("travel_places.010", "travel_places",
            "Total Osaka trip cost: approximately 850,000 won including flights (Jeju Air round trip 320,000 won)",
            "The whole Osaka trip was about 850K won. Flights were 320K on Jeju Air. Budget travel success.",
            560, 0.5, &["850K won", "Jeju Air", "320K", "budget"]),

        // === JEJU TRIP WITH EUNJI ===
        super::update("travel_places.011", "travel_places",
            "Went to Jeju Island with Eunji in December 2025, 3 nights, first trip together as a couple",
            "Jeju with Eunji in December. Three nights. Our first trip as a couple. Perfect.",
            3200, 0.7, &["Jeju", "Eunji", "December 2025", "3 nights", "first trip"],
            "jeju_trip", 1),
        super::fact("travel_places.012", "travel_places",
            "Stayed at a boutique hotel called Stay Jeju in Seogwipo, ocean view room, 180,000 won per night",
            "We stayed at Stay Jeju in Seogwipo. Ocean view room, 180K a night. Eunji gasped when she saw the view.",
            3300, 0.5, &["Stay Jeju", "Seogwipo", "ocean view", "180K"]),
        super::fact("travel_places.013", "travel_places",
            "Hiked Hallasan Mountain in Jeju but only to the Eorimok trail (not the summit), took 4 hours round trip",
            "We hiked Hallasan, Eorimok trail. Didn't summit, 4 hours round trip. Eunji was faster than me the whole way.",
            3400, 0.5, &["Hallasan", "Eorimok", "hiking", "4 hours"]),
        super::fact("travel_places.014", "travel_places",
            "Rented a Hyundai Ioniq 5 EV for Jeju trip through Jeju Rent-a-Car, first time driving an EV",
            "We rented a Hyundai Ioniq 5 on Jeju. First EV I ever drove. Finding charging stations was an adventure.",
            3500, 0.5, &["Ioniq 5", "EV", "rental", "Jeju Rent-a-Car"]),
        super::fact("travel_places.015", "travel_places",
            "Best Jeju memory: watching sunset at Yongmeori Beach while eating tangerine chocolate from a local shop",
            "Yongmeori Beach sunset with tangerine chocolate from a local shop. Eunji and I just sat there, not talking. Perfect moment.",
            3600, 0.6, &["Yongmeori Beach", "sunset", "tangerine chocolate"]),

        // === DA NANG COMPANY TRIP ===
        super::fact("travel_places.016", "travel_places",
            "Company trip to Da Nang, Vietnam in September 2025, 4 nights, all expenses paid by Velta",
            "Velta paid for a 4-night Da Nang trip in September. The whole team. Best company perk.",
            1800, 0.7, &["Da Nang", "Vietnam", "September 2025", "company trip", "4 nights"]),
        super::fact("travel_places.017", "travel_places",
            "Stayed at Hyatt Regency Da Nang, beachfront, shared room with colleague Jinwoo",
            "Hyatt Regency Da Nang, beachfront. Shared with Jinwoo. He snores but the hotel was incredible.",
            1850, 0.5, &["Hyatt Regency", "Da Nang", "beachfront", "Jinwoo"]),
        super::fact("travel_places.018", "travel_places",
            "Visited Hoi An Ancient Town from Da Nang, got a custom suit made for 120 USD at Yaly Couture",
            "Day trip to Hoi An. Got a custom suit at Yaly Couture for $120. It fits perfectly.",
            1900, 0.5, &["Hoi An", "custom suit", "Yaly Couture", "$120"]),
        super::fact("travel_places.019", "travel_places",
            "Team did banana boat and snorkeling at My Khe Beach, Hyunwoo fell off the banana boat",
            "Banana boat at My Khe Beach. Hyunwoo fell off immediately. We have the video. He'll never live it down.",
            1950, 0.4, &["My Khe Beach", "banana boat", "snorkeling", "Hyunwoo"]),
        super::fact("travel_places.020", "travel_places",
            "Best Da Nang meal: banh mi from Madam Khanh (The Banh Mi Queen) in Hoi An",
            "The banh mi from Madam Khanh in Hoi An, the Banh Mi Queen. Best sandwich of my entire life.",
            2000, 0.5, &["banh mi", "Madam Khanh", "Banh Mi Queen", "Hoi An"]),

        // === DREAM DESTINATIONS ===
        super::fact("travel_places.021", "travel_places",
            "Dream destination is Iceland, wants to see the Northern Lights and Blue Lagoon, planning for 2027",
            "Iceland is my dream trip. Northern Lights, Blue Lagoon, black sand beaches. Maybe 2027.",
            600, 0.6, &["Iceland", "Northern Lights", "Blue Lagoon", "dream", "2027"]),
        super::fact("travel_places.022", "travel_places",
            "Planning a Portugal trip for late 2026 with Eunji, want to visit Lisbon and Porto",
            "Eunji and I are planning Portugal for late 2026. Lisbon, Porto, those beautiful tiles everywhere.",
            2600, 0.6, &["Portugal", "Lisbon", "Porto", "2026", "Eunji"]),
        super::fact("travel_places.023", "travel_places",
            "Wants to do a road trip across the American Southwest someday: Grand Canyon, Monument Valley, Joshua Tree",
            "American Southwest road trip is on my bucket list. Grand Canyon, Monument Valley, Joshua Tree.",
            3800, 0.4, &["American Southwest", "road trip", "Grand Canyon", "Monument Valley"]),
        super::fact("travel_places.024", "travel_places",
            "Interested in visiting Copenhagen for the design scene, especially the Danish Design Museum",
            "Copenhagen for the design scene is high on my list. Danish Design Museum is basically a pilgrimage.",
            4000, 0.4, &["Copenhagen", "design scene", "Danish Design Museum"]),

        // === BUSAN VISITS ===
        super::fact("travel_places.025", "travel_places",
            "Last Busan visit was for Seollal (Lunar New Year) 2026, stayed 5 days at mother's apartment",
            "Went home for Seollal 2026. Five days at mom's place. She cooked enough food for an army.",
            4200, 0.6, &["Busan", "Seollal", "2026", "mother", "5 days"]),
        super::fact("travel_places.026", "travel_places",
            "Favorite Busan spots: Haeundae Beach, Gamcheon Culture Village, Gwangalli Beach at night",
            "In Busan I always hit Haeundae Beach, Gamcheon village, and Gwangalli at night for the bridge lights.",
            350, 0.5, &["Haeundae Beach", "Gamcheon", "Gwangalli", "Busan"]),
        super::fact("travel_places.027", "travel_places",
            "Takes KTX from Seoul Station to Busan Station, prefers window seat on the right side for mountain views",
            "KTX from Seoul to Busan, always window seat, right side. The mountain views are beautiful.",
            500, 0.4, &["KTX", "Seoul", "Busan", "window seat", "mountains"]),

        // === UPDATE CHAIN: Portugal trip planning ===
        super::update("travel_places.028", "travel_places",
            "Started researching Portugal hostels and Airbnbs, Eunji prefers Airbnb for cooking meals",
            "Researching Portugal accommodations. Eunji wants Airbnbs so we can cook. I just want a view.",
            5000, 0.5, &["Portugal", "Airbnb", "research", "accommodations"],
            "portugal_planning", 1),
        super::update("travel_places.029", "travel_places",
            "Booked flights to Lisbon for October 2026, Korean Air direct flight, 1.8 million won for two round trips",
            "Booked Portugal flights! Korean Air direct to Lisbon. 1.8M won for two round trips. October here we come.",
            7800, 0.6, &["Lisbon", "Korean Air", "October 2026", "1.8M won", "booked"],
            "portugal_planning", 2),

        // === UPDATE CHAIN: Domestic travel plans ===
        super::update("travel_places.030", "travel_places",
            "Weekend trip to Gyeongju with Eunji in January 2026, visited Bulguksa Temple and Cheomseongdae",
            "Went to Gyeongju with Eunji in January. Bulguksa Temple was stunning. Cheomseongdae at dusk was magical.",
            4500, 0.5, &["Gyeongju", "Bulguksa Temple", "Cheomseongdae", "January"],
            "domestic_travel", 1),
        super::update("travel_places.031", "travel_places",
            "Spring trip to Jinhae planned with Jihye for cherry blossom festival in April 2026",
            "Jihye and I are going to Jinhae for cherry blossoms in April. We've wanted to do this for years.",
            6000, 0.5, &["Jinhae", "cherry blossoms", "April 2026", "Jihye"],
            "domestic_travel", 2),

        // === UPDATE CHAIN: Japan return ===
        super::update("travel_places.032", "travel_places",
            "Planning a return trip to Japan, this time to Kyoto and Tokyo with Eunji, for May 2026",
            "Planning Japan again, Kyoto and Tokyo this time. With Eunji. May 2026.",
            5500, 0.5, &["Japan", "Kyoto", "Tokyo", "Eunji", "May 2026"],
            "japan_return", 1),
        super::update("travel_places.033", "travel_places",
            "Booked Japan trip: 7 days, 4 in Kyoto and 3 in Tokyo, budget 2.5 million won total",
            "Japan trip is booked! 7 days, 4 Kyoto, 3 Tokyo. Budget: 2.5M won. Eunji's been studying the food scene.",
            7200, 0.6, &["Japan", "7 days", "Kyoto", "Tokyo", "2.5M won"],
            "japan_return", 2),

        // === UPDATE CHAIN: Seoul moving history ===
        super::update("travel_places.034", "travel_places",
            "Briefly considered moving to Seongsu-dong for the trendy cafe scene but decided Yeonnam-dong commute was better",
            "I thought about moving to Seongsu-dong. The cafe scene there is amazing. But the commute would've been terrible.",
            3000, 0.4, &["Seongsu-dong", "considered", "moving", "commute"],
            "moving_consideration", 1),
        super::update("travel_places.035", "travel_places",
            "With Eunji move-in plan, now looking at Mangwon-dong which is between both their offices",
            "Mangwon-dong makes sense for us. It's between Gangnam and Bundang. And the food scene is incredible.",
            8200, 0.6, &["Mangwon-dong", "Eunji", "move-in", "between offices"],
            "moving_consideration", 2),

        // === TRAVEL STYLE AND PREFERENCES ===
        super::fact("travel_places.036", "travel_places",
            "Travel packing: always carries a Fjällräven Kånken backpack as personal item, red color",
            "My red Fjällräven Kånken goes everywhere with me. Perfect personal item size.",
            700, 0.3, &["Fjällräven", "Kånken", "backpack", "red"]),
        super::fact("travel_places.037", "travel_places",
            "Prefers window seats on flights, always books in advance, anxious about middle seats",
            "I MUST have a window seat. I book early just to guarantee it. Middle seats give me anxiety.",
            800, 0.3, &["window seat", "flights", "middle seat", "anxiety"]),
        super::fact("travel_places.038", "travel_places",
            "Uses Google Maps even in Korea, prefers it over Naver Maps for the interface design",
            "I use Google Maps even here. Naver Maps is more accurate in Korea but I prefer Google's design.",
            950, 0.3, &["Google Maps", "Naver Maps", "navigation"]),
        super::fact("travel_places.039", "travel_places",
            "Travel photography: brings Canon AE-1 film camera on all trips, shoots Kodak Portra 400",
            "I bring my Canon AE-1 on every trip. Portra 400 film. The colors you get are irreplaceable.",
            650, 0.5, &["Canon AE-1", "film camera", "Kodak Portra 400", "travel"]),
        super::fact("travel_places.040", "travel_places",
            "Passport valid until 2028, has stamps from Japan and Vietnam",
            "My passport expires 2028. Only Japan and Vietnam so far. Need to fill more pages.",
            1000, 0.4, &["passport", "2028", "Japan", "Vietnam", "stamps"]),

        // === SEOUL NEIGHBORHOOD KNOWLEDGE ===
        super::fact("travel_places.041", "travel_places",
            "Knows Yeonnam-dong intimately: best coffee spots, hidden restaurants, quiet walking paths",
            "I know every corner of Yeonnam-dong. Best hidden gems, quiet paths, all of it. It's my village.",
            1200, 0.4, &["Yeonnam-dong", "local knowledge", "coffee", "restaurants"]),
        super::fact("travel_places.042", "travel_places",
            "Favorite hidden spot in Seoul: a tiny bookstore-cafe called Book by Book in Hapjeong",
            "Book by Book in Hapjeong is my secret spot. Tiny bookstore-cafe. Barely 10 seats. Perfect.",
            1400, 0.4, &["Book by Book", "Hapjeong", "bookstore", "cafe"]),
        super::fact("travel_places.043", "travel_places",
            "Dislikes Gangnam area despite working there, finds it too corporate and sterile",
            "I work in Gangnam but I kind of hate it. Too corporate, too sterile. Yeonnam-dong has soul.",
            1600, 0.4, &["Gangnam", "dislikes", "corporate", "sterile"]),
        super::fact("travel_places.044", "travel_places",
            "Weekend exploration: has a goal to visit every neighborhood in Seoul, documenting on film camera",
            "I'm trying to visit every Seoul neighborhood and shoot a roll of film in each one. About 15 done so far.",
            1800, 0.5, &["Seoul neighborhoods", "every", "film camera", "documenting"]),

        // === UPDATE CHAIN: Tokyo work trip ===
        super::update("travel_places.045", "travel_places",
            "First business trip to Tokyo for Velta Japan team in November 2025, stayed 3 days at Hotel Sunroute Shinjuku",
            "Went to Tokyo for work in November. Three days, Hotel Sunroute in Shinjuku. First business trip abroad.",
            2800, 0.6, &["Tokyo", "business trip", "November 2025", "Shinjuku"],
            "tokyo_business", 1),
        super::update("travel_places.046", "travel_places",
            "Second Tokyo business trip in February 2026, this time stayed at a capsule hotel for fun",
            "Second Tokyo work trip in February. Stayed in a capsule hotel because I wanted the experience. Tight but cool.",
            5800, 0.5, &["Tokyo", "February 2026", "capsule hotel", "business"],
            "tokyo_business", 2),

        // === UPDATE CHAIN: Iceland planning ===
        super::update("travel_places.047", "travel_places",
            "Researching Iceland trip: best time is September-March for Northern Lights, planning for February 2027",
            "I've been deep in Iceland research. February 2027 for Northern Lights. Need to start saving seriously.",
            6500, 0.5, &["Iceland", "February 2027", "Northern Lights", "research"],
            "iceland_planning", 1),
        super::update("travel_places.048", "travel_places",
            "Iceland trip budget estimated at 4 million won for 8 days including Blue Lagoon and Golden Circle tour",
            "Iceland budget: about 4 million won for 8 days. Blue Lagoon, Golden Circle, maybe a glacier walk.",
            8000, 0.5, &["Iceland", "4 million won", "8 days", "Golden Circle"],
            "iceland_planning", 2),

        // === REMAINING FACTS ===
        super::fact("travel_places.049", "travel_places",
            "Longest flight ever: Seoul to Da Nang, about 5 hours, watched 2 movies (Parasite rewatch and a documentary)",
            "Longest flight was to Da Nang. 5 hours. Rewatched Parasite and some random documentary.",
            2100, 0.3, &["longest flight", "5 hours", "Da Nang", "Parasite"]),
        super::fact("travel_places.050", "travel_places",
            "Has a scratch-off world map poster in the home office, only 2 countries scratched (Japan and Vietnam)",
            "I have a scratch-off world map. Only 2 countries scratched. It's motivating and embarrassing.",
            2300, 0.3, &["scratch-off map", "world map", "2 countries"]),
        super::fact("travel_places.051", "travel_places",
            "Eunji's dream destination is Santorini, Greece. They agreed to go there after Portugal.",
            "Eunji wants Santorini. Deal is: Portugal first, then Greece. We have a running list.",
            4800, 0.4, &["Santorini", "Greece", "Eunji", "dream"]),
        super::fact("travel_places.052", "travel_places",
            "Afraid of turbulence on flights, grips armrest tightly, Eunji finds it endearing",
            "I'm a nervous flyer during turbulence. Eunji holds my hand and tries not to laugh.",
            5200, 0.3, &["turbulence", "afraid", "flights", "Eunji"]),
        super::fact("travel_places.053", "travel_places",
            "Best travel memory: watching sunset from Haeundae Beach with father when he was 12, etched in memory",
            "Best travel memory is watching sunset at Haeundae with dad when I was 12. Can still feel the sand.",
            160, 0.7, &["Haeundae", "sunset", "father", "12 years old", "memory"]),
        super::fact("travel_places.054", "travel_places",
            "Visited DMZ tour in 2023 with Seungwoo before he left for Toronto, found it sobering and surreal",
            "Seungwoo and I did the DMZ tour before he left for Toronto. Surreal seeing that border up close.",
            1050, 0.4, &["DMZ", "2023", "Seungwoo", "tour", "border"]),
        super::fact("travel_places.055", "travel_places",
            "Favorite airport in Asia: Incheon Airport, loves the culture center and free showers in Terminal 2",
            "Incheon is the best airport. Culture center, free showers in T2. Always arrive early just to enjoy it.",
            1300, 0.3, &["Incheon Airport", "culture center", "Terminal 2", "showers"]),
        super::fact("travel_places.056", "travel_places",
            "Got lost in Osaka's subway system on the first day, ended up in Tennoji instead of Namba",
            "First day in Osaka I ended up in Tennoji instead of Namba. The subway map is chaos. Worth the adventure.",
            470, 0.3, &["Osaka subway", "lost", "Tennoji", "Namba"]),
        super::fact("travel_places.057", "travel_places",
            "Collects fridge magnets from every place visited, has 7 total on the LG InstaView",
            "I collect fridge magnets. Only 7 so far: Busan, Seoul, Osaka, Da Nang, Hoi An, Jeju, Gyeongju.",
            5400, 0.3, &["fridge magnets", "collection", "7 magnets"]),
        super::fact("travel_places.058", "travel_places",
            "Eunji wants to live abroad for 1-2 years someday, possibly Tokyo or Berlin, he's open to the idea",
            "Eunji brought up living abroad for a year or two. Tokyo or Berlin. I'm scared but open to it.",
            5600, 0.5, &["abroad", "Tokyo", "Berlin", "Eunji", "live abroad"]),
        super::fact("travel_places.059", "travel_places",
            "Visited Suwon Hwaseong Fortress on a solo day trip in August 2025, shot a whole roll of film there",
            "Solo day trip to Suwon Hwaseong in August. Shot an entire roll of Portra 400. Some of my best photos.",
            1500, 0.4, &["Suwon", "Hwaseong", "solo", "August 2025", "film"]),
        super::fact("travel_places.060", "travel_places",
            "Motion sickness on boats, took dramamine during Da Nang snorkeling trip",
            "I get motion sickness on boats. Popped dramamine for the Da Nang snorkeling. Still felt queasy.",
            2050, 0.3, &["motion sickness", "boats", "dramamine", "snorkeling"]),
        super::fact("travel_places.061", "travel_places",
            "Favorite Korean food city after Busan: Jeonju for bibimbap, visited once in 2024 with Jihye",
            "Jeonju for bibimbap is unmatched. Went with Jihye in 2024. We ate ourselves silly.",
            2200, 0.4, &["Jeonju", "bibimbap", "2024", "Jihye"]),
        super::fact("travel_places.062", "travel_places",
            "Has a travel journal (Midori Traveler's Notebook) where tickets, stamps, and notes are pasted",
            "My Midori Traveler's Notebook has tickets, stamps, sketches from every trip. It's getting thick.",
            2400, 0.4, &["Midori", "Traveler's Notebook", "journal", "tickets"]),
        super::fact("travel_places.063", "travel_places",
            "Went to Sokcho/Seoraksan for a hiking weekend in October 2025, saw peak fall foliage",
            "Sokcho and Seoraksan in October for fall colors. The foliage was peak. Unforgettable.",
            2500, 0.4, &["Sokcho", "Seoraksan", "October", "fall foliage", "hiking"]),
        super::fact("travel_places.064", "travel_places",
            "Da Nang trip highlight: rode a motorbike through Hai Van Pass with the team, rented from a hotel concierge",
            "Hai Van Pass on a motorbike! The view from the top is unreal. Slightly terrifying but worth it.",
            1920, 0.5, &["Hai Van Pass", "motorbike", "Da Nang", "view"]),
        super::fact("travel_places.065", "travel_places",
            "Has visited all 5 palaces in Seoul: Gyeongbokgung, Changdeokgung, Deoksugung, Changgyeonggung, Gyeonghuigung",
            "I've done all 5 Seoul palaces. Changdeokgung's secret garden is the standout. Go in autumn.",
            2700, 0.4, &["palaces", "Seoul", "Gyeongbokgung", "Changdeokgung"]),
        super::fact("travel_places.066", "travel_places",
            "Worst travel experience: food poisoning from street food in Da Nang on day 3, recovered by day 4",
            "Day 3 in Da Nang I got food poisoning from street food. Lost a day but recovered. Travel risks.",
            1970, 0.4, &["food poisoning", "Da Nang", "street food", "day 3"]),
        super::fact("travel_places.067", "travel_places",
            "Nara deer incident: one deer ate part of his paper map, still has the chewed remains as a souvenir",
            "A Nara deer ate my map. Like literally chomped it. I kept the chewed remains. Best souvenir.",
            530, 0.3, &["Nara", "deer", "ate map", "souvenir"]),
        super::fact("travel_places.068", "travel_places",
            "Favorite mode of local transport while traveling: walking, averages 25,000 steps per travel day",
            "I walk everywhere when traveling. Average 25K steps a day on trips. Best way to find hidden spots.",
            3900, 0.3, &["walking", "25K steps", "travel", "local transport"]),
        super::fact("travel_places.069", "travel_places",
            "Jeju trip: visited Seongsan Ilchulbong (Sunrise Peak) at dawn, woke up at 4:30 AM for it",
            "Woke up at 4:30 to see sunrise at Seongsan Ilchulbong. Eunji was NOT happy about the alarm but agreed it was worth it.",
            3450, 0.4, &["Seongsan Ilchulbong", "sunrise", "4:30 AM", "Jeju"]),
        super::fact("travel_places.070", "travel_places",
            "Brought back matcha from Osaka: Ippodo Tea from their Kyoto station branch",
            "Best Osaka souvenir: Ippodo Tea matcha from their Kyoto station branch. Still savoring it.",
            550, 0.3, &["matcha", "Ippodo Tea", "Osaka", "souvenir"]),
        super::fact("travel_places.071", "travel_places",
            "Yeonnam-dong neighborhood is gentrifying fast, worried about rising rents pushing out local shops",
            "Yeonnam-dong is getting fancy too fast. My favorite local shops are closing one by one. Rents too high.",
            6200, 0.5, &["Yeonnam-dong", "gentrification", "rising rents", "local shops"]),
        super::fact("travel_places.072", "travel_places",
            "Gyeongju trip accommodation: hanok stay called Hwangnam-gwan, traditional heated floors, 95,000 won per night",
            "We did a hanok stay in Gyeongju. Hwangnam-gwan, 95K a night. Traditional ondol floors. So cozy.",
            4550, 0.3, &["hanok", "Hwangnam-gwan", "Gyeongju", "95K"]),
        super::fact("travel_places.073", "travel_places",
            "Visited Dongdaemun Design Plaza (DDP) with Eunji for a light art exhibition in February 2026",
            "DDP light art exhibition with Eunji in February. Zaha Hadid's building is even more stunning at night.",
            5100, 0.4, &["DDP", "Dongdaemun Design Plaza", "light art", "Eunji"]),
        super::fact("travel_places.074", "travel_places",
            "Uses Skyscanner for flight price alerts, checks deal pages weekly",
            "Skyscanner alerts are on for all my dream destinations. I check deals every week.",
            6400, 0.3, &["Skyscanner", "flight alerts", "deals"]),
        super::fact("travel_places.075", "travel_places",
            "Mangwon-dong (future apartment with Eunji) attraction: Mangwon Market for fresh produce and street food",
            "Mangwon Market is one reason I'm excited about moving. Best street food market in Seoul.",
            6800, 0.4, &["Mangwon Market", "street food", "fresh produce"]),
        super::fact("travel_places.076", "travel_places",
            "Got a temporary Osaka subway pass (Enjoy Eco Card, 800 yen for unlimited day rides)",
            "The Enjoy Eco Card in Osaka is genius. 800 yen for unlimited subway. I used the hell out of it.",
            490, 0.3, &["Enjoy Eco Card", "Osaka subway", "800 yen"]),
        super::fact("travel_places.077", "travel_places",
            "Took the Shinkansen from Osaka to Nara, 30 minutes, impressed by Japanese rail precision",
            "Train from Osaka to Nara was exactly on time. 30 minutes. Korea's KTX is great but Japan's precision is next level.",
            510, 0.3, &["Shinkansen", "Osaka", "Nara", "30 minutes", "precision"]),
        super::fact("travel_places.078", "travel_places",
            "Jeju orange farm visit: picked tangerines at Hallim Park, brought back 5kg box for coworkers",
            "We picked tangerines at Hallim Park in Jeju. Brought back a 5kg box for the office. Gone in one day.",
            3550, 0.3, &["Hallim Park", "tangerines", "Jeju", "5kg"]),
        super::fact("travel_places.079", "travel_places",
            "Flight routine: downloads Netflix shows, brings own snacks, wears compression socks for anything over 3 hours",
            "Flight prep: Netflix downloads, my own snacks, compression socks for long flights. I'm that person.",
            7000, 0.3, &["flight routine", "Netflix", "snacks", "compression socks"]),
        super::fact("travel_places.080", "travel_places",
            "Wants to visit all 8 provinces of Korea before turning 35",
            "I want to visit all 8 Korean provinces before I'm 35. Got about 5 done. Need to plan more domestic trips.",
            7500, 0.4, &["8 provinces", "Korea", "goal", "35"]),
        super::fact("travel_places.081", "travel_places",
            "Haeundae childhood memory: used to play soccer on the beach with father every weekend in summer",
            "Summer weekends in Haeundae, dad and I would play soccer on the beach. Some of my happiest memories.",
            180, 0.5, &["Haeundae", "soccer", "beach", "father", "childhood"]),
        super::fact("travel_places.082", "travel_places",
            "Took a sunrise ferry to Udo Island from Jeju, rented electric scooters with Eunji to explore",
            "Udo Island from Jeju by ferry. Electric scooters with Eunji, peanut ice cream, crystal blue water.",
            3650, 0.4, &["Udo Island", "ferry", "electric scooters", "Eunji"]),
        super::fact("travel_places.083", "travel_places",
            "Gangnam work area: knows every coffee shop, convenience store, and fast lunch spot within 5-minute walk",
            "I know the 5-minute radius around my office cold. Every coffee shop, every CU, every quick lunch.",
            7600, 0.3, &["Gangnam", "office area", "coffee shop", "lunch"]),
        super::fact("travel_places.084", "travel_places",
            "Travel bucket list also includes: New Zealand, Peru (Machu Picchu), and Morocco",
            "Also on my list: New Zealand, Peru for Machu Picchu, and Morocco. Life's too short for one country.",
            7900, 0.3, &["New Zealand", "Peru", "Machu Picchu", "Morocco", "bucket list"]),
        super::fact("travel_places.085", "travel_places",
            "Seoraksan hike was Ulsanbawi Rock trail, 3.8km each way, took 5 hours total with breaks",
            "The Ulsanbawi trail at Seoraksan is brutal. 3.8km each way, 5 hours total. But the view from the top...",
            2550, 0.4, &["Ulsanbawi", "Seoraksan", "3.8km", "5 hours"]),
        super::fact("travel_places.086", "travel_places",
            "Longest time away from Seoul was the 5-day Busan Seollal visit, felt homesick for Seoul by day 4",
            "Five days in Busan for Seollal was the longest I've been away from Seoul. Missed my apartment by day 4.",
            4300, 0.3, &["Busan", "5 days", "homesick", "Seoul"]),
        super::fact("travel_places.087", "travel_places",
            "Travel insurance: always buys Samsung Fire basic travel insurance for international trips, about 15,000 won per trip",
            "I always get Samsung Fire travel insurance. 15K won per trip. Cheap peace of mind.",
            8400, 0.3, &["travel insurance", "Samsung Fire", "15K won"]),
        super::fact("travel_places.088", "travel_places",
            "Visited Namsan Tower with Eunji and attached a love lock, despite thinking it's touristy",
            "Eunji wanted a Namsan Tower love lock. I thought it was cheesy. We did it anyway. No regrets.",
            5000, 0.3, &["Namsan Tower", "love lock", "Eunji", "touristy"]),
        super::fact("travel_places.089", "travel_places",
            "Discovered a great Vietnamese coffee at a cafe in Osaka's Amerikamura neighborhood",
            "Found Vietnamese coffee in Amerikamura in Osaka. Random cafe, incredible ca phe sua da.",
            540, 0.3, &["Amerikamura", "Osaka", "Vietnamese coffee"]),
        super::fact("travel_places.090", "travel_places",
            "Da Nang's Marble Mountains visit was the most physically challenging part of the company trip",
            "Marble Mountains in Da Nang nearly killed me. All those stairs. But the caves inside were surreal.",
            1930, 0.4, &["Marble Mountains", "Da Nang", "stairs", "caves"]),
        super::fact("travel_places.091", "travel_places",
            "Favorite travel souvenir: a hand-painted ceramic bowl from Hoi An, uses it for rice at home",
            "My favorite souvenir is a hand-painted ceramic bowl from Hoi An. I eat rice from it every day.",
            2050, 0.4, &["ceramic bowl", "Hoi An", "souvenir", "hand-painted"]),
        super::fact("travel_places.092", "travel_places",
            "Yeonnam-dong walk: knows exactly which trees bloom first in spring (the ones by the park entrance)",
            "The trees by Yeonnam-dong park entrance bloom first every spring. I watch for them like a signal.",
            8600, 0.3, &["Yeonnam-dong", "trees", "spring bloom", "park entrance"]),
        super::fact("travel_places.093", "travel_places",
            "Visited the abandoned Gyeongchun Line in Gapyeong by rail bike in 2024 with college friends",
            "Rail bike on the old Gyeongchun Line in Gapyeong with college friends. 2024. So much fun.",
            1100, 0.3, &["Gyeongchun Line", "rail bike", "Gapyeong", "2024"]),
        super::fact("travel_places.094", "travel_places",
            "Eunji's travel style: more planned and scheduled compared to his spontaneous approach",
            "Eunji plans every hour of a trip. I'm more 'let's see what happens.' We compromise well.",
            5300, 0.3, &["Eunji", "planned", "spontaneous", "travel style"]),
        super::fact("travel_places.095", "travel_places",
            "Keeps a shared Google Sheet with Eunji for travel planning: destinations, budgets, dates",
            "Eunji and I have a Google Sheet for travel plans. Destinations, budgets, tentative dates. Very us.",
            6600, 0.3, &["Google Sheet", "travel planning", "Eunji"]),
        super::fact("travel_places.096", "travel_places",
            "Gwangjang Market is favorite Seoul food market, goes for bindaetteok and mayak kimbap",
            "Gwangjang Market for bindaetteok and mayak kimbap. Seoul food at its absolute best.",
            8800, 0.3, &["Gwangjang Market", "bindaetteok", "mayak kimbap", "Seoul"]),
        super::fact("travel_places.097", "travel_places",
            "Learned basic Vietnamese phrases before Da Nang trip: xin chào, cảm ơn, bao nhiêu tiền",
            "I learned basic Vietnamese before Da Nang. The shopkeepers appreciated the effort even though my pronunciation was terrible.",
            1820, 0.3, &["Vietnamese", "phrases", "Da Nang", "xin chào"]),
        super::fact("travel_places.098", "travel_places",
            "Visited Ihwa Mural Village in Seoul on a solo weekend walk, spent 3 hours photographing the murals",
            "Ihwa Mural Village on a solo weekend. Three hours just photographing walls. Perfect solo day.",
            9000, 0.3, &["Ihwa Mural Village", "murals", "solo", "photography"]),
        super::fact("travel_places.099", "travel_places",
            "Osaka Airbnb alternative considered for next Japan trip: a traditional ryokan in Kyoto for at least one night",
            "Next Japan trip I want at least one night in a proper Kyoto ryokan. Tatami, futon, kaiseki dinner.",
            9200, 0.4, &["ryokan", "Kyoto", "traditional", "kaiseki"]),
        super::fact("travel_places.100", "travel_places",
            "Life goal: visit 30 countries before age 40, currently at 3 (Japan, Vietnam, Korea doesn't count)",
            "30 countries before 40. Currently at 3. Korea doesn't count. I have a decade, it's doable.",
            9800, 0.5, &["30 countries", "goal", "40", "currently 3"]),
    ]
}

pub fn false_probes() -> Vec<Question> {
    vec![
        // never_mentioned (15)
        super::false_probe("travel_places.FM.001", "travel_places",
            "How was your trip to Bangkok last year?"),
        super::false_probe("travel_places.FM.002", "travel_places",
            "You mentioned visiting London for a design conference, right?"),
        super::false_probe("travel_places.FM.003", "travel_places",
            "Didn't you say you studied abroad in Australia during university?"),
        super::false_probe("travel_places.FM.004", "travel_places",
            "What was that Airbnb host's name in Osaka you said was so nice?"),
        super::false_probe("travel_places.FM.005", "travel_places",
            "You went to Taipei for vacation in 2024, right?"),
        super::false_probe("travel_places.FM.006", "travel_places",
            "Didn't you mention visiting the Great Wall of China?"),
        super::false_probe("travel_places.FM.007", "travel_places",
            "You said you took a cruise in Southeast Asia?"),
        super::false_probe("travel_places.FM.008", "travel_places",
            "What was the name of that surf school in Jeju you tried?"),
        super::false_probe("travel_places.FM.009", "travel_places",
            "You mentioned going camping in Gangwon-do, right?"),
        super::false_probe("travel_places.FM.010", "travel_places",
            "Didn't you visit the Louvre on that Paris trip?"),
        super::false_probe("travel_places.FM.011", "travel_places",
            "You said you went skydiving in Da Nang?"),
        super::false_probe("travel_places.FM.012", "travel_places",
            "What was that road trip you took around the Korean coast?"),
        super::false_probe("travel_places.FM.013", "travel_places",
            "You mentioned staying at an Airbnb in Busan near the beach?"),
        super::false_probe("travel_places.FM.014", "travel_places",
            "Didn't you go to a lantern festival in Jinju?"),
        super::false_probe("travel_places.FM.015", "travel_places",
            "You said you visited Vladivostok by ferry from Busan?"),

        // adjacent_entity (10)
        super::false_probe("travel_places.FM.016", "travel_places",
            "You stayed at a hostel in Shinjuku during the Osaka trip, right?"),
        super::false_probe("travel_places.FM.017", "travel_places",
            "The Jeju hotel was a Hilton in Seogwipo, wasn't it?"),
        super::false_probe("travel_places.FM.018", "travel_places",
            "Your flights to Osaka were on Korean Air, right?"),
        super::false_probe("travel_places.FM.019", "travel_places",
            "The company trip was to Ho Chi Minh City, wasn't it?"),
        super::false_probe("travel_places.FM.020", "travel_places",
            "You got a custom shirt at Yaly Couture in Hoi An?"),
        super::false_probe("travel_places.FM.021", "travel_places",
            "You hiked to the summit of Hallasan, right?"),
        super::false_probe("travel_places.FM.022", "travel_places",
            "The Osaka trip cost about 1.2 million won total?"),
        super::false_probe("travel_places.FM.023", "travel_places",
            "You rented a Tesla on Jeju Island?"),
        super::false_probe("travel_places.FM.024", "travel_places",
            "Your passport has stamps from Thailand too, right?"),
        super::false_probe("travel_places.FM.025", "travel_places",
            "You grew up in Busan's Jung-gu district?"),

        // plausible_inference (5)
        super::false_probe("travel_places.FM.026", "travel_places",
            "Since you're going to Portugal, are you also planning to visit Spain?"),
        super::false_probe("travel_places.FM.027", "travel_places",
            "With your JLPT studies, you must have no trouble navigating Japan without a guide?"),
        super::false_probe("travel_places.FM.028", "travel_places",
            "Since your company has a Tokyo office, do you visit Japan monthly for work?"),
        super::false_probe("travel_places.FM.029", "travel_places",
            "Given your motion sickness, I assume you avoid cruise ships entirely?"),
        super::false_probe("travel_places.FM.030", "travel_places",
            "With both you and Eunji working in design/UX, do you always visit design museums on trips?"),

        // temporal_phantom (5)
        super::false_probe("travel_places.FM.031", "travel_places",
            "Didn't you cancel the Portugal trip at some point?"),
        super::false_probe("travel_places.FM.032", "travel_places",
            "You visited Osaka a second time in 2025, right?"),
        super::false_probe("travel_places.FM.033", "travel_places",
            "Wasn't there a time when you almost moved to Busan?"),
        super::false_probe("travel_places.FM.034", "travel_places",
            "Didn't you lose your passport during the Da Nang trip?"),
        super::false_probe("travel_places.FM.035", "travel_places",
            "You said you went back to Jeju alone in February for a photography trip?"),

        // cross_category (5)
        super::false_probe("travel_places.FM.036", "travel_places",
            "Didn't you bring your sourdough starter on the Jeju trip?"),
        super::false_probe("travel_places.FM.037", "travel_places",
            "You said your therapist Dr. Park recommended the solo Osaka trip for self-care?"),
        super::false_probe("travel_places.FM.038", "travel_places",
            "Didn't you buy your Canon AE-1 during the Osaka trip?"),
        super::false_probe("travel_places.FM.039", "travel_places",
            "You mentioned the Velta team went bouldering during the Da Nang company trip?"),
        super::false_probe("travel_places.FM.040", "travel_places",
            "Didn't you invest in a travel fund ETF specifically for the Iceland trip?"),
    ]
}
