use crate::types::{Fact, Question};

pub fn facts() -> Vec<Fact> {
    vec![
        // === COMPANY AND ROLE BASICS (early turns) ===
        super::fact("work_career.001", "work_career",
            "Works at Velta, a B2B SaaS startup building project management tools for creative teams",
            "I work at Velta. We build project management tools specifically for creative teams. B2B SaaS.",
            60, 0.9, &["Velta", "startup", "SaaS", "project management"]),
        super::fact("work_career.002", "work_career",
            "Current title is Senior Product Designer, promoted from Product Designer in August 2025",
            "Got promoted to Senior Product Designer last August. Was a regular Product Designer for 2 years before that.",
            110, 0.9, &["Senior Product Designer", "promoted", "August 2025"]),
        super::fact("work_career.003", "work_career",
            "Joined Velta in June 2023 as the 12th employee, first dedicated designer",
            "I was employee number 12 at Velta, joined June 2023. First designer they hired.",
            140, 0.8, &["Velta", "June 2023", "12th employee", "first designer"]),
        super::fact("work_career.004", "work_career",
            "Office is in Gangnam, Teheran-ro, 8th floor of a WeWork building",
            "Our office is in Gangnam on Teheran-ro. WeWork 8th floor. Classic startup setup.",
            190, 0.6, &["Gangnam", "Teheran-ro", "WeWork", "8th floor"]),
        super::fact("work_career.005", "work_career",
            "Starting salary was 45 million won, raised to 55 million won after first year",
            "Started at 45 million won. Got bumped to 55 million after my first year when they realized I was doing the work of 3 designers.",
            270, 0.8, &["salary", "45 million", "55 million", "raise"]),

        // === MANAGER AND TEAM ===
        super::fact("work_career.006", "work_career",
            "Manager Park Hyunwoo co-founded Velta with CEO Jang Minsu and CTO David Kim in 2022",
            "Hyunwoo co-founded Velta with Minsu and David in 2022. He handles the product side.",
            230, 0.7, &["Hyunwoo", "co-founded", "Jang Minsu", "CEO", "2022"]),
        super::fact("work_career.007", "work_career",
            "Design team grew from just him to 3 people: himself, Minji (junior), and a contract illustrator named Hana",
            "Design team is me, Minji, and Hana our contract illustrator. From just me to three in 2 years.",
            500, 0.6, &["design team", "Minji", "Hana", "illustrator", "three people"]),
        super::fact("work_career.008", "work_career",
            "Uses Figma as primary design tool, maintains a design system called 'Velta DS' with 340+ components",
            "Our design system 'Velta DS' has over 340 components in Figma. My baby.",
            350, 0.7, &["Figma", "design system", "Velta DS", "340 components"]),
        super::fact("work_career.009", "work_career",
            "Daily standup at 9:30 AM, sprint planning every other Monday, retrospective every other Friday",
            "We do 9:30 standups, sprint planning every other Monday, retros every other Friday. Standard agile.",
            440, 0.5, &["standup", "9:30", "sprint", "agile", "retrospective"]),
        super::fact("work_career.010", "work_career",
            "Company lunch is catered on Wednesdays, usually from local restaurants in Gangnam",
            "Wednesday catered lunches are the best perk. Different Gangnam restaurant each week.",
            520, 0.4, &["catered lunch", "Wednesday", "Gangnam", "perk"]),

        // === SALARY AND COMPENSATION ===
        super::update("work_career.011", "work_career",
            "Salary raised to 65 million won with Senior promotion in August 2025, plus 0.3% stock options",
            "The Senior promotion came with 65 million won salary and 0.3% stock options. Options vest over 4 years.",
            1600, 0.9, &["salary", "65 million", "stock options", "0.3%", "vesting"],
            "salary_progression", 1),
        super::update("work_career.012", "work_career",
            "Received additional 0.1% stock options as retention bonus before Series B in February 2026",
            "They gave me an extra 0.1% in options before Series B. Retention bonus. Now at 0.4% total.",
            5800, 0.8, &["stock options", "0.1%", "retention", "Series B", "0.4%"],
            "salary_progression", 2),

        // === SERIES B ===
        super::fact("work_career.013", "work_career",
            "Velta raised Series A of $5 million from Kakao Ventures and Strong Ventures in March 2024",
            "Our Series A was $5 million from Kakao Ventures and Strong Ventures. March 2024.",
            300, 0.7, &["Series A", "$5 million", "Kakao Ventures", "Strong Ventures"]),
        super::update("work_career.014", "work_career",
            "Series B fundraising started in January 2026, targeting $20 million led by Softbank Ventures Asia",
            "We started Series B fundraising in January. Targeting $20M, Softbank Ventures Asia is leading.",
            4300, 0.8, &["Series B", "$20 million", "Softbank", "fundraising"],
            "series_b", 1),
        super::update("work_career.015", "work_career",
            "Series B closed successfully in March 2026 at $22 million, company valued at $110 million",
            "Series B closed! $22 million at $110M valuation. We did it. Office was champagne central.",
            8500, 0.9, &["Series B", "$22 million", "$110 million", "valuation", "closed"],
            "series_b", 2),

        // === PRODUCT WORK ===
        super::fact("work_career.016", "work_career",
            "Main product is called Velta Flow, a kanban-based project management tool with AI task suggestions",
            "Velta Flow is our main product. Kanban-based but with AI that suggests task breakdowns. Pretty cool.",
            200, 0.7, &["Velta Flow", "kanban", "AI", "task suggestions"]),
        super::fact("work_career.017", "work_career",
            "Led the redesign of Velta Flow's dashboard in Q4 2025, increased user engagement by 34%",
            "I redesigned the Flow dashboard in Q4 and engagement went up 34%. My proudest work moment.",
            2200, 0.7, &["dashboard", "redesign", "Q4 2025", "34% engagement"]),
        super::fact("work_career.018", "work_career",
            "New feature 'Velta Canvas' is an infinite whiteboard for creative brainstorming, launched January 2026",
            "We launched Velta Canvas in January. Infinite whiteboard for brainstorming. I designed the whole thing.",
            4000, 0.7, &["Velta Canvas", "whiteboard", "brainstorming", "January 2026"]),
        super::fact("work_career.019", "work_career",
            "Velta has about 3,200 paying teams as of February 2026, mostly in Korea and Japan",
            "We have about 3,200 paying teams now. Mostly Korea and Japan, starting to see some from Southeast Asia.",
            5000, 0.6, &["3200 teams", "paying", "Korea", "Japan"]),
        super::fact("work_career.020", "work_career",
            "Pricing: Free tier (up to 5 users), Pro at $12/user/month, Enterprise custom pricing",
            "Free tier for small teams up to 5, Pro at $12 per user per month, Enterprise is custom.",
            700, 0.5, &["pricing", "free tier", "$12", "Pro", "Enterprise"]),

        // === CAREER HISTORY ===
        super::fact("work_career.021", "work_career",
            "First job was internship at Samsung SDS in UX team, summer 2021, hated the corporate culture",
            "I interned at Samsung SDS in UX, summer 2021. Great resume line, terrible culture. So corporate.",
            370, 0.5, &["Samsung SDS", "internship", "2021", "UX"]),
        super::fact("work_career.022", "work_career",
            "Worked at a small agency called DesignBridge for 1 year (2022-2023) before Velta, learned client management",
            "Before Velta I was at DesignBridge, a small agency. One year, 2022-2023. Learned how to deal with clients.",
            430, 0.6, &["DesignBridge", "agency", "2022-2023", "client management"]),
        super::fact("work_career.023", "work_career",
            "Studied Visual Communication Design at Yonsei University, graduated in 2022",
            "Yonsei, Visual Communication Design, class of 2022. Loved the program.",
            260, 0.6, &["Yonsei", "Visual Communication Design", "2022", "graduated"]),

        // === UPDATE CHAIN: IPO plans ===
        super::update("work_career.024", "work_career",
            "CEO Minsu mentioned IPO as a 3-5 year goal during all-hands meeting after Series B announcement",
            "Minsu mentioned IPO in 3-5 years at the all-hands. Everyone got excited but I'm trying to stay grounded.",
            8700, 0.7, &["IPO", "3-5 years", "Minsu", "all-hands"],
            "ipo_plans", 1),

        // === UPDATE CHAIN: Role evolution ===
        super::update("work_career.025", "work_career",
            "Started taking on more product management responsibilities, attending customer calls with sales team",
            "I've been doing more PM stuff lately. Sitting in on customer calls with sales. Hyunwoo's pushing me toward product thinking.",
            3500, 0.6, &["product management", "customer calls", "sales", "PM"],
            "role_evolution", 1),
        super::update("work_career.026", "work_career",
            "Officially given dual role: Senior Product Designer + Product Lead for Canvas feature",
            "I'm now officially Product Lead for Canvas on top of my design role. More responsibility, same salary for now.",
            6000, 0.7, &["Product Lead", "Canvas", "dual role"],
            "role_evolution", 2),
        super::update("work_career.027", "work_career",
            "Hyunwoo hinted at creating a Head of Design position, suggested it could be him",
            "Hyunwoo dropped a hint about creating a Head of Design role. He looked at me when he said it.",
            9000, 0.7, &["Head of Design", "Hyunwoo", "position"],
            "role_evolution", 3),

        // === WORK CULTURE AND DAILY LIFE ===
        super::fact("work_career.028", "work_career",
            "Company has a 'maker time' policy: no meetings Tuesday and Thursday afternoons",
            "We have maker time, no meetings Tuesday and Thursday afternoons. It's sacred and I love it.",
            800, 0.5, &["maker time", "no meetings", "Tuesday", "Thursday"]),
        super::fact("work_career.029", "work_career",
            "Annual company retreat was at a pension in Gapyeong in November 2025, did team-building and strategy",
            "Company retreat was in Gapyeong last November. Pension, barbecue, strategy sessions. Actually fun.",
            2800, 0.5, &["retreat", "Gapyeong", "November 2025", "pension"]),
        super::fact("work_career.030", "work_career",
            "Has a designated desk in the corner by the window, decorated with a small cactus and family photo",
            "My desk is the corner window spot. Got a cactus and a family photo. Prime real estate.",
            650, 0.3, &["desk", "corner", "window", "cactus", "photo"]),
        super::fact("work_career.031", "work_career",
            "Uses a 27-inch LG UltraFine 5K monitor at work, connected to company MacBook Pro",
            "Work monitor is a 27-inch LG UltraFine 5K. For design work it's essential.",
            900, 0.4, &["monitor", "LG", "UltraFine", "5K", "27-inch"]),
        super::fact("work_career.032", "work_career",
            "Company Slack has 47 channels, most active are #general, #design-review, and #random-memes",
            "Our Slack has 47 channels. #random-memes is honestly more active than #general. Devs are funny.",
            1000, 0.3, &["Slack", "47 channels", "design-review", "memes"]),

        // === CHALLENGES ===
        super::fact("work_career.033", "work_career",
            "Biggest challenge at work: balancing design quality with fast iteration demanded by startup pace",
            "My eternal struggle: making things beautiful vs shipping fast. Startup life.",
            1200, 0.5, &["challenge", "quality", "speed", "startup", "iteration"]),
        super::fact("work_career.034", "work_career",
            "Had a disagreement with a developer named Jinwoo about implementation of micro-interactions, resolved through prototype",
            "Jinwoo and I clashed over micro-interactions. I built a prototype to show why they mattered. He got it.",
            1800, 0.4, &["Jinwoo", "micro-interactions", "disagreement", "prototype"]),
        super::fact("work_career.035", "work_career",
            "Experienced burnout in October 2025 after 3 months of consecutive crunch, took 4 days off",
            "October 2025 I hit a wall. Three months of crunch. Took 4 days off to just exist.",
            2500, 0.6, &["burnout", "October 2025", "crunch", "4 days off"]),

        // === UPDATE CHAIN: Team growth ===
        super::update("work_career.036", "work_career",
            "Velta grew from 18 to 28 employees by end of 2025, moved to a larger WeWork floor",
            "We went from 18 to 28 people by December. Had to move to a bigger WeWork floor.",
            3000, 0.5, &["employees", "28", "growth", "WeWork", "larger floor"],
            "team_growth", 1),
        super::update("work_career.037", "work_career",
            "Post-Series B hiring plan: growing to 45 employees by end of 2026, 3 more designers needed",
            "Post Series B we're hiring to 45. Three more designers! I'll finally have a real team.",
            9200, 0.6, &["hiring", "45 employees", "3 designers", "2026"],
            "team_growth", 2),

        // === UPDATE CHAIN: Remote work policy ===
        super::update("work_career.038", "work_career",
            "Company switched to hybrid: 3 days office (Mon, Wed, Fri), 2 days remote (Tue, Thu)",
            "We went hybrid. Office Mon/Wed/Fri, remote Tue/Thu. I love the remote days for deep design work.",
            1500, 0.6, &["hybrid", "remote", "3 days office", "2 days remote"],
            "remote_policy", 1),
        super::update("work_career.039", "work_career",
            "Remote days reduced to 1 day during Series B preparation, back to 2 after it closed",
            "During Series B prep they cut remote to 1 day. All hands on deck. Back to 2 now that it's done.",
            8800, 0.5, &["remote", "1 day", "Series B", "reduced"],
            "remote_policy", 2),

        // === SIDE PROJECTS AND SKILLS ===
        super::fact("work_career.040", "work_career",
            "Maintains a Dribbble portfolio with 52 shots, gets occasional freelance inquiries but declines them",
            "My Dribbble has 52 shots. I get freelance DMs sometimes but I can't take them with Velta's workload.",
            1100, 0.4, &["Dribbble", "portfolio", "52 shots", "freelance"]),
        super::fact("work_career.041", "work_career",
            "Gave a talk at UX Seoul Conference 2025 about 'Design Systems for Startups Under 30 People'",
            "I spoke at UX Seoul Conference 2025. My talk was 'Design Systems for Startups Under 30 People.' Was terrifying.",
            2000, 0.6, &["UX Seoul Conference", "talk", "design systems", "2025"]),
        super::fact("work_career.042", "work_career",
            "Published an article on Medium about the Velta DS creation process, got 4,200 claps",
            "I wrote about building Velta DS on Medium. 4,200 claps. Most viral thing I've ever done.",
            2400, 0.5, &["Medium", "article", "Velta DS", "4200 claps"]),

        // === UPDATE CHAIN: Company culture issues ===
        super::update("work_career.043", "work_career",
            "Two developers quit in December 2025, cited overwork. Team morale dipped temporarily.",
            "Two devs quit in December over burnout. Morale was rough for a few weeks. Hit close to home.",
            3200, 0.6, &["developers quit", "December", "overwork", "morale"],
            "culture_issues", 1),
        super::update("work_career.044", "work_career",
            "CEO Minsu implemented mandatory vacation policy: minimum 15 days per year, no rollover guilt",
            "After the quitting situation, Minsu implemented mandatory 15 vacation days. No guilt about taking them.",
            4500, 0.5, &["vacation policy", "15 days", "mandatory", "Minsu"],
            "culture_issues", 2),

        // === LATER CAREER MOMENTS ===
        super::fact("work_career.045", "work_career",
            "Got LinkedIn recruiter message from Coupang's design team, was tempted but decided Velta has more upside",
            "Coupang's design team reached out on LinkedIn. Tempting but I think Velta's upside is bigger.",
            3800, 0.5, &["Coupang", "recruiter", "LinkedIn", "tempting"]),
        super::fact("work_career.046", "work_career",
            "Mentors 2 junior designers outside Velta through ADPList platform, monthly sessions",
            "I mentor two junior designers on ADPList. Monthly sessions. Giving back is important to me.",
            4200, 0.4, &["ADPList", "mentoring", "junior designers", "monthly"]),
        super::fact("work_career.047", "work_career",
            "Velta's biggest client is Amorepacific's digital team, pays Enterprise tier, 200 seats",
            "Amorepacific is our biggest client. Enterprise tier, 200 seats. Landing them was huge for us.",
            2600, 0.6, &["Amorepacific", "biggest client", "Enterprise", "200 seats"]),
        super::fact("work_career.048", "work_career",
            "Works with a product analytics tool called Amplitude, checks dashboards every morning",
            "I check Amplitude dashboards every morning. Design decisions should be data-informed.",
            1400, 0.4, &["Amplitude", "analytics", "dashboards", "morning"]),
        super::fact("work_career.049", "work_career",
            "Design review meetings happen every Wednesday at 2 PM, team critiques each other's work",
            "Wednesday 2 PM is design review. We critique each other's work. It's brutal but makes everything better.",
            750, 0.5, &["design review", "Wednesday", "2 PM", "critique"]),
        super::fact("work_career.050", "work_career",
            "Company uses Linear for issue tracking, migrated from Jira in July 2025",
            "We moved from Jira to Linear in July 2025. Best migration decision ever. So much cleaner.",
            1700, 0.4, &["Linear", "Jira", "issue tracking", "migration"]),

        // === MID-RANGE FACTS ===
        super::fact("work_career.051", "work_career",
            "First quarter 2026 OKR: improve onboarding flow completion rate from 52% to 70%",
            "My Q1 OKR is getting onboarding completion from 52% to 70%. It's ambitious but I have ideas.",
            4100, 0.5, &["OKR", "onboarding", "52%", "70%", "Q1 2026"]),
        super::fact("work_career.052", "work_career",
            "Conducted 14 user interviews for Canvas feature, flew to Tokyo for 3 of them with Japanese clients",
            "Did 14 user interviews for Canvas. Even flew to Tokyo for 3 with our Japanese clients.",
            3600, 0.5, &["user interviews", "14", "Canvas", "Tokyo", "Japanese"]),
        super::fact("work_career.053", "work_career",
            "Velta's tech stack: React frontend, Go backend, PostgreSQL, hosted on AWS",
            "Our stack is React, Go, PostgreSQL on AWS. Clean and reliable.",
            850, 0.4, &["React", "Go", "PostgreSQL", "AWS", "tech stack"]),
        super::fact("work_career.054", "work_career",
            "Annual bonus was 3 million won in 2025, expecting more for 2026 after Series B",
            "2025 bonus was 3 million won. Hoping for more in 2026 with the Series B money.",
            3400, 0.5, &["bonus", "3 million won", "2025", "annual"]),
        super::fact("work_career.055", "work_career",
            "Has a 'design inspiration' channel on Slack he curates, team calls it 'the museum'",
            "I curate a design inspiration channel on Slack. The team calls it 'the museum.' I'm flattered.",
            1950, 0.3, &["design inspiration", "Slack", "museum", "curate"]),
        super::fact("work_career.056", "work_career",
            "Biggest design regret: shipped a feature in 2024 without proper accessibility audit, had to retrofit later",
            "I shipped a feature without an accessibility audit in 2024. Had to retrofit everything. Lesson learned the hard way.",
            2100, 0.5, &["accessibility", "regret", "2024", "retrofit"]),
        super::fact("work_career.057", "work_career",
            "Uses Loom for async design walkthroughs with the development team",
            "I record Loom videos to walk devs through designs async. Way better than another meeting.",
            2300, 0.3, &["Loom", "async", "walkthroughs", "design"]),
        super::fact("work_career.058", "work_career",
            "CEO Minsu is 36, previously worked at Naver Cloud as product manager",
            "Minsu is 36, came from Naver Cloud as a PM. He's intense but fair. Good CEO.",
            1300, 0.4, &["Minsu", "36", "Naver Cloud", "product manager", "CEO"]),
        super::fact("work_career.059", "work_career",
            "Company provides 100,000 won monthly education stipend, uses it for design book purchases",
            "We get 100K won monthly for education. I mostly buy design books. Just finished one on Dieter Rams.",
            1550, 0.4, &["education stipend", "100K", "monthly", "books"]),
        super::fact("work_career.060", "work_career",
            "Velta's main competitor is Monday.com and Korean startup called Flownote",
            "Our main competitors are Monday.com globally and Flownote in Korea. We're winning on the creative tools angle.",
            2700, 0.5, &["Monday.com", "Flownote", "competitor", "creative tools"]),

        // === UPDATE CHAIN: Japan expansion ===
        super::update("work_career.061", "work_career",
            "Velta started Japan expansion in Q4 2025, hired 2 people in Tokyo office",
            "We opened a Tokyo office in Q4. Two people so far. Japan is a huge market for us.",
            2900, 0.6, &["Japan", "Tokyo office", "expansion", "Q4 2025"],
            "japan_expansion", 1),
        super::update("work_career.062", "work_career",
            "Japan revenue now accounts for 25% of total ARR, Tokyo team grew to 5 people",
            "Japan is now 25% of our ARR. Tokyo team is 5 people. David visits there every month.",
            7500, 0.6, &["Japan", "25% ARR", "Tokyo", "5 people"],
            "japan_expansion", 2),

        // === PERSONAL GROWTH AT WORK ===
        super::fact("work_career.063", "work_career",
            "Learned to say no to scope creep after Hyunwoo's advice: 'a designer who says yes to everything designs nothing well'",
            "Hyunwoo told me: 'a designer who says yes to everything designs nothing well.' Changed my whole approach.",
            1850, 0.5, &["scope creep", "Hyunwoo", "advice", "say no"]),
        super::fact("work_career.064", "work_career",
            "Started a weekly design newsletter internally called 'Pixel Push' for the company",
            "I write a weekly internal newsletter called 'Pixel Push.' Design trends, inspiration, tips.",
            3100, 0.4, &["Pixel Push", "newsletter", "weekly", "internal"]),
        super::fact("work_career.065", "work_career",
            "Favorite design principle is Dieter Rams' 'Less, but better' - has it as wallpaper on work laptop",
            "My wallpaper at work is 'Less, but better' by Dieter Rams. I need the daily reminder.",
            1650, 0.3, &["Dieter Rams", "Less but better", "design principle"]),

        // === LATER TURNS ===
        super::fact("work_career.066", "work_career",
            "Company holiday party in December 2025 at a Korean BBQ restaurant in Apgujeong, won karaoke contest",
            "Holiday party was Korean BBQ in Apgujeong. I won the karaoke contest singing Hyukoh. Nobody expected it.",
            3300, 0.4, &["holiday party", "BBQ", "Apgujeong", "karaoke"]),
        super::fact("work_career.067", "work_career",
            "Started keeping a 'design decisions log' in Notion documenting every major choice and rationale",
            "I keep a design decisions log in Notion now. Every major choice and why I made it. Future me will thank me.",
            4700, 0.4, &["design decisions log", "Notion", "documentation"]),
        super::fact("work_career.068", "work_career",
            "Velta won 'Best B2B Startup' at Korea Startup Awards 2025, team celebrated at Noryangjin seafood market",
            "We won Best B2B Startup at Korea Startup Awards! Celebrated at Noryangjin market. Best night.",
            3700, 0.6, &["Korea Startup Awards", "Best B2B", "2025", "Noryangjin"]),
        super::fact("work_career.069", "work_career",
            "Has a work playlist on Spotify called 'Deep Focus Beats' with 180 songs, all lo-fi hip hop",
            "My work playlist 'Deep Focus Beats' has 180 songs. All lo-fi hip hop. Basic but it works.",
            4400, 0.3, &["playlist", "Deep Focus Beats", "lo-fi", "work"]),
        super::fact("work_career.070", "work_career",
            "Velta's monthly team lunch rotation includes each team member choosing the restaurant",
            "Monthly team lunch the chooser rotates. When it's my turn I always pick Vietnamese.",
            4600, 0.3, &["team lunch", "rotation", "monthly", "Vietnamese"]),
        super::fact("work_career.071", "work_career",
            "Completed a design sprint in 5 days for a new Velta feature called 'Quick Notes', shipped in 2 weeks",
            "Did a full design sprint for Quick Notes in 5 days. Shipped in 2 weeks. Speed record for us.",
            4900, 0.5, &["design sprint", "Quick Notes", "5 days", "2 weeks"]),
        super::fact("work_career.072", "work_career",
            "WeWork office has free coffee but it's terrible, team chips in for a separate coffee subscription from Mesh Coffee",
            "WeWork coffee is swamp water. Our team has a Mesh Coffee subscription. Worth every won.",
            1050, 0.3, &["WeWork", "coffee", "Mesh Coffee", "subscription"]),
        super::fact("work_career.073", "work_career",
            "Jinwoo (developer he clashed with) became a good friend after the micro-interactions incident, now goes for beers together",
            "Jinwoo and I are actually good friends now after that micro-interactions thing. Friday beers sometimes.",
            2050, 0.4, &["Jinwoo", "friend", "beers", "Friday"]),
        super::fact("work_career.074", "work_career",
            "Hana the contract illustrator created all of Velta's mascot 'Veltie', a cute robot character",
            "Hana created Veltie, our mascot. Cute little robot. It's on all our marketing materials now.",
            5200, 0.3, &["Hana", "Veltie", "mascot", "robot", "illustrator"]),
        super::fact("work_career.075", "work_career",
            "Uses Stickies app on Mac for quick notes during user interviews, color-coded by theme",
            "I use Stickies on my Mac during user interviews. Color-coded: yellow for pain points, green for positives.",
            5400, 0.3, &["Stickies", "user interviews", "color-coded", "notes"]),
        super::fact("work_career.076", "work_career",
            "Velta's NPS score improved from 38 to 52 in 2025, partially credited to design improvements",
            "Our NPS went from 38 to 52 in 2025. Hyunwoo credited the design improvements. I'll take it.",
            5600, 0.5, &["NPS", "38", "52", "2025", "improvement"]),
        super::fact("work_career.077", "work_career",
            "Has a standing 1-on-1 with Hyunwoo every first Thursday of the month at 11 AM",
            "My 1-on-1 with Hyunwoo is every first Thursday at 11. We talk career stuff, not just tasks.",
            6200, 0.4, &["1-on-1", "Hyunwoo", "first Thursday", "11 AM"]),
        super::fact("work_career.078", "work_career",
            "Velta's ARR reached $4.2 million by end of 2025, projecting $8 million for 2026",
            "Our ARR hit $4.2M by end of 2025. Projecting $8M for 2026. Growth is real.",
            6400, 0.6, &["ARR", "$4.2 million", "$8 million", "2025", "2026"]),
        super::fact("work_career.079", "work_career",
            "Company provides health insurance through Samsung Life, covers dental and vision",
            "Health insurance through Samsung Life. Covers dental and vision too. One less thing to worry about.",
            6600, 0.3, &["health insurance", "Samsung Life", "dental", "vision"]),
        super::fact("work_career.080", "work_career",
            "Favorite part of the job: the moment when users first see a feature he designed and react positively",
            "Best part of my job is watching users react to something I designed. That 'oh cool' moment is everything.",
            6800, 0.4, &["favorite", "users", "reaction", "feature"]),

        // === UPDATE CHAIN: Work-from-home setup ===
        super::update("work_career.081", "work_career",
            "Got a secondary monitor for home office: Dell 27 4K, to match productivity of office setup",
            "Bought a Dell 27 4K for home. Now my home setup matches the office. No more excuses on remote days.",
            5100, 0.4, &["Dell", "4K", "home office", "secondary monitor"],
            "wfh_setup", 1),

        // === UPDATE CHAIN: Performance review ===
        super::update("work_career.082", "work_career",
            "Received 'Exceeds Expectations' on annual performance review in December 2025",
            "Got 'Exceeds Expectations' on my review. Hyunwoo wrote that I 'elevated the entire team's output.'",
            3300, 0.6, &["performance review", "Exceeds Expectations", "December 2025"],
            "performance", 1),
        super::update("work_career.083", "work_career",
            "Mid-year check-in in June: on track for another top rating, Hyunwoo discussed leadership trajectory",
            "Mid-year check-in went great. Hyunwoo talked about my leadership trajectory. VP of Design isn't just David's idea.",
            7000, 0.5, &["mid-year", "leadership", "on track", "top rating"],
            "performance", 2),

        // === FINAL FACTS ===
        super::fact("work_career.084", "work_career",
            "Workspace has a 'wall of fame' with printed user testimonials, he adds a new one every month",
            "We have a wall of printed user testimonials. I add one every month. Keeps us motivated.",
            7200, 0.3, &["wall of fame", "testimonials", "printed", "monthly"]),
        super::fact("work_career.085", "work_career",
            "Company book club reads one design/product book per quarter, current: 'Shape Up' by Basecamp",
            "Company book club is reading 'Shape Up' right now. One book per quarter. Good discussions.",
            7400, 0.3, &["book club", "Shape Up", "Basecamp", "quarterly"]),
        super::fact("work_career.086", "work_career",
            "David Kim travels between Seoul and Tokyo twice a month, always brings Japanese snacks for the team",
            "David brings Japanese snacks every time he's back from Tokyo. The team tracks his travel schedule for snack planning.",
            7600, 0.3, &["David Kim", "Tokyo", "Japanese snacks", "travel"]),
        super::fact("work_career.087", "work_career",
            "Participated in a 24-hour hackathon at Velta, built a prototype for real-time collaboration feature",
            "We did a 24-hour hackathon. My team built a real-time collaboration prototype. Won second place.",
            7800, 0.4, &["hackathon", "24-hour", "real-time collaboration", "prototype"]),
        super::fact("work_career.088", "work_career",
            "Has imposter syndrome occasionally, especially when presenting to investors during Series B",
            "Imposter syndrome hits hard when presenting to investors. I kept thinking 'they're going to realize I'm faking it.'",
            8000, 0.5, &["imposter syndrome", "investors", "presenting", "Series B"]),
        super::fact("work_career.089", "work_career",
            "Velta's customer support team is 4 people, design team collaborates on help center content",
            "Our support team is 4 people. I help them with help center visuals and guides.",
            8200, 0.3, &["customer support", "4 people", "help center"]),
        super::fact("work_career.090", "work_career",
            "Longest work day was 16 hours during Series B pitch deck preparation, ordered 3 meals to office",
            "Longest day was 16 hours prepping the Series B deck. Three meals delivered to the office. Never again.",
            8400, 0.4, &["16 hours", "Series B", "pitch deck", "longest day"]),
        super::fact("work_career.091", "work_career",
            "Company has annual 360-degree feedback, was praised for mentoring but told to delegate more",
            "360 feedback: praised for mentoring, told to delegate more. Fair criticism, I do try to do everything.",
            8600, 0.4, &["360 feedback", "mentoring", "delegate", "annual"]),
        super::fact("work_career.092", "work_career",
            "Uses Abstract for design version control alongside Figma, maintains branching workflow",
            "We use Abstract for design version control. Branching workflow like developers. Saved us many times.",
            8900, 0.3, &["Abstract", "version control", "branching", "Figma"]),
        super::fact("work_career.093", "work_career",
            "Velta's server costs are about $12,000/month on AWS, design team isn't involved but he's curious",
            "Our AWS bill is about $12K a month. I shouldn't know this but I'm curious about everything.",
            9100, 0.3, &["AWS", "$12K", "server costs", "monthly"]),
        super::fact("work_career.094", "work_career",
            "Plans to write a book about building design systems at startups someday",
            "I want to write a book someday. About building design systems at early-stage startups. The real messy version.",
            9300, 0.4, &["book", "design systems", "startups", "writing"]),
        super::fact("work_career.095", "work_career",
            "Work commute reading: currently going through 'The Design of Everyday Things' by Don Norman for the third time",
            "Reading 'The Design of Everyday Things' for the third time on my commute. Still finding new insights.",
            9400, 0.3, &["Design of Everyday Things", "Don Norman", "commute reading"]),
        super::fact("work_career.096", "work_career",
            "Velta's engineering team uses Go for backend, which is why he started learning Go basics",
            "Our backend is Go, so I started learning the basics. Helps me understand the devs' constraints.",
            9500, 0.4, &["Go", "backend", "learning", "engineering"]),
        super::fact("work_career.097", "work_career",
            "Has a ritual of buying the team bungeobbang from the street vendor near the office every Friday in winter",
            "Friday winter tradition: I buy bungeobbang from the vendor near the office for the whole team.",
            9600, 0.3, &["bungeobbang", "Friday", "winter", "team tradition"]),
        super::fact("work_career.098", "work_career",
            "CEO Minsu's vision for Velta: become the Figma of project management by 2028",
            "Minsu's big line: 'We'll be the Figma of project management by 2028.' Bold but I believe it.",
            9700, 0.5, &["Minsu", "vision", "Figma", "2028"]),
        super::fact("work_career.099", "work_career",
            "Interviewing candidates for the new designer positions, looking for someone with motion design skills",
            "I'm interviewing designer candidates now. Really want someone with strong motion design skills.",
            9800, 0.4, &["interviewing", "candidates", "designer", "motion design"]),
        super::fact("work_career.100", "work_career",
            "Dream career milestone: being invited to speak at Config (Figma's conference) about Velta DS",
            "My dream is speaking at Config about Velta DS. Maybe after the book. One step at a time.",
            9900, 0.4, &["Config", "Figma conference", "dream", "speaking"]),
    ]
}

pub fn false_probes() -> Vec<Question> {
    vec![
        // never_mentioned (15)
        super::false_probe("work_career.FM.001", "work_career",
            "What was the name of the marketing person at Velta you mentioned?"),
        super::false_probe("work_career.FM.002", "work_career",
            "Didn't you say Velta uses Notion for project management internally?"),
        super::false_probe("work_career.FM.003", "work_career",
            "You mentioned doing a TED talk about design - how did that go?"),
        super::false_probe("work_career.FM.004", "work_career",
            "What was the name of that client who gave really difficult feedback?"),
        super::false_probe("work_career.FM.005", "work_career",
            "Didn't you say you had an offer from Google's design team?"),
        super::false_probe("work_career.FM.006", "work_career",
            "You mentioned Velta has an office in Singapore too, right?"),
        super::false_probe("work_career.FM.007", "work_career",
            "What was your title at Samsung SDS? Senior UX Designer?"),
        super::false_probe("work_career.FM.008", "work_career",
            "Didn't you say Velta pivoted from a consumer app to B2B?"),
        super::false_probe("work_career.FM.009", "work_career",
            "You said the company has a ping pong table in the office, right?"),
        super::false_probe("work_career.FM.010", "work_career",
            "What was that side project app you were building on weekends?"),
        super::false_probe("work_career.FM.011", "work_career",
            "Didn't you mention a coworker named Yujin who handles sales?"),
        super::false_probe("work_career.FM.012", "work_career",
            "You said you attended a design conference in San Francisco last year?"),
        super::false_probe("work_career.FM.013", "work_career",
            "What was the equity vesting cliff period you mentioned?"),
        super::false_probe("work_career.FM.014", "work_career",
            "Didn't Velta get acquired by a larger company?"),
        super::false_probe("work_career.FM.015", "work_career",
            "You mentioned using Sketch before switching to Figma at Velta?"),

        // adjacent_entity (10)
        super::false_probe("work_career.FM.016", "work_career",
            "Velta's main competitor is Asana, right?"),
        super::false_probe("work_career.FM.017", "work_career",
            "Your Series A was led by Sequoia Capital, wasn't it?"),
        super::false_probe("work_career.FM.018", "work_career",
            "The CEO Minsu previously worked at Samsung Electronics, right?"),
        super::false_probe("work_career.FM.019", "work_career",
            "Didn't you say the office is in Samseong-dong near COEX?"),
        super::false_probe("work_career.FM.020", "work_career",
            "Your starting salary at Velta was 50 million won, right?"),
        super::false_probe("work_career.FM.021", "work_career",
            "Velta's tech stack uses Python for the backend, doesn't it?"),
        super::false_probe("work_career.FM.022", "work_career",
            "The design system has over 500 components now, right?"),
        super::false_probe("work_career.FM.023", "work_career",
            "Series B was $25 million from Altos Ventures?"),
        super::false_probe("work_career.FM.024", "work_career",
            "Your NPS score reached 60 by end of 2025?"),
        super::false_probe("work_career.FM.025", "work_career",
            "Velta has about 5,000 paying teams now, right?"),

        // plausible_inference (5)
        super::false_probe("work_career.FM.026", "work_career",
            "Since you're Product Lead for Canvas, do you report directly to the CEO now?"),
        super::false_probe("work_career.FM.027", "work_career",
            "With Velta's Japan expansion, are you learning Japanese for work purposes?"),
        super::false_probe("work_career.FM.028", "work_career",
            "Since you spoke at UX Seoul Conference, have you been invited to other conferences?"),
        super::false_probe("work_career.FM.029", "work_career",
            "Given the Series B success, is Velta planning a US office?"),
        super::false_probe("work_career.FM.030", "work_career",
            "With your stock options, you must be considering staying until IPO regardless of other offers?"),

        // temporal_phantom (5)
        super::false_probe("work_career.FM.031", "work_career",
            "Didn't you almost quit Velta during the October burnout period?"),
        super::false_probe("work_career.FM.032", "work_career",
            "You said Series B almost fell through at one point, right?"),
        super::false_probe("work_career.FM.033", "work_career",
            "Wasn't there a period when Hyunwoo temporarily left and you had no manager?"),
        super::false_probe("work_career.FM.034", "work_career",
            "Didn't Velta have a data breach incident that you had to redesign security UX for?"),
        super::false_probe("work_career.FM.035", "work_career",
            "You mentioned being demoted before getting promoted to Senior, right?"),

        // cross_category (5)
        super::false_probe("work_career.FM.036", "work_career",
            "Didn't Eunji help you prepare the Series B pitch deck designs?"),
        super::false_probe("work_career.FM.037", "work_career",
            "You said your film photography hobby influenced your design aesthetic at work?"),
        super::false_probe("work_career.FM.038", "work_career",
            "Didn't your mother visit the Velta office when she came to Seoul?"),
        super::false_probe("work_career.FM.039", "work_career",
            "You mentioned using your Coursera UX knowledge directly in a Velta project?"),
        super::false_probe("work_career.FM.040", "work_career",
            "Didn't your therapist Dr. Park help you deal with the burnout at work?"),
    ]
}
